### ISSUE TITLE
bug on crm while trying to open the selector for owner ( while creating a new account)

### ISSUE THREAD

**Issue by dardoguidobono** [orocrm/platform#109]
Catchable fatal error: Argument 1 passed to Oro\Bundle\DataGridBundle\Twig\DataGridExtension::getGridMetadata() must be an instance of Oro\Bundle\DataGridBundle\Datagrid\DatagridInterface, null given, called in /opt/local/apache2/htdocs/tests/crm-application/app/cache/prod/twig/10/66/490928cf785614100bc146d30cb15eb16eaabf3610924eaeb4e05d745a1d.php on line 38 and defined in /opt/local/apache2/htdocs/tests/crm-application/vendor/oro/platform/src/Oro/Bundle/DataGridBundle/Twig/DataGridExtension.php on line 78

**Comment by sergeyz** [comment]
Hi, @dardoguidobono!
fixed here https://github.com/orocrm/platform/commit/7c1b6bde0dd519501f276c2639a1f7ef8440827f

Thanks for report!
