### ISSUE TITLE
Improve API DOC

### ISSUE THREAD

**Issue by kelton23om** [orocrm/platform#115]
In order to group resources in the documentation.
Is it possible to add the "section" property, in all API Controllers ?
this could allow two things:
 - render the documentation more readable
 - add exclusion policies

**Comment by artml** [comment]
@kelton23om our new API should really improve the state of things. Please check the [documentation](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/ApiBundle/Resources/doc/index.md) if you're interested.
