### ISSUE TITLE
Calendar - timezone issues

### ISSUE THREAD

**Issue by nenadalm** [orocrm/platform#138]
As I know - datetimes should be stored in UTC in the platform.

If I create event at: Aug 5, 2014, 5:00 AM
it stores: 2014-08-05 03:00:00 (which is correct)

But If I create event at: Jan 23, 2015, 5:00 AM
it stores: 2015-01-23 03:00:00 (should be 2015-01-23 04:00:00)
(http://www.timeanddate.com/worldclock/converted.html?iso=20140123T05&p1=204&p2=204)

on the dashboard it shows correctly (5 am) but in the database it's wrong (which complicates to add events programatically)

**Comment by artml** [comment]
@nenadalm can you please check if it's still relevant? thanks.

**Comment by artml** [comment]
closing due to no feedback
