### ISSUE TITLE
Loggable and Versioned Annotations

### ISSUE THREAD

**Issue by LRotherfield** [orocrm/platform#150]
Do these annotations work on their own at the moment?  Just following through the event listener, it seems that in order to create a log entry, the entity must be in the config manager and the entity must be marked as auditable:
https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DataAuditBundle/Loggable/LoggableManager.php#L263
https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DataAuditBundle/Loggable/LoggableManager.php#L492

**Comment by dima-welance** [comment]
Is the @Versioned annotation still not supported ?

**Comment by iklymenko** [comment]
Hi dima-welance, unfortunately, no.
