### ISSUE TITLE
No entity relationships generated

### ISSUE THREAD

**Issue by dtzubertowski** [orocrm/platform#152]
Whenever I create an entity, or extend existing one, oro seems to ignore the relations on the DB. For example in my migration schema:

        $table = $schema->createTable('account_extension_request');
        $table->addColumn('id', 'integer', ['autoincrement' => true]);
        $table->addColumn('user_owner_id', 'integer', ['notnull' => false]);
        $table->addColumn('opportunity_id', 'integer', ['notnull' => false]);
        $table->addColumn('status', 'integer', []);
        $table->addColumn('createdAt', 'datetime', []);
        $table->addColumn('updatedAt', 'datetime', []);
        $table->setPrimaryKey(['id']);
        $table->addIndex(['opportunity_id'], 'IDX_6004BACA9A34590F', []);
        $table->addIndex(['user_owner_id'], 'FK_6004BACA9EB185F9', []);

        $table->addForeignKeyConstraint(
            $schema->getTable('oro_user'),
            ['user_owner_id'],
            ['id'],
            ['onDelete' => 'SET NULL', 'onUpdate' => null]
        );

I can't relate to the user_owner_id in any way. Moreover in the file there's no data about this extension added:
- app/cache/dev/oro-entities/Extend/Entity/ExtendUser.orm.yml

  Extend\Entity\ExtendUser:
    type: mappedSuperclass
    fields: {  }

**Comment by artml** [comment]
@dtzubertowski by any chance, do you still experiencing the issue? Apologies for the _very_ late response.

**Comment by sergeyz** [comment]
Its not a bug, @dtzubertowski added foreign key to database but didn't provide any custom property for it. See https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/EntityExtendBundle/README.md#add-relation for more details

**Comment by artml** [comment]
Ah, okay. Thanks @sergeyz
