### ISSUE TITLE
DataAuditBundle: Fatal error: Nesting level too deep

### ISSUE THREAD

**Issue by nenadalm** [orocrm/platform#159]
Fatal error: Nesting level too deep - recursive dependency? in /srv/www/orocrm-new/vendor/oro/platform/src/Oro/Bundle/DataAuditBundle/Loggable/LoggableManager.php on line ...

https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DataAuditBundle/Loggable/LoggableManager.php#L291

maybe use "$old === $new" instead of "$old == $new"?

**Comment by artml** [comment]
The fix is merged within 1.10 release
