### ISSUE TITLE
Bug in SearchHandler

### ISSUE THREAD

**Issue by stalxed** [orocrm/platform#167]
Contitions for this bug:
1) Custom entity without owner(becose this entity don't have role ASSIGN).

File with bug:  platform / src / Oro / Bundle / FormBundle / Autocomplete / SearchHandler.php
URL: https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/FormBundle/Autocomplete/SearchHandler.php
Line number: 176
Code:
```php
$query = $this->aclHelper->apply($queryBuilder, 'ASSIGN');
```

Fix of this bug:
replace this line to:
```php
$query = $this->aclHelper->apply($queryBuilder, 'VIEW');
```

Please include this fix in next realise!

**Comment by artml** [comment]
This has been fixed in 1.8 version.
