### ISSUE TITLE
Previous version developed datagrids don't work on new version

### ISSUE THREAD

**Issue by etcware** [orocrm/platform#174]
Please, let me know without debugging all, why my datagrids don’t work in orocrm new version. What are the differences between datagrid in orocrm 1.3 and 1.4?
I don't know the corresponding platform version.
As supplementary information I’ve seen in log file this query about my entity:
```
SELECT e0_.id AS id0, e0_.title AS title1, e1_.label AS label2,   
e0_.description AS description3, e2_.title AS title4 FROM educacloud_event e0_   
LEFT JOIN educacloud_event_status e1_ ON e0_.status_id = e1_.id   
LEFT JOIN educacloud_event e2_ ON e0_.edition_event_id = e2_.id   
WHERE e0_.parent_event_id IS NULL AND 1 = 0
```
As you can see the query with condition “AND 1 = 0″ returns 0 items!
This happens on the new version while in 1.3 my datagrids work fine.
thanks
Alessandra

**Comment by MikeParkin** [comment]
Hi,

We also hit this issue, will it be possible for you to create a migration to solve this?

How did you do this for your SaaS customers? They presumably have the same issue?

Thanks
Mike

**Comment by artml** [comment]
@MikeParkin do you still experience the issue?

**Comment by artml** [comment]
closing due to no feedback
