### ISSUE TITLE
REST raw methods with orocrm give me an error

### ISSUE THREAD

**Issue by etcware** [orocrm/platform#176]
I'm trying to implement a REST stub bundle to anticipate REST integration. FOSREST methods have not related entities so I need to use raw http Response to return data to the client. My stub REST is for example:  
```
 /**
     * Get contact events
     *
     * @Get("/contactEvents/{cf}")
     *
     * @ApiDoc(
     *      description="returns contact events"
     * )
     * @AclAncestor("acl_educaevent_view")
     */
public function getContactEventsAction($cf)
    {
        $logger = $this->get('logger');
        $logger->info(' ------------- Contact cf '.$cf);
        // deve restituire una lista di educaevents
        $result = ...;
        return new Response(json_encode($result), Codes::HTTP_OK);
    }
```
When I try it by using Chrome with Advanced REST client it returns 200OK but the next access to orocrm 
give me this result:
```
Fatal error: Call to a member function getId() on a non-object in /Users/ale/Sites/crm-application/vendor/oro/platform/src/Oro/Bundle/SecurityBundle/Http/Firewall/ContextListener.php on line 39
```
And it returns to work after Chrome cache clearing.
Can you help me?
thanks 
Alessandra

**Comment by artml** [comment]
Since we migrate to JSON API I believe the issue is no longer relevant.
