### ISSUE TITLE
doctrine:mapping:import - error (Property "email" in "OroUser" was already declared)

### ISSUE THREAD

**Issue by madmis** [orocrm/platform#182]
I run command
```
app/console doctrine:mapping:import "MdsExternalAccountBundle" yml --filter="mds_external_account" --force
```

And get error
```
[Doctrine\ORM\Mapping\MappingException]
  Property "email" in "OroUser" was already declared, but it must be declared only once
```

Why i have this error?
I use latest oro platform version

**Comment by dimonixx** [comment]
Hi
have you found any solution ?

**Comment by madmis** [comment]
No, i can't find solution. For now i don't work with oro.

**Comment by rodolfobandeira** [comment]
Hi there! I'm getting the same error here. By now I'm creating entity classes manually.

**Comment by mingxing** [comment]
Me too, any update?
Thanks

**Comment by easy-dev** [comment]
Well I still got this issue, when I'm trying to auto generate Entities I'm getting 

[Doctrine\ORM\Mapping\MappingException]                                                
Property "email" in "OroUser" was already declared, but it must be declared only once

**Comment by zebimax** [comment]
Unfortunately, Doctrine command "doctrine:mapping:import" can not run in Oro Platform based applications.
This command can be useful for simple databases([see details](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/tools.html#reverse-engineering)).
If your aim is to not write manually entities code and generate it, you can try to generate metadata files for your tables in other Symfony application and then use them in Oro application.
