### ISSUE TITLE
Add phone numbers to users

### ISSUE THREAD

**Issue by kmuenze** [orocrm/platform#188]
Currently a User does not have a phone number.

Adding a phone number to the user can act as an identifier similar to email.

It also has the added benefit of providing the ability for easy to create internal phone lists.

This is being moved from orocrm / crm  #83 to platform because I believe this is where it belongs.

**Comment by cawolf** [comment]
Hey, whats the status of this issue? We really like to customize our email communication and provide agent specific phone numbers for calls. Thank you,
best regars,
Christian

**Comment by DimaSoroka** [comment]
Hi @cawolf, this issue scheduled for development. You can create a custom field for your needs right now without this fix.

**Comment by cawolf** [comment]
Hi @DimaSoroka, thank you, we will wait for the next release,
best regards,
Christian

**Comment by artml** [comment]
Fixed this long ago.
