### ISSUE TITLE
Upgrade jQuery UI version to 1.11.x

### ISSUE THREAD

**Issue by Kidra** [orocrm/platform#191]
We have an issue where a wysiwyg editor in a UI dialog is having its iframe reset when another dialog takes focus and moves to the top of the stack, clearing all the content and rendering the editor unusable.   This would also be an issue with any videos or other iframe elements which get loaded in dialogs. The bug is documented here:

http://bugs.jqueryui.com/ticket/9166

The issue is resolved in jQuery UI 1.11.

**Comment by LRotherfield** [comment]
@DimaSoroka It looks like this is in the next version of the platform: https://github.com/orocrm/platform/commit/4b581845562ec6da30680e0197fe9387cc7a488e, do you have a hopeful release date for 1.7?

**Comment by DimaSoroka** [comment]
Yes, we are targeting end of April.

**Comment by artml** [comment]
Released within 1.7
