### ISSUE TITLE
missing __toString in entity leads to app being killed silently

### ISSUE THREAD

**Issue by adamjakab** [orocrm/platform#197]
Hi,

I have a working entity and a viewAction for it. When I was building the entity I have forgot to add a __toString method to it (I didn't think I needed one) and my view was not working. I realized there was something very wrong becasue the profiler bar below in dev environment would not renderer - my view got rendered up until the navigation bar but the "content_data" section would not appare.

The application died silently after having rendered the ownerLink (I think it died trying to render the link to the data audit link.).
![oroplatform-1](https://cloud.githubusercontent.com/assets/1028115/5262063/19e3566c-7a21-11e4-90d6-ba0440f744c1.png)

I am reporting this because the application would not give any visible exceptions (even though in the log I could find this:

```
event.INFO: An exception was thrown while getting the uncalled listeners (You cannot create a service ("oro_security.listener.api_listener") of an inactive scope ("request").) {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\InactiveScopeException: You cannot create a service (\"oro_security.listener.api_listener\") of an inactive scope (\"request\"). at /home/master.mekitcrm.bradipo/oro/app/cache/dev/appDevDebugProjectContainer.php:18314)"} []
```

After checking on a similar entity in my app and confronting them I noticed the missing __toString method, implemented it and the exception was gone.

I thik you can reproduce this by commenting out the __toString method on any entity and trying to access the viewAction for it.

Maybe a check should be implemented somewhere to give a 'visible' exception for this.
What do you think?

**Comment by LRotherfield** [comment]
@yshyshkin was there a specific commit that fixed this bug?  We have encountered the same error message and although we may be able to upgrade to solve the issue, if you could point us to the commit that fixed it that would be helpful.
