### ISSUE TITLE
Version 1.4.1 Datagrid Filter Display Bug

### ISSUE THREAD

**Issue by ghost** [orocrm/platform#202]
Hi Guys,

we Updated to Version 1.4.1 and found an little display Bug.
When you have an Datagrid on the Page without Data, you get the "Manage Filter" Dropdown on the very bottom left Side.
You can see this on your Demo here: http://demo.orocrm.com/marketing-list/

Best Regards
David

**Comment by artml** [comment]
The issue has been fixed in 1.5 release.
