### ISSUE TITLE
[RequireJsBundle] Definition "oro.cache.abstract" does not exist.

### ISSUE THREAD

**Issue by kayue** [orocrm/platform#215]
https://github.com/orocrm/RequireJSBundle/blob/81bb71982747f057fb262b2fc713f56a1b266965/Resources/config/services.yml#L14

I am getting the following error when I use RequireJSBundle standalone.

> The parent definition "oro.cache.abstract" defined for definition "oro_requirejs.cache" does not exist.

Can we drop this dependency?

**Comment by alsma-magecore** [comment]
Hello @kayue ! Thanks for raising up this issue. We tried to find good solution for this in #100 . If you have ideas how to drop this dependency feel free to submit PR or update initial one. 

Thank you!

**Comment by kayue** [comment]
@alsma-magecore May I know where is this service being used in the RequireJSBundle.

**Comment by alsma-magecore** [comment]
It's used [here](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/RequireJSBundle/Provider/Config.php#L71-71) for caching requireJS merged config.

**Comment by kayue** [comment]
Can we call setCache in PlatformBundle instead?

**Comment by artml** [comment]
@kayue have you managed to get rid of this dependency?

**Comment by ste93cry** [comment]
The PR #496 should help on this
