### ISSUE TITLE
Segments Definition Issue

### ISSUE THREAD

**Issue by rogyar** [orocrm/platform#216]
We have just faced with an issue: if you try to create a segment and apply to some "string" field the following kind of condition:
<fieldname> is equals to 'Value1'
or
<fieldname> is equals to 'Value2'
You will get list of all entities no matter what you have entered. Reproduced on 1.4, 1.5

![screen shot 2015-01-13 at 9 16 05 am](https://cloud.githubusercontent.com/assets/2148959/5717203/215b4210-9b05-11e4-9a68-1d2bbce3725f.png)

**Comment by mccar** [comment]
Hello @rogyar !
This bug has been fixed in version 1.5 and 1.6
Thank you!
