### ISSUE TITLE
Replacement of variables in datagrid.yml only works for the first match in line

### ISSUE THREAD

**Issue by mario-seidel** [orocrm/platform#220]
When you are using multiple variables for classes in a datagrid.yml, only the first one will be replaced 
correctly. I searched a little for the same usage in the platform code and was successful:

https://github.com/orocrm/platform/blob/f1d6ef9af4f01b1113fd61ed5482dfbd799e6a95/src/Oro/Bundle/EmailBundle/Resources/config/datagrid.yml#L89
```php
...
where:
    and:
        - f.type IN ('%oro_email.email_folder.model.class%::INBOX', '%oro_email.email_folder.model.class%::OTHER')
...
```
I have added the eMail-widget and got exactly the same error, a wrong SQL statement:
```sql
WHERE 
  o3_.id IN (?) 
  AND o1_.type IN (
    'inbox', 'Oro\\Bundle\\EmailBundle\\Model\\FolderType::OTHER'
  ) 
```

The error occurs in https://github.com/orocrm/platform/blob/518020378c8e078c257316131e94e7fc563b4a9b/src/Oro/Bundle/DataGridBundle/Provider/SystemAwareResolver.php#L88

Tested with platform 1.4.3

**Comment by artml** [comment]
@mario-seidel does it occur on the newer versions of the platform, 1.9.x or 1.10 master?

**Comment by artml** [comment]
closing due to no feedback
