### ISSUE TITLE
Wildcard versions in composer.json

### ISSUE THREAD

**Issue by mgersten-caxy** [orocrm/platform#221]
Are you open to using >X.Y.Z, <X.Y+1 in composer.json rather than exact versions.  I can provide a PR if the answer is yes.  This would make dependency resolution easier when using OroCRM with other things.

**Comment by DimaSoroka** [comment]
This will be a problem. We had issues with 3rd party bundles upgrades in >X.Y.Z, <X.Y+1 range before and this is the reason why we locked to exact version.
