### ISSUE TITLE
BAP - cannot install/update italian translations

### ISSUE THREAD

**Issue by adamjakab** [orocrm/platform#225]
When trying to update italian translations we get:

Could not download translations, error: Error parsing YAML, invalid file "/home/crm.mekit.it/mekitcrm/app/cache/dev/translations/it_IT/OroEmailBundle/translations/messages.it_IT.yml

To me these keys result invalid:
\[Default\]: '[Default]'
%subject% - Email: '%subject% - Email'
%subject% - My Emails - %username%: '%subject% - Mie emails - %username%'

**Comment by hugeval** [comment]
Hi, @adamjakab, thank you for your feedback. According to http://www.yaml.org/refcard.html, '[]' is collection indicators, so you shouldn't use ```[Default]``` as key. As a workaround you can surround this key with quotes, e.g:
```
'[Default]': '[Default]'
%subject% - Email: '%subject% - Email'
%subject% - My Emails - %username%: '%subject% - Mie emails - %username%'
```

**Comment by adamjakab** [comment]
hi @hugeval - the translations come from the Crowdin translation platform! I agree with you that [] should not be used as key - I can only translate/ignore it - someone who manages the keys should check this out!

**Comment by hugeval** [comment]
@adamjakab, thanks for response. I've just downloaded Italian translations for OroEmailBundle, [] are in quotes already.

**Comment by rgrebenchuk** [comment]
Issues with true/false, with leading [ and % were fixed in crowdin and we will rebuild translations as soon as possible

**Comment by mbanin** [comment]
Hello, now install/update translations works correct.

**Comment by adamjakab** [comment]
Hi, there are still some issues! The previouse error is now gone and I get another one "Could not download translations, error: unknown" - when updating italian translations.
I am able to see some of the translations but given that the italian translations are at 99% as far as the platform is concerned I am sure that there are some translations that are not working.

**Comment by mbanin** [comment]
Hello, it seems that it is your local issue. What version of application do you use?
At our latest public version everything is ok.

**Comment by adamjakab** [comment]
I am on a fresh oro/platform 1.6.1 and Italian language pack, when I click download gives the error "Could not download translations, error: unknown" - however when I refresh the page I can see it is installed, I can enable it and it works.
