### ISSUE TITLE
Feature request: second pagination element below datagrids

### ISSUE THREAD

**Issue by cawolf** [orocrm/platform#226]
Hi, we are working with rather large datasets presented in large datagrids. Currently, our workflow is slowed by the fact that you need to scroll/jump up to the toolbar to use the pagination. Would it be possible to extend the datagrids that you can configure to show a second pagination just below the datagrids?

**Comment by alsma-magecore** [comment]
Hello @cawolf !

Yes, you need to render toolbar twice. You can override this (method)[https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DataGridBundle/Resources/public/js/datagrid/grid.js#L795-795] by replacing requireJS module in `map` section of `requirejs.yml`.

**Comment by cawolf** [comment]
Hi @alsma-magecore, thank you for your quick reply. I see, I will try to do as you suggested. Are there any plans to provide an "out-of-the-box" configuration option for this behaviour?

**Comment by cawolf** [comment]
Hi, I just checked the roadmap and the topic "Lock headers on grids" will definitely help us out. Thank you for your support!
