### ISSUE TITLE
Update Symfony

### ISSUE THREAD

**Issue by YKnob** [orocrm/platform#236]
It is possible to update to version 2.6 or 2.7?

**Comment by DimaSoroka** [comment]
We are working only with LTS releases and planning upgrade to 2.7 when it will be released.

**Comment by dewos** [comment]
Hi, any news about Symfony 2.8? It is a LTS version, also. Thanks.

**Comment by DimaSoroka** [comment]
We are going to upgrade to 2.8 later this year.

**Comment by dextervip** [comment]
It is important an upgrade to 2.8! It is a step away to symfony 3! Is there any branch to work on?
