### ISSUE TITLE
Request: Filters in RestAPI

### ISSUE THREAD

**Issue by rodolfobandeira** [orocrm/platform#239]
Hi, it would be very useful the possibility to create filters in API GET methods.

I'm facing a problem when I need to verify if some value already exists in OroCRM I need to read all entries and verify one by one. 

Some useful features:
- Filters (Is_greather_then, Is_equal, Is_less_then, etc)
- Sort (Order_by_Desc, Order_by_Asc)
- Get_Total_Quantity (This would be useful while reading big volume of data)

**Comment by alsma-magecore** [comment]
Hello @rodolfobandeira ! 

That is possible to do now, but it's not very obvious and we have plans to improve APIBundle!

The total number of records could be retrieved by passing special `X-Include` [header](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/SoapBundle/README.md#include-additional-info-into-response)
It's also impossible to configure filters for API GET requests, see `\Oro\Bundle\SoapBundle\Controller\Api\Rest\RestGetController::getFilterCriteria`.

**Comment by rodolfobandeira** [comment]
Hi @alsma-magecore  !

You guys always surprising me.. Thank you for the information. I'll try here.
