### ISSUE TITLE
Refresh schema migration to alter table names

### ISSUE THREAD

**Issue by LRotherfield** [orocrm/platform#245]
I have been trying to write a migration that allows me to rename a table.  I can do this using a postQuery but I run into problems if any migrations that run afterwards reference the new table name because the schema is not updated and does not know that the table name has been changed.  To fix this I have modified the MigrationExecutor locally to refresh the schema if the migration that ran requires it:

```php
public function executeUp(array $migrations, $dryRun = false)
    {
        $platform = $this->queryExecutor->getConnection()->getDatabasePlatform();
        $sm = $this->queryExecutor->getConnection()->getSchemaManager();
        $schema = $this->createPlatformSchema($sm, $platform);
        $failedMigrations = false;
        foreach ($migrations as $item) {
            $migration = $item->getMigration();
            if (!empty($failedMigrations) && !$migration instanceof FailIndependentMigration) {
                $this->logger->notice(sprintf('> %s - skipped', get_class($migration)));
                continue;
            }

            if ($this->executeUpMigration($schema, $platform, $migration, $dryRun)) {
                $item->setSuccessful();
/** Note: Refresh the schema if current migration requires it (table name updated...) */
                if ($migration instanceof RefreshSchemaMigrationInterface) {
                    $schema = $this->createPlatformSchema($sm, $platform);
                }
            } else {
                $item->setFailed();
                $failedMigrations[] = get_class($migration);
            }
        }
        if (!empty($failedMigrations)) {
            throw new \RuntimeException(sprintf('Failed migrations: %s.', implode(', ', $failedMigrations)));
        }
    }

    protected function createPlatformSchema($sm, $platform)
    {
        return $this->createSchemaObject(
            $sm->listTables(),
            $platform->supportsSequences() ? $sm->listSequences() : [],
            $sm->createSchemaConfig()
        );
    }
```

Does it make sense to do this?  Do you have a way to rename tables other than this?

**Comment by vsoroka** [comment]
Hi @LRotherfield,

You can use renameTable method of RenameExtension. (https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/MigrationBundle/Migration/Extension/RenameExtension.php#L52-Lundefined)
How to use extensions in your migration you can read in https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/MigrationBundle/README.md#extensions-for-database-structure-migrations

**Comment by LRotherfield** [comment]
@vsoroka Thanks for getting back to me, I should have at least read the docs first, sorry. 

I have tried using this extension, however it does not change my initial problem:

1. I have a migration (and probably will have many more as the project evolves) that uses the table `df_scope_localization`.  
2. This table used to be called `df_scope_locale` and I renamed it (using the extension you linked to).  
3. When migrations run, if the rename migration runs in the same set of migrations as the migration that uses the new table name, the second migration will fail because the schema is not updated so does not know that the table has been renamed.

```
  > MyBundle\Migrations\Schema\v0_10\DefactoScopeBundle
...
  > MyOtherBundle\Migrations\Schema\v1_2\DefactoContactBundle
    ERROR: There is no table with name 'bap_standard.df_scope_localization' in the schema.
```
Where `MyBundle\Migrations\Schema\v0_10\DefactoScopeBundle` renames the table and `MyOtherBundle\Migrations\Schema\v1_2\DefactoContactBundle` references the new name.

Does that make sense?

Unfortunately I cannot just use the old table name because if the migrations do not run in the same "run" then the second one will fail because the old table name will not exist.

**Comment by artml** [comment]
@LRotherfield have you managed to solve this issue? Sorry for the very late feedback.

**Comment by LRotherfield** [comment]
Hi @artml I have not checked in the most recent versions to see if this has been solved.  I am not sure when I will get around to checking but I can try and get some feedback to you by the end of the week.  I currently still use my above mentioned solution.
