### ISSUE TITLE
Dependencies between platform and crm

### ISSUE THREAD

**Issue by odi-um** [orocrm/platform#247]
* clone and checkout branch 1.6 of  [platform application](https://github.com/orocrm/platform-application).
* run composer install
* run oro:install as described in README.md

Instead of successful installation you will see 
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class OroCRM\Bundle\ContactUsBundle\Entity\AbstractContactRequest does not exist' in vendor/oro/platform/src/Oro/Bundle/EntityExtendBundle/Tools/GeneratorExtensions/ExtendEntityGeneratorExtension.php:58

Seems platform has information about crm classes in https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/MigrationBundle/EventListener/MigrationTableData/OroCRM.yml

**Comment by vsoroka** [comment]
Hello @odi-um,

I did the same steps you described and the platform has been installed without any exceptions.
Could you please provide some additional details on which installation step you got the error?

P.S.: about OroCRM.yml. It is temporary workaround and it will be removed soon. This workaround works only if you install CRM not the platform. See https://github.com/orocrm/platform/blob/1.6/src/Oro/Bundle/MigrationBundle/EventListener/PreUpMigrationListener.php#L55-L63

**Comment by vsoroka** [comment]
I'm not sure, but it seems that you install the platform on the existing CRM database. Could you please check parameters.yml file?

**Comment by odi-um** [comment]
yeah, you were right. DB was from previous install. Thank you.
