### ISSUE TITLE
Platform 1.6 bound to composer 1.0.0-alpha8 breaks with require-dev

### ISSUE THREAD

**Issue by nxpthx** [orocrm/platform#248]
Since the composer.json in the 1.6 branch requires 1.0.0-alpha8 but the downstream requirement include packages which already have the caret operator within it's version constraints the oro platform fatals.

I suggest to also raise the dependency to composer 1.0.0-alpha9 like on master branch (if that's enough) or even remove a fixed constraint.

**Comment by ramunasd** [comment]
There is workaround for this issue. You can change caret operator in composer.lock to tilde operator. Clean your vendor folder completely and reinstall with composer.

**Comment by akuzmenko-magecore** [comment]
Hi @nxpthx,
This issue has been fixed. Thank you for drawing our attention to it.
