### ISSUE TITLE
placeholders.yml extension 

### ISSUE THREAD

**Issue by danielsan80** [orocrm/platform#252]
I created my own placeholders.yml with:
```
items:
    logo:
        template: AcmeUIBundle:Default:logo.html.twig
```

Oro\Bundle\UIBundle\DependencyInjection\OroUIExtension use array_merge_recursive to do the merge

so if I do a dump of $items after the merge I obtain:

```
array (size=21)
  'logo' => 
    array (size=1)
      'template' => 
        array (size=2)
          0 => string 'OroUIBundle:Default:logo.html.twig' (length=34)
          1 => string 'AcmeUIBundle:Default:logo.html.twig' (length=38)
```

instead of the expected:

```
array (size=21)
  'logo' => 
    array (size=1)
      'template' => string 'AcmeUIBundle:Default:logo.html.twig' (length=34)
```

Is this correct?

I get the error:
ContextErrorException: Notice: Array to string conversion in ... /vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/Loader/FilesystemLoader.php line 69

**Comment by yurio** [comment]
Hi, @danielsan80.
Yes. We use array_merge_recursive. If you want to change logo template, you can rewrite OroUIBundle:Default:logo.html.twig template in application level (app/Resources/OroUIBundle/views/Default/logo.html.twig file)
