### ISSUE TITLE
1.6.2 can't install any packages

### ISSUE THREAD

**Issue by mzupan** [orocrm/platform#254]
I followed the platform install doc and getting the following errors trying to install packages

```
[root@ip-10-22-80-64 crm-application]# php app/console oro:package:install --env=dev "oro/crm-zendesk"
Do you want to load demo data? (yes/no, default - no) yes
oro/crm-zendesk requires:
 - oro/platform [installed]
 - oro/crm [installed]
All missing packages will be installed. Continue? (yes/no) yes
Could not load package zendframework/zendframework in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^1.0: Invalid version string "^1.0"
```

Same error happens on a web install too.

**Comment by gido** [comment]
The `^` npm-style semver operator is added in composer version [`1.0.0-alpha10`](https://github.com/composer/composer/blob/master/CHANGELOG.md#100-alpha10-2015-04-14) and oro/platform require composer only version `1.0.0-alpha9`.

It would be nice to change this dependencies by something less stricts (like `~1.0.0-alpha9`)

**Comment by orocrmdeployer** [comment]
Extension can be installed without package manager. 
http://www.orocrm.com/documentation/index/current/cookbook/how-to-install-extension-from-command-line#using-composer

Next tag 1.0.0-alpha10 requires symfony 2.5

**Comment by gido** [comment]
@orocrmdeployer OK, thanks. I prefer this way. A bit less obscure ;)

**Comment by mzupan** [comment]
@orocrmdeployer when I use require I get the following

```
[2015-04-24 14:20:32] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'SELECT DISTINCT o0_.name AS name0 FROM orocrm_channel o1_ INNER JOIN orocrm_channel_entity_name o0_ ON o1_.id = o0_.channel_id WHERE o1_.status = ?' with params [1]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crm.orocrm_channel' doesn't exist" at /var/www/crm/current/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException: An exception occurred while executing 'SELECT DISTINCT o0_.name AS name0 FROM orocrm_channel o1_ INNER JOIN orocrm_channel_entity_name o0_ ON o1_.id = o0_.channel_id WHERE o1_.status = ?' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'crm.orocrm_channel' doesn't exist at /var/www/crm/current/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:91, PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crm.orocrm_channel' doesn't exist at /var/www/crm/current/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:694)"} []
```

**Comment by sergeyz** [comment]
Hi, @mzupan!

Please check that your database is up to date using `app/console doctrine:schema:update --dump-sql --env=your_env_here`. If there are any sql queries please run update using `oro:platform:update` command

**Comment by artml** [comment]
This is an issue about version that is no longer supported so I'm closing it.
