### ISSUE TITLE
akeneo/batch-bundle 0.4.1 error

### ISSUE THREAD

**Issue by sbani** [orocrm/platform#257]
Running composer update today_
> Removing akeneo/batch-bundle (0.4.0)
> Installing akeneo/batch-bundle (0.4.1)
> Downloading: 100%  

  Running `$ php app/console cache:clear`

> PHP Fatal error:  Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException' with message 'The service "akeneo_batch.job_repository" has a dependency on a non-existent parameter "akeneo_batch.entity.job_execution.class". Did you mean this: "akeneo_batch.manager.job_execution.class"?' in /var/www/vhosts/orocrm/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:108

I updated my *composer.json* with: 
```json
    "require": {
        "oro/platform": "1.6.*",
        "guzzlehttp/guzzle": "~5.0",
        "akeneo/batch-bundle": "0.4.0" 
    },
```
But this is only a quick fix.

**Comment by sergeyz** [comment]
Hi, @sbani! Thanks for report. Fix was merged to master branch and now we are waiting for new bugfix release for Akeneo team

You can check it here https://github.com/akeneo/BatchBundle/pull/66

**Comment by sbani** [comment]
Hi @sergeyz, thank you for fast reply and the fast fix.

**Comment by sbani** [comment]
Has been fixed. Thank you @sergeyz
