### ISSUE TITLE
Required option not working for OroRichTextType

### ISSUE THREAD

**Issue by northdakota** [orocrm/platform#260]
Validation option "required" not working with form type: OroRichTextType

**Comment by hugeval** [comment]
Hi @northdakota, form type ```oro_rich_text``` works as expected. But there is case when besides form type definition (https://github.com/orocrm/crm/blob/master/src/OroCRM/Bundle/CallBundle/Form/Type/CallType.php for example) validation rules present also (https://github.com/orocrm/crm/blob/master/src/OroCRM/Bundle/CallBundle/Resources/config/validation.yml). Those rules have higher priority. For example, if you want to make ```Call.notes``` property required, you should add ```notes: - NotBlank: ~``` to https://github.com/orocrm/crm/blob/master/src/OroCRM/Bundle/CallBundle/Resources/config/validation.yml
