### ISSUE TITLE
oro:cron:tracking:parse - Passing the endpoint and running forever

### ISSUE THREAD

**Issue by rodolfobandeira** [orocrm/platform#262]
Hi!

The parsing command is running forever here. I'll try to stop oro-tracking to verify if it's going to finish. Do you guys have any other clue meanwhile we don't have a patch? 

obs: I changed my batch size from 100 to 10.000 in order do speed up the parsing process.

`php app/console oro:cron:tracking:parse -e prod --process-isolation`

Result after **20 days** and some restarts:

`Batch #190 of 168 processed at 2015-05-27 06:38:29.`

Thank you.

**Comment by rodolfobandeira** [comment]
I tested here and I had to stop oro-tracking in order to finish parsing data.

**Comment by yurio** [comment]
Hi. Thanks for highlighting this issue. Fix will be provided at master and 1.7 branches ASAP.

**Comment by rodolfobandeira** [comment]
Thank you @yurio
