### ISSUE TITLE
EmailBundle typo?

### ISSUE THREAD

**Issue by adamjakab** [orocrm/platform#267]
https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/EmailBundle/Resources/config/services.yml#L360

**Comment by adamjakab** [comment]
This has been fixed ages ago: https://github.com/orocrm/platform/blob/093cbf02dc9075fa5a7f19ec7f0e4c5055cc1c29/src/Oro/Bundle/EmailBundle/Resources/config/services.yml#L361
there was a trailing '='

**Comment by sergeyz** [comment]
Hi, @adamjakab, its not a typo, see http://symfony.com/doc/2.3/cookbook/service_container/scopes.html#using-a-synchronized-service

Old Symfony 2.3 staff and was removed during migration to 2.7
