### ISSUE TITLE
Timezone issue in JS date formatter

### ISSUE THREAD

**Issue by LRotherfield** [orocrm/platform#268]
Hi Guys,

There seems to be a little bug in the JS datetime formatter.  I was trying to debug why dates were showing differently between one of my datagrids and the related view pages.  I have my timezone set to `Europe/London` and I am displaying a date of `2015-11-17 10:30 UTC`.  This date on the view page correctly renders as `2015-11-17 10:30` in the `Europe/London` timezone as on November 17th London will be back to UTC (no daylight savings).  However the grid (And the date time picker widget for forms) is rendering the date as `2015-11-17 11:30`.  I assume it is taking the current modifier for `Europe/London` rather than the modifier for the date set.

I hope that makes sense

**Comment by Grygir** [comment]
Hi @LRotherfield,

This issue is already fixed and upcoming release won't contain this bug. 

Thank you.

**Comment by LRotherfield** [comment]
@Grygir amazing thanks, do you  know when the release is due?

**Comment by DimaSoroka** [comment]
Fix will be available in master shortly and release is planned for August.
