### ISSUE TITLE
Components in widget does not initialize

### ISSUE THREAD

**Issue by ramunasd** [orocrm/platform#281]
When component is loaded in widget via `oro_widget_render`, then this component does nothing.
`UIBundle\Resources\public\js\layout.js` just loads this component but no initialization is performed.

Version: 1.7.2

**Comment by x86demon** [comment]
Please, check that component is placed in scope of `widget-content` container

**Comment by artml** [comment]
@ramunasd did that solve the issue?

**Comment by ramunasd** [comment]
I'm closing this because so much time passed since i found issue. Thanks anyway ;)
