### ISSUE TITLE
Wrong filename in media cache

### ISSUE THREAD

**Issue by ramunasd** [orocrm/platform#288]
When image filename has space or other escapable character, FileController stores filtered file with escaped characters. On next request cached images are not found and filter again processes file.

Bug is in Oro/Bundle/AttachmentBundle/Controller/FileController:78

Version: 1.7.x

**Comment by iklymenko** [comment]
Hi ramunasd,
we will check this and provide a fix in the closest release. 
Thanks for making our product better!

**Comment by mkudelya** [comment]
Hi @ramunasd 

This issue doesn't reproduce on 1.10.14. I'm closing the issue. Please open it if the issue still reproduce.
