### ISSUE TITLE
Schema update fail on install 

### ISSUE THREAD

**Issue by Shine-neko** [orocrm/platform#294]
I have a beautiful exception
```
[Doctrine\DBAL\DBALException]
  An exception occurred while executing 'CREATE TABLE oro_search_index_text (id INT AUTO_INCREMENT NOT NULL, item_id INT NOT NULL, field VARCHAR(250) NO
  T NULL, value LONGTEXT NOT NULL, INDEX IDX_A0243539126F525E (item_id), INDEX value (value), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_u
  nicode_ci ENGINE = MyISAM':
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'value' used in key specification without a key length
```

PS:  I use oro crm-application v1.7.4. 

Bouyaaaa =:

**Comment by tim-massey** [comment]
I'm getting this also.

**Comment by orocrmdeployer** [comment]
What MySQL version are you using?

**Comment by Shine-neko** [comment]
MariaDB 10.0.20 via Homebrew

**Comment by iklymenko** [comment]
For some reasons, instead of FULLTEXT index was added regular index on the LONG TEXT field which caused an exception because of MySQL limitations.

**Comment by tim-massey** [comment]
Works on pgsql btw. I've just installed it.

**Comment by dutchiexl** [comment]
I am havind the same problem with mysql

**Comment by rgrebenchuk** [comment]
Did you run oro:install or use doctrine:schema:create?

**Comment by artml** [comment]
No more comments from any of the reporters so I am closing this for now. Feel free to reopen if the issue persists. Thank you.
