### ISSUE TITLE
Sending E-Mail-Campaign slows down with more E-Mails to send

### ISSUE THREAD

**Issue by Hillum123** [orocrm/platform#298]
While sending E-Mail-Campaign per CRON or even with self-built Command, the performance of this process drops rapidly. The server-load runs very high and RAM is always full. At the start, the process runs smooth, until about 500 e-mails sent. Then performance falls to about 5~8 Mails/minute.

**Comment by artml** [comment]
@Hillum123 we do not recommend to use OroCRM's own campaigning engine for sending out campaigns bigger than a couple of hundred emails. Please use MailChimp or dotmailer integration for large mailings. Thank you.
