### ISSUE TITLE
Cannot run functional tests: Error with User::$avatar

### ISSUE THREAD

**Issue by sbani** [orocrm/platform#301]
Hi all,

I get a strange error when I run the `TaskControllerACLTest` (which I copied from crm):
> ReflectionException: Property Oro\Bundle\UserBundle\Entity\User::$avatar does not exist

My setup is clean. I followed the installation steps form this guide: http://www.orocrm.com/documentation/index/current/book/functional-tests
```bash
$ app/console oro:install --env test --organization-name Oro --user-name admin --user-email admin@example.com --user-firstname John --user-lastname Doe --user-password admin --sample-data n --application-url http://localhost --force
$ app/console doctrine:fixture:load --no-debug --append --no-interaction --env=test --fixtures ./vendor/oro/platform/src/Oro/Bundle/TestFrameworkBundle/Fixtures
$ app/console oro:test:schema:update --env test
$ phpunit -c app/ 
```

I really don't get what's happening here.

Related to issue #102?

**Comment by sbani** [comment]
I can avoid the user error by running the Functional tests without the other unit tests

```bash
php vendor/bin/phpunit -c app/ --testsuite "Functional Tests"
```

**Comment by rgrebenchuk** [comment]
Hi
What version are you using? Try to remove app/cache/test folder

**Comment by sbani** [comment]
Hi @rgrebenchuk,

thank you for your answer.

If I run it inside my vagrant box and clearing cache, the error occurs again.
I am running this on a clean CI Server Instance and it's happening too.

**Comment by sergeyz** [comment]
The reason is that Unit test autoloads User class and ExtendBundle can't modify User parent and add extend properties to User afterwards
