### ISSUE TITLE
The "Replace" counter of the import doesn't works. (ContextInterface::incrementReplaceCount())

### ISSUE THREAD

**Issue by mikemirten** [orocrm/platform#303]
The "Replace" ("Update" ?) counter doesn't works for an updated entities while the importing process. The data are updated correct.

I'm calling the ```Oro\Bundle\ImportExportBundle\Context\ContextInterface::incrementReplaceCount()``` method in my implementation of the strategy for an updated entities.

The ```incrementAddCount()``` is works fine.

**Comment by sergeyz** [comment]
Hi, @mikemirten !
It depends on context, how many steps or post process jobs do you have?

**Comment by mikemirten** [comment]
Just took a look inside of the only context implementation: ```Oro\Bundle\ImportExportBundle\Context\Cintext```

This is the code of the ```incrementReplaceCount()```:
```php
public function incrementReplaceCount()
{
    $this->setValue('replace_count', (int)$this->getValue('replace_count') + 1);
}
```

It doesn't looks like depends of something. I have the account creation post-process. Though without the process it's works in the same way. Now i trying to make it works as an only process, without a post-processes.

**Comment by sergeyz** [comment]
Each step has its own context, please make sure that you have all step contexts here
https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/ImportExportBundle/Job/JobExecutor.php#L336
