### ISSUE TITLE
No default value is defined to required argument for route "oro_entity_api_rest_entityfield_getfields"

### ISSUE THREAD

**Issue by mrbrazzi** [orocrm/platform#306]
I update througth composer today and after login and before to load the dashboard I get the following exception:
```
Controller "Oro\Bundle\EntityBundle\Controller\Api\Rest\EntityFieldController::getFieldsAction()" requires that you provide a value for the "$entityName" argument (because there is no default value or because there is a non optional argument after this one)
```
I check the route with router:match command and I found that the route require a paramater
```
Route "oro_entity_api_rest_entityfield_getfields" matches

[router] Route "oro_entity_api_rest_entityfield_getfields"
Name         oro_entity_api_rest_entityfield_getfields
Path         /crm/
Path Regex   #^/crm/$#s
Host         ANY
Host Regex   
Scheme       ANY
Method       GET
Class        Symfony\Component\Routing\Route
Defaults     _controller: OroEntityBundle:Api\Rest\EntityField:getFields
Requirements entityName: ((\w+)_)+(\w+)
Options      compiler_class: Symfony\Component\Routing\RouteCompiler
```
I'm missing something?

**Comment by iklymenko** [comment]
Hi @mrbrazzi,
unfortunately we tried a lot of times but were not able to reproduce this issue. Could you please try again with the latest stable and update us if issue is still exist.

**Comment by iklymenko** [comment]
Since we didn't receive any additional information here I'm assuming that issue is not actual anymore.

@mrbrazzi, feel free to reopen this ticket if issue is still present.
