### ISSUE TITLE
Aggressive  "oro:search:reindex" while running through job queue daemon

### ISSUE THREAD

**Issue by rodolfobandeira** [orocrm/platform#313]
Hello!

I noticed a very aggressive oro:search:reindex in the latest version of platform v1.8.0 when I execute the job queue daemon. 
 
It's consuming 100% of the CPU and the nginx it's not being able to send the requests to php5-fpm.
`oro:search:reindex OroCRM\Bundle\MagentoBundle\Entity\Cart 180000 10000 -v`

Any chance to be related with **BAP-8621** @alex-n-2k7 ?

Thank you!

**Comment by artml** [comment]
Fixed this back in 1.8 days.
