### ISSUE TITLE
The command php app/console generate:bundle doesn't exist anymore

### ISSUE THREAD

**Issue by startupz** [orocrm/platform#316]
I would like to create a new bundle from scratch but the command php app/console generate:bundle dosn't existe anymore in the last version (1.8).

**Comment by sergeyz** [comment]
Hi, @startupz!

Please run `composer install` without `--no-dev` option

**Comment by startupz** [comment]
```bash
www-data@vmsrv44:~/public_html/crm-application$ php composer.phar install --prefer-dist
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package rhumsaa/uuid is abandoned, you should avoid using it. Use ramsey/uuid instead.
Generating autoload files
> ComponentInstaller\Installer::postAutoloadDump
Compiling component files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Oro\Bundle\InstallerBundle\Composer\ScriptHandler::setPermissions
> Oro\Bundle\InstallerBundle\Composer\ScriptHandler::installAssets
```

**Comment by startupz** [comment]
I already install with --no-dev option. Does I need to make an update? But I want to keep composer.lock versions.

**Comment by startupz** [comment]
I just make a fresh install. And the command is missing :

```bash
 git clone https://github.com/orocrm/crm-application.git oro
  535  cd oro/
  536  curl -s https://getcomposer.org/installer | php
  537  php composer.phar install --prefer-dist
  538  mysqladmin -f -usynbshop drop synbshop_jvi_oro
  539  mysqladmin -f -usynbshop create synbshop_jvi_oro
  540  php app/console oro:install --timeout=0
  541  vim app/config/parameters.yml
  542  php app/console oro:install --timeout=0
  543  php app/console
  544  php app/console generate:bundle
```

**Comment by robertocastro** [comment]
I got the same problem with fresh install of crm-application v1.8.
I had to require bundle after install : 
# composer require sensio/generator-bundle:^3.0@dev
But then generate:bundle didn't ask me anymore to skip automatic update of routing and kernel like is sayed here : http://www.orocrm.com/documentation/index/current/cookbook/how-to-create-new-bundle.
So I ended by creating bundles manually.

Maybe something wrong with composer.lock ?

**Comment by sergeyz** [comment]
Hi!

`composer require sensio/generator-bundle:~2.5.0` will install required version. 
Fix will be in application repository soon. Thanks!

**Comment by startupz** [comment]
It works!

**Comment by karol-gontarski** [comment]
still missing ...

**Comment by iklymenko** [comment]
Hi @karol-gontarski, 
the dependency is in place https://github.com/orocrm/platform/blob/1.9.1/composer.json#L82, but pay attention that composer.lock file for application is generated for prod environment, so it excludes require-dev section (https://github.com/orocrm/platform-application/blob/master/composer.lock).
