### ISSUE TITLE
'oro:cron:import-tracking' performance

### ISSUE THREAD

**Issue by rodolfobandeira** [orocrm/platform#318]
Hello!

After disabling "Dynamic Tracking processing" in order to get a better performance in my server, the command to parse the .log tracking files is triggering a query that gets stuck for around 5 minutes here. (5 minutes for each .log file). I'd like to report to you since maybe there are other users with the same problem or will get at the same point  when they get more than some millions of rows on tracking tables.

`php app/console oro:cron:import-tracking -d "/var/www/html/orocrm/app/logs/tracking/" -vvv -e prod`

Debugging the mysql I can see this query trying to execute:

```sql
SELECT COUNT(a0_.id) AS sclr_0 FROM akeneo_batch_job_execution a0_ 
LEFT JOIN akeneo_batch_job_instance a1_ 
ON a0_.job_instance_id = a1_.id 
WHERE a0_.status NOT IN (2, 3) 
AND a1_.rawConfiguration = 'a:3:{s:10:\"entityName\";s:45:\"Oro\\Bundle\\TrackingBundle\\Entity\\TrackingData\";s:14:\"processorAlias\";s:27:\"oro_tracking.processor.data\";s:4:\"file\";s:64:\"/var/www/html/orocrm/app/logs/tracking/20150904-18-5-7.log\";}'
```
Why is this query executing in this format if the `a1_.rawConfiguration` has a base64 encoded data? like this: 
```
YToxOntzOjY6ImltcG9ydCI7YTo1OntzOjE0OiJwcm9jZXNzb3JBbGlhcyI7czozMzoib3Jv
Y3JtX21hZ2VudG8uYWRkX29yX3VwZGF0ZV9jYXJ0IjtzOjEwOiJlbnRpdHlOYW1lIjtzOj
M5OiJPcm9DUk1cQnVuZGxlXE1hZ2VudG9CdW5kbGVcRW50aXR5XENhcnQiO3M6N
zoiY2hhbm5lbCI7aToxODtzOjExOiJjaGFubmVsVHlwZSI7czo3OiJtYWdlbnRvIjtzOjU6Im
ZvcmNlIjtiOjA7fX0=
```

This is the `explain extended` for this query:

![screen shot 2015-09-21 at 10 29 55 am](https://cloud.githubusercontent.com/assets/1811118/9994867/3b7b805c-604d-11e5-9bd3-e6730bfeaf31.png)

As you can see, the command is hitting 7 millions of rows for each .log file with that query showed before.
Thank you

**Comment by rodolfobandeira** [comment]
Tried to modify [this line](https://github.com/orocrm/platform/blob/98374acceeef79d93dd96900d2f8b3aa6ec5988e/src/Oro/Bundle/TrackingBundle/Command/ImportLogsCommand.php#L154):

`->setParameter('rawConfiguration', serialize($options))`
to:
`->setParameter('rawConfiguration', base64_encode(serialize($options)))`

But still not working. I'm pretty sure there is something wrong here because according with `git blame` this code should be working since 2014. 

Anyways. Maybe adding an index to field `rawConfiguration` would improve the performance? What do you think? @sergeyz

**Comment by sergeyz** [comment]
Hi, @rodolfobandeira!

> Why is this query executing in this format if the a1_.rawConfiguration has a base64 encoded data?
We store serialized data in database in base64 to avoid this http://www.jackreichert.com/2014/02/02/handling-a-php-unserialize-offset-error/

> I'm pretty sure there is something wrong here because according with git blame this code should be working since 2014
Probably broken by serialized => base64 using doctrine extension

> Anyways. Maybe adding an index to field rawConfiguration would improve the performance? What do you think?
Yes, it should.

Thanks for report, I'm going to fix it ASAP

**Comment by rodolfobandeira** [comment]
Thank you @sergeyz ! 
You're right, looks like the "DC2Type:array" it's not working for some reason while building that query.  I'll try adding the index manually here and let you know. Thanks

**Comment by sergeyz** [comment]
Just sent PR for review.

Added index with length limit (not sure that it will go to master, will see on review), fixed and improved query(removed in clause and fixed base64).

I'm wondering why do you have 7M records in that table, is it one day job results?
We have command to clean up batch job tables using cron, can you check how it works for your case?
https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/BatchBundle/Command/CleanupCommand.php#L40

I can send you patch if you want to check those changes

**Comment by rodolfobandeira** [comment]
Hello @sergeyz 

Thank you so much for your effort on this item. I'm running the command to clear akeneo logs daily:

```
## REMOVING LOG FILES FROM Akeneo
05 00 * * * php /var/www/html/orocrm/app/console oro:cron:batch:cleanup -e prod --ansi -vvv --process-isolation
```

Running this command manually I got this:
```
php /var/www/html/orocrm/app/console oro:cron:batch:cleanup -e prod --ansi -vvv --process-isolation
Batch jobs will be deleted: 128881
Batch job history cleanup complete
```

`select count(*) from akeneo_batch_job_instance;`
`6848298`

`select count(*) from akeneo_batch_job_execution;`
`6788598`


So, I found the `-interval` parameter and decided to pass "2 days". Check the result:
```
php /var/www/html/demac-orocrm/app/console oro:cron:batch:cleanup -e prod --ansi -vvv --process-isolation -i "2 days"
Batch jobs will be deleted: 6712623
```

If I understood well my orocrm is generating 3 millions of logs per week right? Actually that makes sense because my tracking table has 50M of rows right now. 

Conclusion. I'll change my command to instead of using default interval of "2 weeks" and start using "2 days". I think after cleaning up this entries it will improve the performance pretty well. I'll wait the command finish and let you know. Maybe we don't really need that index on rawConfiguration but we really appreciate the fixes on base64 + serialization you did. 

Thank you so much!

**Comment by rodolfobandeira** [comment]
Just a heads up:

```
Batch jobs will be deleted: 6139923
PHP Fatal error:  Out of memory (allocated 5395447808) (tried to allocate 1073741824 bytes) in /var/www/html/orocrm/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/HydrationCompleteHandler.php on line 98
```

**Comment by sergeyz** [comment]
Just reported this issue, should be fixed ASAP.
As a workaround just try to decrease interval day by day

**Comment by rodolfobandeira** [comment]
Thanks @sergeyz !

**Comment by sergeyz** [comment]
Fix already in master and release branches
https://github.com/orocrm/platform/commit/640dd0e3c6cd06868d37faffa15f42326bf5f860

**Comment by rodolfobandeira** [comment]
Hi @sergeyz 
Thank you so much!
