### ISSUE TITLE
Decouple LocaleBundle from dependencies and make it standalone

### ISSUE THREAD

**Issue by ste93cry** [orocrm/platform#319]
The LocaleBundle has some useful classes and features like address formatting or PHP-to-JS date formatting that would be cool to use outside of the OroCRM platform. Would it be possible to make the bundle standalone by removing all the hard dependencies? From the `composer.json` file I see that there are 4 dependencies listed:

- `oro/config`
- `oro/requirejs-bundle`
- `oro/config-bundle`
- `oro/moment-timezone`

**Comment by sergeyz** [comment]
Hi, @ste93cry !
`oro/requirejs-bundle` and `oro/moment-timezone` are separate bundle atm.
Good idea!

**Comment by DimaSoroka** [comment]
We do not have nearest plans to work on LocaleBundle decoupling, but we'll be happy to review and accept your contribution that will help to solve this request. Feel free to create a PR.
