### ISSUE TITLE
[RFC] Localization settings "error" (502) - Disable ChromePHP

### ISSUE THREAD

**Issue by sbani** [orocrm/platform#321]
# 502 Bad Gateway - headers too big
## Problem
When installing the German translation, I get an error when opening `http://crm-dev.dev/config/system/platform/localization` 

Error is:
> 502 headers too big
This is an nginx error and it's ok here because headers are really too big.

And I found out why:
The header `X-ChromeLogger-Data` is very big (245,800 characters, totaling *245,800 bytes*). And that's because of the missing translations:
> Missing messages 1566
> Fallback messages 53
> Defined messages 74

It's, for sure, a bad behavior if the page is crashing this way, so we should think about a solution.

### 1) Disable ChromePHP as default
When disabling ChromePHP, the functionality still exist and can't cause any errors. It can be enabled if wanted or needed.

### 2) Strip error messages
Returning the complete list is a mess and is mostly not needed i think. So we could check the length and cut it.

Hope you guys are getting my point this time :four_leaf_clover:

**Comment by sergeyz** [comment]
Hi, @sbani !

Translations are managed using https://crowdin.com/ by our community, so you can avoid this issue by adding missing messages for German translation.

Another way is to increase headers size in nginx configuration to use ChromePHP extension during development.

**Comment by sbani** [comment]
Hi @sergeyz,

this is a strange way to deal with errors for me. You kinda say:
"If you don't want to translate a language yourself, you can either stop using it or you are not able to use the *dev mode. Because showing errors is more important than preventing them."

But okay, I will disable ChromePHP which solves the problem. It's okay for me.

**Comment by sergeyz** [comment]
This issues is totally related to your development environment. 

At now German translation has `Missing messages 1566` and that is not an error, just current translations state.

ChromePHP sends logs using header. So if you want to get all errors - please configure your environment to receive that logs in a proper way.
Any large log with ChromePHP can cause same error.

So, I think we should not handle it from source code.

**Comment by sbani** [comment]
I get your point. Thanks @sergeyz for your feedback.

**Comment by stepansib** [comment]
But this issue present in production env too (
People using chrome can't reach some pages, they get the same error "headers too big"

**Comment by sergeyz** [comment]
HI, @stepansib !

Is it X-ChromeLogger-Data header?

**Comment by stepansib** [comment]
I cant check this right now because this error is thrown by Microsoft
ForeFront firewall. I will add info a little later

2015-11-26 16:04 GMT+07:00 Sergey Zhuravel <notifications@github.com>:

> HI, @stepansib <https://github.com/stepansib> !
>
> Is it X-ChromeLogger-Data header?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orocrm/platform/issues/321#issuecomment-159852775>.
>



-- 
*С уважением, Степан.*
*8-913-753-39-87*
*stepan.sib@gmail.com <stepan.sib@gmail.com>*
