### ISSUE TITLE
Installer requirements check always fails inside a Docker container

### ISSUE THREAD

**Issue by advancingu** [orocrm/platform#331]
When running `app/console oro:install` inside a Docker container, the requirements check always fails:

    Oro requirements check:
	+---------+---------------------------------------------------------------------------------+
	| Check   | Mandatory requirements                                                          |
	+---------+---------------------------------------------------------------------------------+
	| OK      | Vendor libraries must be installed                                              |
	| OK      | app/cache/ directory must be writable                                           |
	| OK      | app/logs/ directory must be writable                                            |
	| OK      | Configured default timezone "UTC" must be supported by your installation of PHP |
	| OK      | json_encode() must be available                                                 |
	| OK      | session_start() must be available                                               |
	| OK      | ctype_alpha() must be available                                                 |
	| OK      | token_get_all() must be available                                               |
	| OK      | simplexml_import_dom() must be available                                        |
	| OK      | APC version must be at least 3.1.13 when using PHP 5.4                          |
	| OK      | PCRE extension must be available                                                |
	| ERROR   | Move app/cache folder outside encrypted directory.                              |
	+---------+---------------------------------------------------------------------------------+

Looking at the requirement check code it appears that any other filename length than `255` is considered unacceptable: https://github.com/orocrm/crm-application/blob/master/app/OroRequirements.php#L355

This is despite the fact that the bug report which appears to have caused this test only has a filename with less than 200 characters: https://github.com/orocrm/platform/issues/31

In fact, `getconf NAME_MAX` returns `242` on my Docker setup and I've been running Symfony applications inside Docker for more than a year now without any cache issues.

I suggest changing the test to only reject less than 200 characters. Also, the error message is currently highly misleading and should instead state something along the lines of `Maximum supported filename length greater than 200 characters`.

**Comment by iklymenko** [comment]
Hi @advancingu, 
we will set the limit to not less than 242 characters in our closest release for all applications. Thanks for highlighting this issue!

**Comment by advancingu** [comment]
I've put my Docker setup online in case you're interested in the setup: https://github.com/advancingu/OroCRMDocker

**Comment by DimaSoroka** [comment]
Thanks @advancingu !
