### ISSUE TITLE
Update distribution bundle

### ISSUE THREAD

**Issue by sagikazarmark** [orocrm/platform#339]
Is it possible to update the distribution bundle?

That would let as use the new Symfony 3.0 directory structure, which is far more better than the current one.

The attachment directory should also be moved to the `var/` directory.

Fortunately, it is possible to use the new directory structure without updating to symfony 3.0.

**Comment by DimaSoroka** [comment]
Hi @sagikazarmark 

Could you please clarify what you would like to update in distribution bundle? We are going to upgrade to Symfony 2.8 once it will be released and upgrade to 3.x planed for 3.3 LTS release.

**Comment by sagikazarmark** [comment]
The distribution bundle is a separate component of the framework. It is currently locked to 2.3.4.

https://github.com/sensiolabs/SensioDistributionBundle

AFAIK it is backwards compatible with "older" symfony versions.

The reason why I would like to update it can be read above. The fact that Symfony 3 introduces a new directory structure, does not mean it is limited to symfony 3.

**Comment by DimaSoroka** [comment]
Got you, thanks for clarification. Are you looking for v4.0.3? Feel free to prepare PR, we'll be happy to include in into the upcoming release in December.

**Comment by sagikazarmark** [comment]
Yeah, 4.0.3 would be fine. PR is on route.
