### ISSUE TITLE
ContextListener.php

### ISSUE THREAD

**Issue by lmeliberty** [orocrm/platform#349]
Hello,

In the Oro\Bundle\SecurityBundle\Http\Firewall\ContextListener.php file, you made a change to add a try / catch block.
```php
        $token = $this->context->getToken();
        if ($token instanceof OrganizationContextTokenInterface) {
            try {
                $token->setOrganizationContext(
                    $this->manager->getOrganizationById($token->getOrganizationContext()->getId())
                );
            } catch (NoResultException $e) {
                $token->setAuthenticated(false);
            }
        }
```
Can you update the 1.7.* branch with this update please ?

**Comment by DimaSoroka** [comment]
please prepare a PR, we'll be happy to merge it there

**Comment by lmeliberty** [comment]
Thank's for your answer.
I just make a PR: https://github.com/orocrm/platform/pull/350.

**Comment by DimaSoroka** [comment]
thanks, we'll handle it shortly

**Comment by artml** [comment]
PR merged long time ago, closing this.
