### ISSUE TITLE
Missing js dependencies

### ISSUE THREAD

**Issue by ramunasd** [orocrm/platform#355]
After fresh installation `app/console oro:requirejs:build` throws exception:
```
  [RuntimeException]                                                                                          
  Tracing dependencies for: /src/admin/web/js/oro.min.js                                                      
  Error: ENOENT, no such file or directory '/src/admin/web/bundles/components/jsplumb/dom.jsPlumb.js'         
  In module tree:                                                                                             
      oroworkflow/js/extend/jsplumb                                                                           
  Error: Error: ENOENT, no such file or directory '/src/admin/web/bundles/components/jsplumb/dom.jsPlumb.js'  
  In module tree:                                                                                             
      oroworkflow/js/extend/jsplumb                                                                           
      at Object.fs.openSync (fs.js:432:18)
```

Without successful build platform is unable to start - hangs out right after successful login.

To overcome this i must do these commands:
* `mkdir web/bundles/components/jsplumb && cp vendor/oro/jsplumb/dom.jsPlumb.js web/bundles/components/jsplumb/`
* `cd web/bundles/components && ln -s ../../../vendor/oro/moment-timezone`

Version: 1.8.2

**Comment by sergeyz** [comment]
Hi, @ramunasd!

components installed on composer script https://github.com/orocrm/crm-application/blob/master/composer.json#L33

Please add script to you root composer.json if you don't use any *-application repository.
Its know composer limitation when composer executes root composer.json scripts only
https://getcomposer.org/doc/articles/scripts.md

**Comment by ramunasd** [comment]
@sergeyz i have this line, my composer.json is taken from https://github.com/orocrm/platform-application

**Comment by sergeyz** [comment]
please try to run 'composer run-script post-install-cmd'

**Comment by ramunasd** [comment]
@sergeyz nope, this also doesn't helps :)

**Comment by sergeyz** [comment]
@ramunasd is there components config https://github.com/orocrm/crm-application/blob/master/composer.json#L25 in your root composer.json?

In addition, please post `composer show --installed | grep -i oro` result here

**Comment by ramunasd** [comment]
I can't reproduce this issue. Perhaps it was something with composer or packagist cache. Thanks for help ;)
