### ISSUE TITLE
Incorrect behavior (sorting, paging) grid in dashboard widget 

### ISSUE THREAD

**Issue by odi-um** [orocrm/platform#357]
In certain situations grids added to dashboard\ don't work as expected. Sorting and paging does not work, row actions (view, edit, delete) lead to trace pages.

For example steps to reproduce issue with sorting:
- Login and open dashboard in demo http://demo.orocrm.com
- Add "recent email" widget to dashboard
- Stay on inbox tab, do not change it
- Try to sort email by date several times (ASC, DESC, ASC, etc)

You will see that order does not change at all. Issues disappears after you change tab to sent and then back to inbox.

Probable cause of this issue, when browser sends requests at the first time, query params look like this 
```
dashboard-recent-emails-inbox-grid[userId]:1
dashboard-recent-emails-inbox-grid_w51[_pager][_page]:1
dashboard-recent-emails-inbox-grid_w51[_pager][_per_page]:10
dashboard-recent-emails-inbox-grid_w51[_parameters][view]:__all__
dashboard-recent-emails-inbox-grid_w51[_sort_by][receivedAt]:ASC
```

After grid was rebuilt by JS (browsing through tabs), query params look like this 
```
dashboard-recent-emails-inbox-grid[userId]:1
dashboard-recent-emails-inbox-grid[_pager][_page]:1
dashboard-recent-emails-inbox-grid[_pager][_per_page]:10
dashboard-recent-emails-inbox-grid[_parameters][view]:__all__
dashboard-recent-emails-inbox-grid[_sort_by][receivedAt]:ASC
```
I understand why we need this suffix thing "_w51" but seems it incorrectly managed on the backend. When we use row UI elements like row click or row actions, they produce link with incorrect query grid parameter and system tries to load such grid. For this we already open [pull](https://github.com/orocrm/platform/pull/344) requests but seems problem have a deeper roots then we thought.

**Comment by artml** [comment]
We have merged your pull request. Thank you for the contribution!
