### ISSUE TITLE
Modal preview of template has incorrect height

### ISSUE THREAD

**Issue by codesman** [orocrm/platform#358]
When previewing edits to a template, the `div.modal-body` is not allowed to expand to the height of the modal because `height:auto;` is being inlined by:

https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/UIBundle/Resources/public/js/modal.js#L188

Which results in something that looks like this:

![screen shot 2015-12-04 at 1 10 06 pm](https://cloud.githubusercontent.com/assets/1653589/11604494/2a4823a0-9aa2-11e5-944c-8d0dbbfd1561.png)

Removing the `height:auto;` rule from the div allows it to fill the modal.

I can confirm this behavior in Chrome 47.0.2526.73 and Safari 8.0.6 (10600.6.3) OS X.

**Comment by Grygir** [comment]
Thank you for reporting the issue. It will be fixed in upcoming version of OroCRM.

**Comment by codesman** [comment]
Hello @

**Comment by codesman** [comment]
Hello @Grygir,

I've noticed in 1.9-RC1 that this has changed, but not in a good way.  Now, the email preview modal is fixed at 400px high.  This makes it very difficult to preview emails that are longer than a line or two.  Seems like it would be much better to have this preview modal use as much height as possible versus clamping to such a small size, or at least allow it to be resized.

**Comment by Grygir** [comment]
Hello @codesman,

Thanks for you comment, we'll take a look how to fit this issue.

**Comment by amuzalevskiy** [comment]
Hi @codesman,

We've updated email preview dialog and it is resizable now. That fix will be included in platform v1.9.

Thank you
