### ISSUE TITLE
Report Total per page and Total after filter

### ISSUE THREAD

**Issue by golriz** [orocrm/platform#363]
- total per page of report return value of grand_total 
- if apply some filter on report , value of total and grand_total return total of all records instead of total of filtered row

**Comment by ahmadgolzar** [comment]
We have the same problem and I noticed that orocrm demo website has this problem too.
http://demo.orocrm.com/desktop/report/static/accounts/life_time_value

The problems are:
1. Page total shows the same sum as grand total
2. When you filter the report the totals does not change

**Comment by DimaSoroka** [comment]
Thanks for info, we'll check this issue and will work on fix.

**Comment by artml** [comment]
Fixed within 1.9 release. Thanks for raising the issue @golriz @ahmadgolzar
