### ISSUE TITLE
Will Security bundle ever going to be a stand-alone

### ISSUE THREAD

**Issue by Mrkisha** [orocrm/platform#368]
Will you ever make Security bundle available in packagist and is it stand-alone?

**Comment by DimaSoroka** [comment]
We do not have this in our plans for nearest future, if you would like to decouple it and contribute changes - we will be happy to maintain it moving forward.

**Comment by Mrkisha** [comment]
I would consider it. But the Security Bundle is not available on github to be cloned. I would consider using the bundle in my next project that needs to start very soon.

**Comment by DimaSoroka** [comment]
Thanks, please let us know if we can help somehow. Closing this ticket and looking forward for your contribution.
