### ISSUE TITLE
create_datetime action time parameter handling

### ISSUE THREAD

**Issue by codesman** [orocrm/platform#372]
The current documentation for the create_datetime action says that the `time` parameter may be configured like this: `time: 2014-04-01 12:12:00`

However, when you use this value the action fails because this value is parsed as an integer and the parameter requires a string.

Using this syntax, `time: '2014-04-01 12:12:00'` the action is completed successfully.

I submitted a PR that adds a note about needing to quote this value, but I'm not sure if that is correct.

Does the value need to be quoted in the process.yml file or does the config parser need to be changed to not interpret that as integer?

**Comment by yshyshkin** [comment]
Hello, @codesman 

You are completely right - `time: 2014-04-01 12:12:00` is invalid value because it parsed incorrectly by YAML parser (we use default YAML as config format).

> Does the value need to be quoted in the process.yml file or does the config parser need to be changed to not interpret that as integer?

It should be quoted in the configuration file (process.yml in your case).

**Comment by yshyshkin** [comment]
PR https://github.com/orocrm/platform/pull/374 was merged.
