### ISSUE TITLE
PHP 5.6 + \SoapClient() = Could not connect to host

### ISSUE THREAD

**Issue by rodolfobandeira** [orocrm/platform#378]
Hi there, 

I had to add `$options['location'] = 'http://example.org/wsdl';` in order to make Magento Integration working properly on PHP 5.6. I'm not sure why SoapClient() requires this on PHP 5.6. If we don't use it, it's going to return "Could not connect to host". I could create a pull request for this but sometimes Oro uses cached WSDL, so maybe using this "location" could bypass the cache. (I didn't have time to verify) 

It's just a heads up since more Oro users could face the same issue.

Here is where I injected the "location" parameter:
https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/IntegrationBundle/Provider/SOAPTransport.php#L152

**Comment by artml** [comment]
Thanks Rodolfo, this is a valuable advice.

**Comment by rodolfobandeira** [comment]
I found the problem. The host I was trying to connect is redirecting to another domain name. For some reason, PHP 5.6 doesn't carry the location automatically. So, since it's a very specific case, I'm going to close this issue and if anyone else got the same problem they will know the proper solution reading above.
