### ISSUE TITLE
System Calendar ignores ACL

### ISSUE THREAD

**Issue by reiser** [orocrm/platform#384]
Hi,

its not possible to hide the System Calendar.
I added a new Role without any permissions and the Tab is still visible.
![bug](https://cloud.githubusercontent.com/assets/449441/12379407/69f60c94-bd5a-11e5-83d1-de3ba58a2a94.jpg)
![bug2](https://cloud.githubusercontent.com/assets/449441/12379433/e037f91c-bd5a-11e5-9dec-9df3ba74d233.jpg)

Regards Thorsten

**Comment by artml** [comment]
Hi Thorsten,

To hide them from the menu you have to disable two capabilities (in a section below Entity):
* Manage system calendars
* Manage system calendar events
