### ISSUE TITLE
[Config] Sync standalone repository with changes introduced in platform

### ISSUE THREAD

**Issue by ste93cry** [orocrm/platform#385]
Config component is a great component that was extracted from the platform and published on its own repository. However, it seems to be outdated. Changes pushed to this repository are not synced with the other one. Could you please sync the two repositories?

**Comment by DimaSoroka** [comment]
Sure, repo updated with latest changes

**Comment by ste93cry** [comment]
repository is again behind the main one. Things changed a lot, new dependencies has been introduced but the component is so useful that I think it's worth to maintain the standalone repository updated. Could you check if something can be done about this?

**Comment by sergeyz** [comment]
Hi, changes should not affect standalone distribution afaik, automated sync almost configured.

**Comment by ste93cry** [comment]
As far as I see there are now dependencies on some packages that are not published standalone from the whole platform (e.g. the Oro PropertyAccess component), so the compo

**Comment by sergeyz** [comment]
Ah, sorry, I checked RequireJSBundle

**Comment by ste93cry** [comment]
By the way RequireJSBundle has the same problem, it depends on PhpUtils component which is not public too
