### ISSUE TITLE
Web Accessibility / WCAG considerations?

### ISSUE THREAD

**Issue by StephenOTT** [orocrm/platform#387]
When the UI is being designed, is there any accessibility / WCAG 2.0 testing / optimization?

**Comment by DimaSoroka** [comment]
hello @StephenOTT 

We were covering some parts of WCAG 2.0 recommendations, but we didn't do any testing and optimization in this regard.

**Comment by StephenOTT** [comment]
Thanks

**Comment by StephenOTT** [comment]
@DimaSoroka a great little tool for quick checks is: http://wave.webaim.org/extension/

**Comment by DimaSoroka** [comment]
Thanks!
