### ISSUE TITLE
Single Integration per OroCRM instance?

### ISSUE THREAD

**Issue by StephenOTT** [orocrm/platform#388]
On the following page of the docs:
http://www.orocrm.com/documentation/index/current/user-guide/integrations-overview

It says:
Integrations applied to the whole system. **_There can only be one integration with a third-party system for an OroCRM instance_**. These integrations can be enabled/disabled and defined in the “System → Configuration → Integration”. These are

Can get some further explanation for: `There can only be one integration with a third-party system for an OroCRM instance` ?  Why can only one integration be used?  

Does this mean that if someone build a Yahoo or OpenID integration, they could not use the google integration at the same time?

**Comment by mbessolov** [comment]
Hi Stephen,

Thank you for pointing it out. What we meant to say is that there could not be two instances of the same connector in case of a system-wide integration. For example, you cannot have two Microsoft Exchange connectors enabled simultaneously, or two single sign-on integrations with our Google connector.

This limitation does not apply when connectors are different (which could be different third-party systems, or even just different implementations of an integration to the same system). If there were a Yahoo or an OpenID integration available, you could enable them and Google single sign-on together. It should also be possible to enable both the pre-built Google single sign-in integration and a 3-rd party Google single sign-on connector implementation together, as long as the 3-rd party developer does not intentionally prevent it from happening.

We would appreciate any suggestions on how to rewrite this section for better clarity.

Thank you,
Michael

**Comment by StephenOTT** [comment]
@mbessolov updated docs with what I think helps to clarify based on your explanation above.
