### ISSUE TITLE
Fix bug in 1.8 too please (#369)

### ISSUE THREAD

**Issue by sbani** [orocrm/platform#390]
Can you please fix the bug #369 in 1.8 too? Perhaps before 1.9 release?
My CI system is not working properly because of this bug. I can't test anything and cannot deliver continuously.

If you want, I can create an extra PR for 1.8.

**Comment by DimaSoroka** [comment]
Please submit a PR for 1.8, we'll merge it. 1.9 is coming in one-two weeks.

**Comment by sbani** [comment]
Ok. Created the PR.
The update to 1.9 will take "some time" (for me to adapt). Would be nice to have a working copy of 1.8 without the bug.

Thank you for your efforts
