### ISSUE TITLE
Content Translation?

### ISSUE THREAD

**Issue by StephenOTT** [orocrm/platform#393]
Has there been any thought into handling content translation?

Example you may have the Interface in English, but you are adding content for different languages like a email template in different languages, or a product that is translated into different languages.

Not seeing any docs referring to this.

**Comment by mbessolov** [comment]
How the content can be translated highly depends on the use case.

For example, in OroCommerce localized content can have two dimensions (website and locale), not one (locale). As a result, there could be multiple (and different) translations for the same piece of content and for the same language (e.g. translation to German for the main website and for the secondary website, which may be two different translations either because they need to be different, or because two different departments are managing the content, etc.)

**Comment by StephenOTT** [comment]
Has a UI been developed to manage the different translations?

Any picture or screenshot you can share?

**Comment by StephenOTT** [comment]
@mbessolov the use case I am looking at the moment is something such as a Product Description

There would be the original/source product description (usually the primary language of the system) and then there would be translations of that product.

So for example:
you would have Product ABC and a English Description for that product
Then you would have Product ABC translated into Spanish, where the Description is in Spanish.

Another example would be with Tags.  When you add a Tag you may want to translate the tag for other languages.

Anyone work on a general translation UI and pattern?

**Comment by mbessolov** [comment]
Some examples of content translation management UIs:

- OroCommerce (rough, it's still alpha, we are going to rework this UI significantly after beta) - both Products and Categories of the Master Catalog have some localizable fields by default. For example on the [Category edit page](http://demo.orocommerce.com/admin/catalog/category/update/4) , fields Title, Short Description and Long Description have a folder like icon to the right. If you click on this icon, it will show additional fields for each of the configured locales.

- [Akeneo PIM](http://akeneo.com) - they also have more than one dimension (two - channel and locale). For example check the Product edit page  - http://demo.akeneo.com/#url=/enrich/product/1101?dataLocale=en_US  (login: admin ,  password: admin , go to Enrich -> Products -> click on any product -> click on "Compare/Translate" button on the product edit page)

**Comment by StephenOTT** [comment]
> OroCommerce (rough, it's still alpha, we are going to rework this UI significantly after beta) - both Products and Categories of the Master Catalog have some localizable fields by default. For example on the Category edit page , fields Title, Short Description and Long Description have a folder like icon to the right. If you click on this icon, it will show additional fields for each of the configured locales.

AHHH!!! I was looking for a icon such as: http://fortawesome.github.io/Font-Awesome/icon/language/

The folder through me off! :)

**Comment by mbessolov** [comment]
You see now why it needs to be reworked.
Thank you for the suggested icon, we'll use it for now. Hopefully it will be less confusing than a folder icon (and more "accurate" than a globe icon, which we've decided not to use).

**Comment by StephenOTT** [comment]
:+1:
