### ISSUE TITLE
oro:cron:tracking:parse = proc_open(): fork failed - Cannot allocate memory

### ISSUE THREAD

**Issue by rodolfobandeira** [orocrm/platform#397]
`php /var/www/html/orocrm/app/console oro:cron:tracking:parse --max-execution-time=720 -e prod --no-ansi`

...

```
Batch #418 of 438 processed at 2016-02-10 16:07:30.
Batch #419 of 438 processed at 2016-02-10 16:08:59.
Batch #420 of 438 processed at 2016-02-10 16:10:28.
PHP Warning:  proc_open(): fork failed - Cannot allocate memory in /var/www/html/orocrm/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php on line 978
```

...

![htop](http://s12.postimg.org/ukjkcvyn1/Screen_Shot_2016_02_10_at_4_15_07_PM.png)

**Comment by rodolfobandeira** [comment]
Another problem related. When I thought it was finishing it showed this sweet message:

```
...
Batch #79 of 80 processed at 2016-02-12 10:13:55.
Batch #80 of 80 processed at 2016-02-12 10:14:16.
Recheck previous visit events...
Total previous visit events to be processed - 162,200,454 (162,201 batches).
Batch #1 of 162,201 processed at 2016-02-12 10:17:28.
Batch #2 of 162,201 processed at 2016-02-12 10:17:32.
...
```

It took at least 30 days to parse everything and when finally it's finishing I found that there is a loop that for some reason never ends.
Thank you

**Comment by yurio** [comment]
Hi, @rodolfobandeira.
Thanks for highlighting this issues.

We will check memory leaks in parser.

For the Recheck previous visit event.
We should give additional chance for the old data to identify it. That is why we do this work. You can set max-execution-time not so big to be sure that this process does not takes you process time. In this case parser will check new data and will try to process old data for the remaining time. It's not necessary to wait while old data will be rechecked. But this recheck will give you more info about your visitors.

**Comment by rodolfobandeira** [comment]
Thank you for the feedback @yurio
