### ISSUE TITLE
The problem with moving events on the Route (.../calendar/default)

### ISSUE THREAD

**Issue by kostant85** [orocrm/platform#402]
Once assigned to a contact event (step 1,2) - open on the page at .../calendar/default (step 3). Contact ( context) that is bound to the event - exists (step 4). But if you move the event to another day , the context is removed (step 5). Also recording removed from the table oro_rel_46a29d1983dfdfa4e84e2b`. The update to 1.9 has not helped.
![1](https://cloud.githubusercontent.com/assets/15968007/13179492/ca93b8e4-d72c-11e5-9114-5e3dadecd1a1.png)
![2](https://cloud.githubusercontent.com/assets/15968007/13179490/ca9395bc-d72c-11e5-9664-72a688204973.png)
![3](https://cloud.githubusercontent.com/assets/15968007/13179491/ca93c050-d72c-11e5-8eca-8020863e236b.png)
![4](https://cloud.githubusercontent.com/assets/15968007/13179493/ca940d3a-d72c-11e5-8459-1ea73e4a311c.png)

**Comment by iklymenko** [comment]
Hi @kostant85, 
thanks for the hands up on this issue. We added it to our backlog.

**Comment by artml** [comment]
Fixed in 1.9 release
