### ISSUE TITLE
Cannot use 'True' as class name as it is reserved (PHP7 support)

### ISSUE THREAD

**Issue by jameswithers** [orocrm/platform#408]
When installing OroCRM 1.9.0 I get `Fatal error: Cannot use 'True' as class name as it is reserved in orocrm\vendor\oro\platform\src\Oro\Component\ConfigExpression\Condition\True.php`

A forum post refers to PHP7 end of 2015: http://www.orocrm.com/forums/topic/php-7-0-compatibility.

**Comment by DimaSoroka** [comment]
We do not support PHP7 yet, this will be done in the next release

**Comment by jameswithers** [comment]
Do you have a roadmap/release date for this?

**Comment by woei66** [comment]
there is a word-around fix about this
http://www.orocrm.com/forums/topic/php-7-0-compatibility#post-13517
personally, I think you should fix this asap since php7 is already released officially and you should follow up the naming rule of php7

**Comment by DimaSoroka** [comment]
We are targeting to include PHP7 support in our April release

**Comment by sadortun** [comment]
#347

**Comment by dextervip** [comment]
Shouldn't PHP 7 support be released now? Any updates?

**Comment by artml** [comment]
@dextervip It is still in development, current estimate is that it will be committed to master in a few weeks.

**Comment by iklymenko** [comment]
Hello guys,
PHP7 support is complete for our latest master.

**Comment by alsma** [comment]
@iklymenko Could you please also update composer.lock in https://github.com/orocrm/crm-application because now it's pointed to platform in this state https://github.com/orocrm/platform/commit/b37231b0a5a775058e36172d12c4a9f7295206bb

**Comment by alsma** [comment]
and the same here https://github.com/orocrm/platform-application/blob/master/composer.lock#L4014
