### ISSUE TITLE
Imap sync duplicates activities and cases

### ISSUE THREAD

**Issue by alsma** [orocrm/platform#411]
Hi guys!

I've found weird behaviour of system mailboxes on one of our CRM installations. Email box is located in Zoho's cloud

We have following configuration:
**Environment**: 1.9 RC1
**System mailboxes**: 1 with enabled IMAP sync only
**Email folders**: Single folder *Inbox* enabled
**Email processing action**: Convert to case
**Access management**: Access granted for 2 users and one role 

There are a lot of email/case duplication. It alsoы generate case entity for reply on email that case is already created for.
<img width="1868" alt="screen shot 2016-03-09 at 11 37 00" src="https://cloud.githubusercontent.com/assets/3245855/13631063/548690f4-e5eb-11e5-873d-2cc478e680b9.png">
It also duplicate activities
<img width="1878" alt="screen shot 2016-03-09 at 11 38 52" src="https://cloud.githubusercontent.com/assets/3245855/13631164/cfa98f3e-e5eb-11e5-91c0-7001c1d4bf03.png">

But on emails grid (for user that has access to system mailbox) there is no duplicates
<img width="1870" alt="screen shot 2016-03-09 at 11 43 29" src="https://cloud.githubusercontent.com/assets/3245855/13631224/2c1d4ee0-e5ec-11e5-811e-40ddbf1ba4a8.png">

**Comment by alsma** [comment]
The issue was already resolved in 1.9 release. @iklymenko thank you for pointing this out.

**Comment by iklymenko** [comment]
@alsma, no problem! Thanks for heads up!
