### ISSUE TITLE
the "php app/console generate:bundle" is not existed (Command "generate:bundle" is not defined)

### ISSUE THREAD

**Issue by woei66** [orocrm/platform#416]
here is the step that I installed oro-crm
git clone -b 1.9.0 https://github.com/orocrm/crm-application.git
composer install --prefer-dist
when I try to use the "php app/console generate:bundle" 
I got a error message that Command "generate:bundle" is not defined
![2016-03-16 18_37_37](https://cloud.githubusercontent.com/assets/5770807/13809558/415a6c6a-eba6-11e5-9327-6713667822bd.jpg)

then, I try to install the tool by below command
composer require sensio/generator-bundle
or 
composer require sensio/generator-bundle:~2.5.0
and both got the memory message like below
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted

![2016-03-16 18_39_19](https://cloud.githubusercontent.com/assets/5770807/13809599/726c926a-eba6-11e5-864d-9578bc99ad88.jpg)

I have changed php.ini to 1G memory size but it still failed
any suggestion?
thank you.

Ps. I saw a related issue is 
https://github.com/orocrm/platform/issues/316

**Comment by iklymenko** [comment]
Hi @woei66,
please check the answer here https://github.com/orocrm/platform/issues/316#issuecomment-197343862 
Regarding the memory issue, it's a known composer issue, try to remove composer.lock and run "composer install --prefer-dist" OR run "composer update --prefer-dist".

If it will not help try to temporary remove memory limit at all: php -dmemory_limit=-1 composer.phar ...

**Comment by woei66** [comment]
thanks and your suggestions workable
