### ISSUE TITLE
Entity Permissions Table Header, on Role Edit page, Needs to stick to top when scrolling

### ISSUE THREAD

**Issue by StephenOTT** [orocrm/platform#418]
When scrolling long lists of entities, and you are modifying a specific permission for  role, the header of the permissions table does not stick to top when scrolling:
![screen shot 2016-03-18 at 1 02 28 pm](https://cloud.githubusercontent.com/assets/1994838/13885604/acdb5684-ed09-11e5-92b7-7f187c302643.png)

So very quickly you end up in confusion about which column is which.
![screen shot 2016-03-18 at 1 02 59 pm](https://cloud.githubusercontent.com/assets/1994838/13885662/d423fda4-ed09-11e5-9b39-85aff7a4c890.png)

**Comment by artml** [comment]
Hi Stephen,

Thanks for your suggestion! We will be redesigning the role permission management in the upcoming release so this issue will be addressed.
