### ISSUE TITLE
Responsive layout - overlapping States from Workflow

### ISSUE THREAD

**Issue by StephenOTT** [orocrm/platform#420]
![screen shot 2016-03-22 at 12 29 33 pm](https://cloud.githubusercontent.com/assets/1994838/13959281/ef96b6d0-f029-11e5-8345-b0e985f39666.png)

See the states indicator at the top of the picture.  When your screen is not very large (13inch laptops) / when you are not maximized, it very quickly starts to overlap rather than wraps or goes to a new line.

**Comment by dmitrosh** [comment]
Thank you for pointing out this issue. We'll see what we can do there

**Comment by amuzalevskiy** [comment]
Hi @StephenOTT ,

Related issue BAP-9965 is fixed in master branch and will be available in the next release.

Thank you,

Andrii
