### ISSUE TITLE
Missing command oro:test:schema:update

### ISSUE THREAD

**Issue by sbani** [orocrm/platform#421]
Following the [docs](https://www.orocrm.com/documentation/index/current/book/functional-tests), I need to run `app/console oro:test:schema:update --env test` for the functional tests.

```bash
app/console oro:install --env test --organization-name Oro --user-name admin --user-email admin@example.com --user-firstname John --user-lastname Doe --user-password admin --sample-data n --application-url http://localhost --force
app/console doctrine:fixture:load --no-debug --append --no-interaction --env=test --fixtures ./vendor/oro/platform/src/Oro/Bundle/TestFrameworkBundle/Fixtures
app/console oro:test:schema:update --env test
```

But the command is missing since `1.9`! What happened? Why is this missing in the docs or UPGRADE file?

**Comment by sergeyz** [comment]
Hi, @sbani! Its no longer needed to run `oro:test:schema:update` command, TestFrameworkBundle contains migrations for test entities. So now https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/TestFrameworkBundle/Tests/Functional/SchemaTest.php validates schema and metadata matches

Just sent pr for docs https://github.com/orocrm/documentation/pull/203, thank you for report!

**Comment by sbani** [comment]
Thanks
