### ISSUE TITLE
Add Tag Groups as part of tags bundle

### ISSUE THREAD

**Issue by StephenOTT** [orocrm/platform#424]
The ability to group tags together as Taxonomies/Tag Groups would allow admins to create more structured understanding of tags and sibling relationships to other tags.

**Comment by artml** [comment]
Hi Stephen,

Thanks for the suggestion, we will add this feature to our backlog.

**Comment by sadortun** [comment]
Hi @artml do you have an ETA for this ?

**Comment by StephenOTT** [comment]
@artml @DimaSoroka, I think the best approach to solve this tag issue is to build a core tag system (Taxonomies and Terms), where terms have have parent child relationships, and that each Taxonomy is likely a entity that extends the base Tag/Taxonomy entity. (or something like that).

The current Tags implementation is fairly specific to "Free Form Tags" that are applied to certain entities, but as use cases expand (as i have heard from @sadortun ), people are looking to use tags in very similar ways to how CMS's such as Drupal use tagging.

Thoughts?

**Comment by artml** [comment]
@StephenOTT no objections from our side, it's just not on top of our priorities list at the moment. Current tags are good enough for most use cases, and there are other areas of OroCRM that call for more immediate improvement.

I'm leaving this as open for contribution for now.

**Comment by sadortun** [comment]
I've started working on something.... to be continued

**Comment by sadortun** [comment]
Hi @artml  Master doesnt seems to [build](https://travis-ci.org/orocrm/platform/branches) ? What is the best version to use to test and validate  a PR ?

**Comment by StephenOTT** [comment]
been looking at: http://docs.sylius.org/en/latest/bundles/SyliusTaxonomyBundle/index.html

**Comment by sadortun** [comment]
We have a good working prototype. with 1.9.x. I'll try to make it available soon

**Comment by artml** [comment]
Thank you @sadortun !

**Comment by sadortun** [comment]
For thoses who are interested, a working prototype is availabe here: 


https://github.com/NewEraSystems/platform/tree/feature/424-tag-groups


![image](https://cloud.githubusercontent.com/assets/794449/18937864/23e36040-85c2-11e6-9e18-a8fc60451a07.png)

![image](https://cloud.githubusercontent.com/assets/794449/18937870/2a17912a-85c2-11e6-8822-200a5524b7a5.png)

![image](https://cloud.githubusercontent.com/assets/794449/18937874/2f59d40e-85c2-11e6-9dd4-165df5b84561.png)


Migration are not implemented. you need to run `doctrine:schema:update --dump-sql` to update your DB

**Comment by StephenOTT** [comment]
@sadortun any further updates?  Worth a PR yet?

**Comment by sadortun** [comment]
Yes, soon... 
- [ ] Adding Migrations

**Comment by StephenOTT** [comment]
@sadortun any new features added? or refinements?

**Comment by sadortun** [comment]
@StephenOTT, No, working well enough for now. There is a few more thing that would be nice, but i am not sure if we will have time in the near future.

- [ ] Tag color override Taxonomy color
- [ ] Nested taxonomies (parent tree)
- [ ] Taxonomy search/list page that would display all nested Tags and entities

If you have some spare time, feel free to fork my fork and submit a PR there, I'll submit a PR to the `platform` repo once Migrations are completed

**Comment by artml** [comment]
@sadortun any chance you might submit it within two weeks, before our 2.0 code freeze? I'd love to mention you in our release notes :)

**Comment by sadortun** [comment]
Sure !  I'll finish the migrations next week.

**Comment by sadortun** [comment]
@artml Do you think you can push on your side to implement #541 That would be a great addition !

**Comment by artml** [comment]
@sadortun sadly, no. We have just one sprint left and plenty of features to complete.

I will add it to 2.1 backlog though.

**Comment by sadortun** [comment]
Ok, thanks!

**Comment by mkudelya** [comment]
Hi @sadortun 

I have merged your PR in master branch. Feature will be available in public platform repository in a few days.

Thanks!

**Comment by mkudelya** [comment]
new feature is already on orocrm. closing the issue.
