### ISSUE TITLE
Impossible to serialize associations with EntitySerializer

### ISSUE THREAD

**Issue by ishakuta** [orocrm/platform#425]
In updateQuery method, updateSelectQueryPart called without last param, which is false be default

https://github.com/orocrm/platform/blob/master/src/Oro/Component/EntitySerializer/EntitySerializer.php#L343

**Comment by vsoroka** [comment]
The "to-one" associations are added by the next code. Please see https://github.com/orocrm/platform/blob/master/src/Oro/Component/EntitySerializer/EntitySerializer.php#L347-L366. The "to-many" associations are loaded by another method. Please see 'loadRelatedData'.

Could you please describe the issue in more details?

**Comment by artml** [comment]
No response from @ishakuta yet so I'm closing it for now.
