### ISSUE TITLE
Comments submission should use "Save" instead of "Send"

### ISSUE THREAD

**Issue by StephenOTT** [orocrm/platform#429]
When submitting a comment to a entity, the submit button's label is "Send":
![screen shot 2016-03-31 at 1 39 17 pm](https://cloud.githubusercontent.com/assets/1994838/14185119/6d5e3ba6-f746-11e5-8dd1-93d3fdc51894.png)

But in other places such as the adding of a note, the submit button is "Save".  It would seem to make more sense in the context of submission to use "Save" instead of "Send".

Would suggest change from Send to Save for the submission button of comments unless there is a reason for the differentiation?

**Comment by iklymenko** [comment]
@StephenOTT,
thanks for the good suggestion! We already had similar ticket in the backlog, but we thought to rename button to "Add Comment" and title of this popup to "Add". What do you think about this decision? Or just renaming "Send" to "Save" will be better?

**Comment by StephenOTT** [comment]
"Add" is for sure a better word than "Send" in this context.  I had suggested "Save", just as a more generic word that can be used throughout the platform regardless of context.

**Comment by iklymenko** [comment]
@StephenOTT, thanks!

**Comment by artml** [comment]
Fixed in 1.10 master
