### ISSUE TITLE
Update button does not appear when using Is Empty or Is Not Empty in data grid Filters

### ISSUE THREAD

**Issue by StephenOTT** [orocrm/platform#430]
When using a filter in a data grid you can update the field through the Update button or by selecting the filter option and clicking outside of the filter and it will update the grid.
![screen shot 2016-03-31 at 2 28 47 pm](https://cloud.githubusercontent.com/assets/1994838/14186569/05f02248-f74d-11e5-95ce-a4c41b28174c.png)

But when you use the `Is Empty` or `Is Not Empty` options, the Update button does not appear.  You can still select away from the filter option and the grid will update.  But without the Update button it is a major user blocker without specific training for them to know to click away.  The expected behaviour is to select the update button.

![screen shot 2016-03-31 at 2 27 30 pm](https://cloud.githubusercontent.com/assets/1994838/14186527/cf6bb8d6-f74c-11e5-978a-21ef4fe2bb21.png)
![screen shot 2016-03-31 at 2 27 23 pm](https://cloud.githubusercontent.com/assets/1994838/14186529/d043651a-f74c-11e5-819d-6a137902e0fe.png)

Tested in Safari, Chrome, and Firefox Desktop

**Comment by artml** [comment]
@StephenOTT we've fixed this in 1.9.1 version. Thanks for reporting the bug!
