### ISSUE TITLE
Accessibility: Form Labels

### ISSUE THREAD

**Issue by StephenOTT** [orocrm/platform#431]
As a general rule, when creating forms / inputs that do not have a label (likely because you did not want a visible label, the practice to meet accessibility has been to apply the label but using a class to make it invisible to the user.  

Example of the input field for search on a DataGrid filter:
![screen shot 2016-03-31 at 2 47 48 pm](https://cloud.githubusercontent.com/assets/1994838/14187180/c0fbb0be-f74f-11e5-90ea-d80bf7d7a6a7.png)
![screen shot 2016-03-31 at 2 47 54 pm](https://cloud.githubusercontent.com/assets/1994838/14187182/c2a663fa-f74f-11e5-91e8-a3d0cac38f41.png)

Here are some more details about Form accessibility for Labels: https://www.w3.org/WAI/tutorials/forms/labels/

You will see that there are other options such as using Aria-Label and other techniques for special cases.
Its a good quick read to keep in mind.

**Comment by mkudelya** [comment]
Hi @StephenOTT 

We will keep in mind these approaches. I'm closing this issue.
Thank you.
