### ISSUE TITLE
How to use operator LIKE in datagrid.yml ?

### ISSUE THREAD

**Issue by VitaliyBelous** [orocrm/platform#440]
How to  use operator LIKE in datagrid.yml with %, eg link like “%word%”? 

Native SQL looks
SELECT * from table WHERE link like '%word%'; 

I tried this in datagrid: 
......
     where:
               and:
                      - referral.link LIKE '%%word%%'
.......

but it doesnt work!
Error: "The parameter "key" must be defined."
Do you have some solution?

**Comment by vsoroka** [comment]
Hi @VitaliyBelous,

Thank you for reporting the issue.
It seems that it is a bug in [SystemAwareResolver](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DataGridBundle/Provider/SystemAwareResolver.php).

I've added this issue in our backlog.

As a workaround you can create a listener for **oro_datagrid.datagrid.build.before.your_grid_name** event of your grid to add LIKE operator.

**Comment by venimus** [comment]
Meanwhile you could also use `CONCAT(CHAR(37), 'word', CHAR(37))` as a workaround
