### ISSUE TITLE
"tel:" links in signatures are removed

### ISSUE THREAD

**Issue by zizzfizzix** [orocrm/platform#441]
When you add a tel: link in your signature it gets stripped off.
`<a href="tel:000000000">000 000 000</a>` becomes just `000 000 000`
It is reproducible every time.

**Comment by StephenOTT** [comment]
That happen with all HTML? likely the signature is escaped of HTML and JS for security and formatting?

**Comment by Krushelnitskiy** [comment]
Hi @zizzfizzix. 

Oro Platform uses HTML Purifier for validation URI. By default in HTML Purifier available schema formats (file. ftp, http, https, data, nntp, mailto, news) and HTML Purifier not support schema tel in attribute href.

To resolve this problem in your project you can do the following:


1.  Create class HTMLPurifier_URIScheme_tel

 ```
 class HTMLPurifier_URIScheme_tel extends HTMLPurifier_URIScheme {
  
     public $browsable = false;
     public $may_omit_host = true;
  
     public function doValidate(&$uri, $config, $context) {
         $uri->userinfo = null;
         $uri->host     = null;
         $uri->port     = null;
  
         $validCalltoPhoneNumberPattern = '/^\+?[\(\)\.0-9_-]+$/i'; // <---whatever pattern you want to force phone numbers to match
         $proposedPhoneNumber = $uri->path; // defined phone
         if (preg_match($validCalltoPhoneNumberPattern, $proposedPhoneNumber) !== 1) {
             return FALSE;
         } else {
             return TRUE;
         }
     }
 }
 ```

2.  Regitster HTMLPurifier_URIScheme_tel class in HTMLPurifier_URISchemeRegistry:

 ```HTMLPurifier_URISchemeRegistry::instance()->register('tel', new HTMLPurifier_URIScheme_tel); ```

3. Extend class SanitizeHTMLTransformer and change the method sanitize to add value 'tel' => true in config

 ```
  $config->set(
             'URI.AllowedSchemes',
             ['http' => true, 'https' => true, 'mailto' => true, 'ftp' => true, 'data' => true, 'tel' => true]
         );
 ```
 

>  link to method https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/FormBundle/Form/DataTransformer/SanitizeHTMLTransformer.php#L56

 4..  Extend OroRichTextType and update the method buildForm to use extended SanitizeHTMLTransformer class.

> link to OroRichTextType https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/FormBundle/Form/Type/OroRichTextType.php

 5..  Update service oro_form.type.rich_text to use Extend OroRichTextType.

**Comment by sadortun** [comment]
@Krushelnitskiy will you make a PR with this ?

**Comment by iklymenko** [comment]
@sadortun, we will include this fix into the one of our next releases. Or we'll do it faster, if somebody contributes it. :)

**Comment by zizzfizzix** [comment]
I'm glad that you have found a solution, unfortunately I can't contribute a PR, but I'm looking forward to a future release with the fix incorporated 😄

**Comment by iklymenko** [comment]
@zizzfizzix, anyway, thanks for heads up on the issue!

**Comment by JhumanJ** [comment]
And just like that, 5 years later @Krushelnitskiy's post helped me supporting custom protocol for Notion. Internet is an amazing place
