### ISSUE TITLE
Twig DateTimeExtension is forced to UTC

### ISSUE THREAD

**Issue by codesman** [orocrm/platform#444]
Our system uses the HST timezone. One of our agents recently brought to my attention the fact that the MyEmails datagrid is reporting the email times in UTC and not HST.

I confirmed this on orocrm/platform 1.9.1 today by sending an email at 1:43PM HST, and here is what the MyEmails page shows:

![screen shot 2016-04-26 at 6 19 41 pm](https://cloud.githubusercontent.com/assets/1653589/14839080/94d003ea-0bdc-11e6-98b6-abf7bd5548af.png)

So I did some dumping from `/vendor/oro/platform/src/Oro/Bundle/EmailBundle/Resources/views/macros.html.twig` with this:

```PHP
{{ dump(date()) }}
{{ dump(date(date)) }}
{{ dump(date()|oro_format_date) }}
{{ dump(date(date)|oro_format_date) }}
```
I get this:
```PHP
// This is HST
object(DateTime)#21121 (3) {
  ["date"]=>
  string(26) "2016-04-26 15:47:58.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(16) "Pacific/Honolulu"
}
// This is HST
object(DateTime)#21121 (3) {
  ["date"]=>
  string(26) "2016-04-26 13:43:08.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(16) "Pacific/Honolulu"
}
// This is UTC
string(12) "Apr 27, 2016"
// This is UTC
string(12) "Apr 26, 2016"
```
The `date` parameter that is passed in to the twig macro is in UTC. The date() and date(date) calls correctly convert to the system timezone(HST). The problem is that when an HST date is passed to the oro_format_date filter it returns values in UTC and not HST. I don't believe this is the desired default behavior.

The problem appears to be in `/vendor/oro/platform/src/Oro/Bundle/LocaleBundle/Twig/DateTimeExtension.php`

There are 3 methods in that class that all contain this: `$timeZone = $this->getOption($options, 'timeZone', 'UTC');`

It appears that if you don't specify a timezone Option(which the twig macro does not) then it forces timezone to UTC, even if that is not what the system uses globally.

I solved this problem in my app by removing the 3rd parameter in all of the `getOption` calls.  I will submit a pull request, but I'm not sure if this will cause problems elsewhere.  I don't think so, because I can't think of a good reason you would always want to force to UTC if an option hasn't been passed.

**Comment by artml** [comment]
Closing this along with the related PR on @codesman 's request
