### ISSUE TITLE
Twig dependency

### ISSUE THREAD

**Issue by tadcka** [orocrm/platform#447]
Symfony 2.7.\* required twig ~1.23
ORO platform 1.9.\*  required twig 1.20.0

https://github.com/symfony/symfony/blob/2.7/composer.json#L24
https://github.com/orocrm/platform/blob/1.9/composer.json#L25

**Comment by artml** [comment]
@tadcka thanks for pointing this out. Does this cause you any problems with install or update?

**Comment by tadcka** [comment]
@artml yes, i want update symfony with composer but get twig conflict. Symfony improve  container dump time https://github.com/symfony/symfony/pull/18265 Platform container dump use much time.

**Comment by artml** [comment]
@tadcka okay, thanks for clarification. We will try to resolve this issue asap.

**Comment by tadcka** [comment]
@artml status?

**Comment by artml** [comment]
@tadcka not sure if we might fix it before the release, will likely come with one of 1.10.x stability releases.

Can you please check if this conflict appears for Symfony 2.8? We've recently added its support, maybe the issue has been fixed along the way?

**Comment by DimaSoroka** [comment]
OroPlatform 1.10.13 requires twig 1.24.* and OroPlatform 2.0.0 requires 1.29.*, closing this issue.
