### ISSUE TITLE
Impossible to override User password hashing algo

### ISSUE THREAD

**Issue by ishakuta** [orocrm/platform#448]
@DimaSoroka @vsoroka partially related to https://github.com/orocrm/platform/issues/423
> Application configuration should be applied with highest priority so you should be able to have additional control on top of bundle configs.

try to add 
```
            Oro\Bundle\UserBundle\Entity\User:
                algorithm:            pbkdf2
                // algo options here
```
to app/config/security.yml

and you'll get Fatal Error cause type hinting in ArrayUtil::arrayMergeRecursiveDistinct 
`public static function arrayMergeRecursiveDistinct(array $first, array $second)`

which is because of merge `Oro\Bundle\UserBundle\Entity\User: sha512` with array provided above, 
yes, it's probably not a downside of that app.yml approach, but ArrayUtil issue

P.S.: checked on 1.9 but as I see master branch can also have the same issue

**Comment by hurricane-voronin** [comment]
Hi @ishakuta,

Thanks for your PR, soon you'll see it at master.

**Comment by ishakuta** [comment]
@hurricane-voronin won't you update 1.9 branch with this fix?

**Comment by DimaSoroka** [comment]
@ishakuta, feel free to submit PR, we are welcome contributions to maintenance branches with latest minor version and to master. All ongoing maintenance is done in the master except customer support issues and community contributions.

**Comment by ishakuta** [comment]
@DimaSoroka that's basically the same two commits to cherry-pick from master :)

**Comment by artml** [comment]
The pull request has been merged so I assume this can be closed.
