### ISSUE TITLE
api_wsse_secured not uses the same nonce cache as wsse_secured

### ISSUE THREAD

**Issue by ishakuta** [orocrm/platform#449]
Seems like [api_wsse_secured](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/ApiBundle/Resources/config/oro/app.yml#L8) firewall doesn't use [nonce cache] (https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/SecurityBundle/DependencyInjection/OroSecurityExtension.php#L83-L83) nonce_cache_service_id

That leads to ability to use the same nonce twice.

**Comment by iklymenko** [comment]
Hi @ishakuta,
thanks for heads up on this. We will work on this issue in next two weeks and include fix for the next feature release.

**Comment by ishakuta** [comment]
Issue with nonce cache were resolved, there's another one related.
So, the app has two firewalls: 

- wsse_secured (old) with 'main' context that allows to handle API requests from OroCRM UI (such as workflow transitions)

- api_wsse_secured (new) with 'main' context, but, with `stateless: true`, which means that `context: main`, won't be used and this firewall won't authenticate API requests from UI (workflow transitions)

While it's ok in general, but when dealing with auth errors these two firewalls will lead to WsseAuthProvider will be called twice (two different instances with same configuration). Given that, `$lastException` in `AuthenticationProviderManager` will have always "Previously used nonce detected.".

Which is fine, cause API client will have still the same response (401 with empty body), but the problem arise when you'd like to add meaningful error messages in API response for codes other than 200. In such case you'll always get "Previously used nonce detected.".
