### ISSUE TITLE
"../../package/platform/" is not found 

### ISSUE THREAD

**Issue by ed29** [orocrm/platform#456]
Hi:

When i do the php composer.phar install --prefer-dist --no-dev command,it has a exception:

>  [RuntimeException]
 Source path "../../package/platform/" is not found for package oro/platform

How to make it work?

**Comment by sergeyz** [comment]
Hi, @ed29!

Thanks for report, going to fix this issues asap

Use stable version as an alternative to master branch https://github.com/orocrm/platform/tree/1.9

**Comment by ed29** [comment]
OK,fine

**Comment by DimaSoroka** [comment]
Issue was fixed, thanks again!
