### ISSUE TITLE
The service "oro_email.workflow.action.send_email" has a dependency on a non-existent service "oro_action.context_accessor".

### ISSUE THREAD

**Issue by dextervip** [orocrm/platform#457]
I am installing the crm appliaction platform using master to test PHP 7 support however I am getting an exception:

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "oro_email.workflow.action.send_email" has a dependency on a non-existent service "oro_action.context_accessor".

**Comment by mccar** [comment]
Which version of the application you are trying to install? It is master?

**Comment by sergeyz** [comment]
Hi, @dextervip !

`composer show --installed | grep oro` is the best way to show installed versions

**Comment by dextervip** [comment]
All oro packages are in dev-master version. 




On Wed, May 18, 2016 at 4:06 AM -0700, "Sergey Zhuravel" <notifications@github.com> wrote:












Hi, @dextervip !



composer show --installed | grep oro is the best way to show installed versions

**Comment by sergeyz** [comment]
dev-master can be different for different moments, depends on commit actually. Please make sure you have latest commits, or post command output here

**Comment by dextervip** [comment]
composer show |  grep oro
oro/crm                                  dev-master cd86052 OroCRM
oro/crm-abandoned-cart                   dev-master 0077e6a OroCRM Abandoned Car                                                                                                                                  t
oro/crm-dotmailer                        dev-master 153b471 OroCRM Dotmailer int                                                                                                                                  egration
oro/crm-hangouts-call-bundle             dev-master c705de8 OroCRM Google Hangou                                                                                                                                  ts integration
oro/crm-magento-embedded-contact-us      dev-master e324902 OroCRM Package, Cont                                                                                                                                  act Us form for Magento
oro/crm-mail-chimp                       dev-master 076676e OroCRM MailChimp int                                                                                                                                  egration
oro/crm-zendesk                          dev-master bbbf441 OroCRM Zendesk Integ                                                                                                                                  ration
oro/doctrine-extensions                  1.0.12             Doctrine Extensions                                                                                                                                   for MySQL and PostgreSQL.
oro/jsplumb                              1.7.6              jsPlumb provides a m                                                                                                                                  eans for a developer to visually c...
oro/moment-timezone                      0.3.1              Parse and display da                                                                                                                                  tes in any timezone
oro/platform                             dev-master b37231b Business Application                                                                                                                                   Platform (BAP)
oro/platform-serialised-fields           dev-master 00e1e93 Oro Platform Seriali                                                                                                                                  zed Fields

I have updated all dependencies before opening this issues.

**Comment by sergeyz** [comment]
> I have updated all dependencies before opening this issues.

`oro/platform dev-master b37231b` is 21 days behind HEAD 

we are going to check lock file is up to date, please do `composer update` for now

**Comment by dextervip** [comment]
@sergeyz I updated now but still got the same result. oro/platform dev-master b37231b Business Application Platform (BAP).

**Comment by mrfroasty** [comment]
Got the same error here - testing oro-platform + PHP 7 + app_dev.php.If I swap to app.php then the error is no longer to be seen.

**Comment by artml** [comment]
@mrfroasty on the latest master branch?

**Comment by mrfroasty** [comment]
@artml 
yes latest master branch as i believed thats where the PHP 7, otherwise its true I could have used stable 1.9.

**Comment by mrfroasty** [comment]
```
composer show | grep oro
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
oro/doctrine-extensions                  1.0.12             Doctrine Extensions for MySQL and PostgreSQL.
oro/jsplumb                              1.7.6              jsPlumb provides a means for a developer to visually connect elements on their web pages.
oro/moment-timezone                      0.3.1              Parse and display dates in any timezone
oro/platform                             dev-master df3e947 Business Application Platform (BAP)
oro/platform-serialised-fields           1.4.1              Oro Platform Serialized Fields
```

P:S
oro/platform-serialised-fields modification - I have done to composer.json to get around conflict in composer:

```
diff --git a/composer.json b/composer.json
index 69bc4ce..eaf11ad 100644
--- a/composer.json
+++ b/composer.json
@@ -20,7 +20,7 @@
     ],
     "require": {
         "oro/platform": "self.version",
-        "oro/platform-serialised-fields" : "self.version"
+        "oro/platform-serialised-fields" : "*"
     },
     "require-dev": {
         "sensio/generator-bundle": "2.5.3",


```

**Comment by mrfroasty** [comment]
@artml 
Please ignore me - I am having difficult to reproduce it anymore

**Comment by artml** [comment]
@mrfroasty no worries—feel free to reopen this if you manage to reproduce the issue and have clear STR.

Thank you!
