### ISSUE TITLE
Inline editing default route params only supports 'className'

### ISSUE THREAD

**Issue by LRotherfield** [orocrm/platform#458]
It looks like due to the configuration node of the inline editing extension, the only key that can be added as a default route parameter is className: https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DataGridBundle/Extension/InlineEditing/Configuration.php#L91

I don't think this was the intention as the documentation shows other values: https://github.com/orocrm/platform/commit/2552070df81df65958f4aff5482a57d56473798e#diff-9a5bb5d9a684815a47b83a73ea73ae2fR15

Currently using any key other than className results in a validation exception, I think it should be a prototype value in the configuration.

**As an aside**:

I was hoping to use a value from the query, is this possible, so a dynamic value?  For instance if I am selecting:

```
o.example_field as exampleField
```
Can I/should I be able to then?
```
default_route_params:
  example_field_param: exampleField
```

**Comment by hurricane-voronin** [comment]
Hi @LRotherfield,

All additional parameters that you needed in the request will be added automatically.
You just need to specify api accessor route for it e.g:
We can specify custom api accessor for contacts grid:

**Comment by hurricane-voronin** [comment]
Hi @LRotherfield,

In your case you need to specify custom api accessor, all additional parameters that you needed in the request will be added automatically.
E.g  custom api accessor for contacts grid:

```yml
        inline_editing:
            enable: true
            save_api_accessor:
                route: oro_api_post_custom_contact
```

with route  configuration:

```php
    /**
     * @Post("/custom/contact/{id}/{firstName}/{lastName}")
     */
```

in this case {id}, {firstName} and {lastName} will be replaced from query values.

**Comment by artml** [comment]
question appears to be solved so closing this for now
