### ISSUE TITLE
Question:after changing parameters.yml

### ISSUE THREAD

**Issue by ed29** [orocrm/platform#460]
Hi:

I installed crm-application and it works fine.Now,i want to make a change to app/config/parameters.yml,i had changed it,but it don't take effect,how to make it work?Was it been cached?

**Comment by sadortun** [comment]
You can run :
```
php app/console cache:clear --env prod
php app/console cache:clear --env dev
```

or delete the `app/cache/dev` and `app/cache/prod` folders

**Comment by ed29** [comment]
@sadortun Got it,thank you!
