### ISSUE TITLE
After cache:clear,get 500 error 

### ISSUE THREAD

**Issue by ed29** [orocrm/platform#461]
Hi:

I installed and using crm-application,after doing`php app/console cache:clear --env prod`,it will get http 500 error with frontend,and  need to exec `chmod -R 777 app/cache`to make it work.My server are ubuntu, nginx and php5-fpm.

I don't know whether it is a bug or nor.

**Comment by DimaSoroka** [comment]
Please make sure that ``app/cache`` has write permissions (recursively) for web server user. What we seeing happening in the scenario you described, when you call clear cache command it creates folders and files that are owned by your user and web server user doesn't have write permissions to created folders.

**Comment by ed29** [comment]
@DimaSoroka I understand now,thank you.
