### ISSUE TITLE
Changelog maintenance

### ISSUE THREAD

**Issue by sadortun** [orocrm/platform#462]
Hi Oro team,

Would it be possible that when PR are  merged into master to keep up to date the CHANGELOG.md ? It would be much easier to track added features.

For example, GitLab have a nice way to include not yet released features and bug fixes :
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CHANGELOG

The sane apply to the orocrm/crm project

**Comment by artml** [comment]
Hi Samuel,

Thank you for your suggestion. We'd like to have a similar file, but the sheer size of our product changes will require a lot of additional work that is not feasible to be done manually.

Do you know any tool that might compose such file automatically? It would be a nice help to us.

Thank you!

**Comment by sadortun** [comment]
Hi @artml I don't know a particular tool that can do this.

For the changelog, the idea is only to use it to track new Epics and noticeable changes, not every commits. At least to have an idea of what is going to be included in the next releases.

I am sure that many of us are trying to scan the huge commit log to see  what was implemented, which is long and painfull !

**Comment by artml** [comment]
@sadortun I see what you mean. I've created a [pre-release for 1.10](https://github.com/orocrm/crm/releases/tag/1.10.0), please see if this is what you're looking for?

(There's not a lot of text yet, I'm just checking the concept. Will add more if it's the thing.)

**Comment by sadortun** [comment]
It's  a start, but I don't believe it enough. Behind the scene, here is the foundamental question the changelog must be able to answer. 

> Considering the ORO team roadmap, should we develop the feature XYX on our own, and submit a PR, or wait for a new release that will contain that feature.

**Comment by artml** [comment]
@sadortun I think the best solution would be a case-to-case approach. If you are interested in any particular feature, open an issue here and discuss it with us. We will take it into consideration and then decide if we are going to [implement it ourselves](https://github.com/orocrm/crm/labels/scheduled%20for%20implementation) (and provide a more or less fixed implementation timeline) or [open the issue for community](https://github.com/orocrm/crm/labels/open%20for%20contribution) development. 

We're trying to improve our community issue management (we know we could have done better in the past!) and I think will outline this process in more detail in a blog post soon.

**Comment by artml** [comment]
@sadortun re: roadmap. IDK if GitHub has any tools for it. I would prefer to create no more than one or two future releases that roughly corresponds for a half year down the road. What time horizon you're looking at?

**Comment by sadortun** [comment]
Ok, if you would like, you can tag Milestones to issues, that would give a good idea of your short amd mid-term plans

**Comment by artml** [comment]
@sadortun that's exactly what I'm going to do.

If this solves the problem you've raised, can I close this issue for now?

**Comment by sadortun** [comment]
Yes, i think everybody will enjoy it  !
