### ISSUE TITLE
SecurityController loginCheck triggered sometimes. 

### ISSUE THREAD

**Issue by Numkil** [orocrm/platform#464]
Hey Orocrm, 

I'm sorry this issue is very vague but I've been unable to find a reason for this happening. 

I have been working on a project based on the Oro-platform. People have been reporting that sometimes, very rarely, they get a 500 internal server error when trying to log in. The error message when this happens is this. ```You must configure the check path to be handled by the firewall using form_login in your security firewall configuration.```. It seems that sometimes the login procedure tries to execute checkAction() on the SecurityController. 

The fact that this happens only sometimes is very confusing, and makes me think my Security.yml is correct. Have you guys been encountering similar issues?

Edit: I can ofcourse provide extra information, just tell me what you need.

**Comment by artml** [comment]
Hi Kevin,

Thank you for bringing this up. We haven't encountered anything like that but will gladly investigate it if you provide us at least an application log next time this happens in your project. Or a log from the past if you have one at hands.

**Comment by artml** [comment]
Closing this issue because of no feedback. @Numkil feel free to reopen it at any time.
