### ISSUE TITLE
How to set sent mail frequence

### ISSUE THREAD

**Issue by ed29** [orocrm/platform#467]
Hi:

I am use the SMTP to sent mail,i want to control the frequence of sending mail,example:sent a mail every 20 seconds.

How to make it?

**Comment by DimaSoroka** [comment]
Could you please explain a bit more your case and the reason for such delay?

**Comment by ed29** [comment]
I use third part SMTP account,they limit the amount of mails per minute,beyond the limit the account may be blocked.so,if i don't set the delay,it can't sent out the  subscripted emails.

I don't really known the SMTP account's limit,bus i has have an account been blocked.

**Comment by DimaSoroka** [comment]
I would recommend to use specialized services like [sendgrid ](https://sendgrid.com/) for this purpose instead adding a hack to the application.

**Comment by ed29** [comment]
OK,i will have a try.
