### ISSUE TITLE
[Bug] "Choice" inline edditing fail in grid

### ISSUE THREAD

**Issue by sadortun** [orocrm/platform#480]
Hi,

Changing the ORO Contact Gender field inline in the grid fail  due to an exeception in JS validation.

It look like `vendor\oro\platform\src\Oro\Bundle\FormBundle\Resources\public\lib\jquery.validate\additional-methods.js` is not included, therefore jquery.validate fail on any custom validation.

![image](https://cloud.githubusercontent.com/assets/794449/16367221/4963b01c-3bef-11e6-821b-b8d8b0f88977.png)

The `Choice` validation callback doesn't exists
![image](https://cloud.githubusercontent.com/assets/794449/16367233/63186818-3bef-11e6-8523-accc8c9d04b7.png)

Called by https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DataGridBundle/Resources/public/js/app/components/cell-popup-editor-component.js#L117

**Comment by Grygir** [comment]
Thank you for reporting this bug, we'll do our best to fix it within 1.10 release.
