### ISSUE TITLE
[BUG] PHP Fatal: DashboardBundle/Model/WidgetConfigs.php

### ISSUE THREAD

**Issue by sbani** [orocrm/platform#484]
Found a bug related to the dashboard bundle.

`The DashBoardController:widgetAction` checks for dashboard.yml config but doesn't check for the Bundle param.

## Example
URL: `http://crm-dev.dev/dashboard/widget/my_leads/XXXBundle/myLeads?_wid=dashboard-widget-623280200-94&_widgetContainer=dashboard-item&_widgetId=94`
> PHP message: PHP Fatal error:  Call to a member function getName() on null in /var/www/vhosts/orocrm/current/vendor/oro/platform/src/Oro/Bundle/DashboardBundle/Model/WidgetConfigs.php on line 231

The XXXBundle doesn't exist and leads to an error.

EDIT: the error comes from the wrong `_widgetId`

**Comment by sbani** [comment]
If the web server shows fatals, this could be seen as a [Full Path Disclosure](https://www.owasp.org/index.php/Full_Path_Disclosure) for a logged in attacker.

**Comment by artml** [comment]
The PR with the fix was merged so I'm closing this.
