### ISSUE TITLE
Load datagrid.yml from multiple files

### ISSUE THREAD

**Issue by sbani** [orocrm/platform#492]
Hi,

as our `datagrid.yml` file is growing and growing, we want to suggest a datagrid folder in `Rosources/config`. 

I thought about a combination of `FolderContentCumulativeLoader` and the `YamlCumulativeFileLoader`. One possibility is to add callback to the `FolderContentCumulativeLoader` which iterates over the loaded file names.

Example:

``` php
$folderLoader = new CumulativeConfigLoader(
    'oro_datagrid',
    [
        new YamlCumulativeFileLoader('Resources/config/datagrid.yml'),
        new FolderContentCumulativeLoader('Resources/config/datagrid/', -1, false, ['yml'], function($file) {
            $yamlParser = new YamlParser();
            try {
                return $yamlParser->parse(file_get_contents($file));
            } catch (ParseException $e) {
                $e->setParsedFile($file);
                throw new \InvalidArgumentException(sprintf('Unable to parse file "%s".', $file), $e->getCode(), $e);
            }
        }),
    ]
);
```

What do you think? Or do you know a better approach?

**Comment by sergeyz** [comment]
I suggest it to store under `Resources/config/oro` folder

**Comment by sadortun** [comment]
@sergeyz  `Ressources/config/oro/datagrid` ?

**Comment by sergeyz** [comment]
Yep, to split from symfony configs

**Comment by adamlundrigan** [comment]
The workflow bundle uses this notation to allow splitting up YAML files:

```yaml
imports:
    - { resource: 'b2b_flow_lead/steps.yml' }
    - { resource: 'b2b_flow_lead/attributes.yml' }
    - { resource: 'b2b_flow_lead/transitions.yml' }
    - { resource: 'b2b_flow_lead/transition_definitions.yml' }
```
([source](https://github.com/orocrm/platform/blob/2ac18cce58767af45462b78ddb569019782a4e0b/src/Oro/Bundle/WorkflowBundle/Resources/doc/reference/workflow/configuration-reference.md))

I tried the same approach with one of my `datagrid.yml` files but it does not work there ("A configuration for "xxxxxx" datagrid was not found.").  Perhaps that `imports` functionality can be generalized so it works in all the oro YAML files?

**Comment by sbani** [comment]
In my opinion, @adamlundrigan's solution with `imports` is better than my first idea

**Comment by StephenOTT** [comment]
Any movement on this??

**Comment by mkudelya** [comment]
Currently yml import is working only for workflow, but we are open to contribution.
Thanks!

**Comment by dewos** [comment]
@mkudelya any update on your side? I might try to implement it next weekend.

**Comment by mkudelya** [comment]
Hi @dewos 

Currently we are not planning to do this feature. We very much welcome contributions, thanks.

**Comment by dewos** [comment]
@mkudelya I'm on it!

**Comment by dewos** [comment]
Done

**Comment by sadortun** [comment]
@dewos Awesome !

**Comment by mkudelya** [comment]
Hi @dewos 

Thank you for your contribution! I will review and test it tomorrow.

**Comment by mkudelya** [comment]
I have merged this feature in 1.10 branch and master. The next release of 1.10 will contain it. On master you can see it in the few days.
Thanks!

**Comment by dewos** [comment]
@mkudelya Very nice. 

I wish you all happy holidays.

**Comment by mkudelya** [comment]
@sadortun 

Happy holidays! :)
