### ISSUE TITLE
1.10 branch ?

### ISSUE THREAD

**Issue by sadortun** [orocrm/platform#493]
Hi @artml.

Since 1.10 is already tagged in beta, do you think you could push a `1.10` branch ? 

Have a good day,
Samuel

**Comment by artml** [comment]
@sadortun not sure I understood this, or am capable of doing so. I am not a developer, sorry :) can you please explain?

**Comment by mbessolov** [comment]
@sadortun The pre-release identifier part (beta.X) in the 1.10.0-beta.X tags correlates with the _OroCommerce _ release cycle just for the referencing purpose. OroPlatform doesn't have pre-release versions for minor releases in 1.x (rare exceptions possible).

OroPlatform 1.10 will be pushed when the OroPlatform team is ready to release it.

**Comment by sadortun** [comment]
Perfect! Thanks!
