### ISSUE TITLE
dev-master API and Doctrine ORM inheritance mapping

### ISSUE THREAD

**Issue by adamlundrigan** [orocrm/platform#501]
I'm running `dev-master` so I can work with the new parts of ApiBundle.  I've set up an entity `CourseRegistration` which has ManyToOne associations with a few other entities, one of which is mapped by Doctrine ORM using class-table inheritance (`courseOfferingGroup`, with mapping IC=`CourseOfferingGroup\InClassGroup` and VR=`CourseOfferingGroup\VirtualGroup`).  When I try to use the API to create a new instance of the `CourseRegistration` entity:

```
POST /api/registrationcourseregistrations HTTP/1.1
Authorization: WSSE profile="UsernameToken"
X-WSSE: UsernameToken Username="xxxxxx", PasswordDigest="xxxxxx", Nonce="xxxxxx", Created="xxxxxx"
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

courseOfferingGroup=3&employee=293&employeeProfile=293&status=P
```

 I get a 400 Bad Request with this response:

```json
[
  {
    "title": "form constraint",
    "detail": "This value is not valid.",
    "source":"courseOfferingGroup"
  }
]
```

I did a git bisect between c273cbc (when the above worked) and HEAD (d0c0f92) and the problem appears to be in 5d00fb5 (by @vsoroka).  It's a big commit...any advice how to trace that auto-generated form validation to find out why it's rejecting the CTI entity?

**Comment by mkudelya** [comment]
Hi @adamlundrigan,

[Here](https://www.orocrm.com/forums/topic/create-custom-entity-from-rest-api) i explained how to add record to **extend** entity. You can use this example to create own records.
The main idea is generate api key in user profile, go to for example [there](http://orocrmee.local/app_dev.php/api/doc/rest_json_api#get--api-accounts) and click on sandbox and click on Try button. This json will be hint to creating records.

**Comment by adamlundrigan** [comment]
Another case of me not RTFM.  I keep forgetting that the new API follows JSON.API so I should look to it's documentation first when I run into trouble.  I updated my code to send a JSON body like you did in your example (the JSON.API spec says to do):

```json
{
  "data":
    {
      "type": "registrationcourseregistrations",
      "attributes": {
        "status": "P"
      },
      "relationships": {
        "courseOfferingGroup": {
          "data": {"type": "virtualgroups", "id": 17}
        },
        "employeeProfile": {
          "data": {"type": "employeeprofiles", "id": 502}
        },
        "employee": {
          "data": {"type": "employees", "id": 488}
        }
      }
    }
}
```

it works (record is created) but I get a 500 response back:

```json
{
  "errors": [
    {
      "status": "500",
      "title": "runtime exception",
      "detail": "An object of the type \"Oro\\Bundle\\AddressBundle\\Entity\\Region\" does not have the identifier property \"combinedCode\"."
    }
  ]
}
```

The "employeeprofiles" entity has a relation to `Oro\Bundle\AddressBundle\Entity\Address`, so I need to do some digging to find out what's going on there.  If I do a `GET /api/registrationcourseregistrations/:id` with a valid ID it returns the JSON for the record (including address, country and region data).  Perlis of living on the bleeding edge of your platform :wink:

**Comment by adamlundrigan** [comment]
No longer have this problem after updating to 1.10.0
