### ISSUE TITLE
Oro Platform Update fails on master

### ISSUE THREAD

**Issue by Richard87** [orocrm/platform#506]
Updating to Master branch failed, need some guidence to what to do next (it goes incredibly slow and I would love to have PHP7 support)

But this happend:

	# sudo -u www-data php5 app/console oro:platform:update --env prod --force
	Process migrations...
	  > Oro\Bundle\EntityExtendBundle\Migration\LoadEntityConfigStateMigration
	  > Oro\Bundle\MigrationBundle\Migration\UpdateBundleVersionMigration
	  > Oro\Bundle\EntityExtendBundle\Migration\RefreshExtendCacheMigration

	  [Doctrine\ORM\Mapping\MappingException]
	  The target-entity OroCRM\Bundle\TaskBundle\Entity\Task cannot be found in 'Oro\Bundle\CommentBundle\Entity\Comment#task_f06ab819'.

	oro:entity-extend:cache:clear [--no-warmup] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--jms-job-id JMS-JOB-ID] [--current-user CURRENT-USER] [--current-organization CURRENT-ORGANIZATION] [--disabled-listeners DISABLED-LISTENERS] [--] <command>

		ERROR: The command terminated with an exit code: 1.
	  > Oro\Bundle\EntityConfigBundle\Migration\UpdateEntityConfigMigration - skipped
	  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendConfigMigration - skipped
	  > OroCRM\Bundle\ActivityContactBundle\Migration\ActivityContactMigration - skipped
	  > Oro\Bundle\ActivityListBundle\Migration\ActivityListMigration - skipped
	  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendIndicesMigration - skipped
	  > Oro\Bundle\EntityConfigBundle\Migration\WarmUpEntityConfigCacheMigration - skipped

	  [RuntimeException]
	  Failed migrations: Oro\Bundle\EntityExtendBundle\Migration\RefreshExtendCacheMigration.

	oro:migration:load [--force] [--dry-run] [--show-queries] [--bundles [BUNDLES]] [--exclude [EXCLUDE]] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--jms-job-id JMS-JOB-ID] [--current-user CURRENT-USER] [--current-organization CURRENT-ORGANIZATION] [--disabled-listeners DISABLED-LISTENERS] [--] <command>

	  [RuntimeException]
	  The command terminated with an exit code: 1.

	oro:platform:update [--force] [--skip-assets] [--symlink] [--force-debug] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--jms-job-id JMS-JOB-ID] [--current-user CURRENT-USER] [--current-organization CURRENT-ORGANIZATION] [--disabled-listeners DISABLED-LISTENERS] [--] <command>

Any help would be greatly appreciated!

**Comment by sadortun** [comment]
@Richard87 We had a lot of issues upgrading to master about a week ago,  The Task Bundle has been extracted, but its not yet available
The following versions seems to work better : 
- https://github.com/orocrm/crm/tree/5f0b1eb94925b26e0498c804183246b85d09d4af and
- https://github.com/orocrm/platform/tree/e32eeb8c002a6312a854f4fee9bb31d7c30ffb67

Related :  https://github.com/orocrm/crm/issues/192 https://github.com/orocrm/platform/issues/493

**Comment by Richard87** [comment]
Thank you! I'll give those a try :)

**Comment by Richard87** [comment]
Got this result:

	PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "orocrm_contact.event_listener.datagrid.my_contacts_activity" has a dependency on a non-existent service "oro_user.dashboard.owner_helper". in /home/crm/crm/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:58
	Stack trace:
	#0 /home/crm/crm/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(42): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processReferences(Array)
	#1 /home/crm/crm/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(36): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processDefinition(Object(Symfony\Component\DependencyInjection\Definition))
	#2 /home/crm/crm/vendor/symfony/symfony/src/Symfony/Comp in /home/crm/crm/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 58

Any more tips :)

**Comment by Richard87** [comment]
I just reinstalled 1.9.6 and got this error, should I be worried?

	# sudo -u www-data php5 app/console oro:platform:update --env prod --force
	PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Property OroCRM\Bundle\TaskBundle\Entity\Task::$contact_cdc90e7a does not exist' in /home/crm/crm/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php:80
	Stack trace:
	#0 /home/crm/crm/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php(80): ReflectionProperty->__construct('OroCRM\Bundle\T...', 'contact_cdc90e7...')
	#1 /home/crm/crm/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php(965): Doctrine\Common\Persistence\Mapping\RuntimeReflectionService->getAccessibleProperty('OroCRM\Bundle\T...', 'contact_cdc90e7...')
	#2 /home/crm/crm/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(721): Doctrine\ORM\Mapping\ClassMetadataInfo->wakeupReflection(Object(Doctrine\Common\Persistence\Mapping\RuntimeReflectionService))
	#3 /home/crm/crm/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(214): Doctrine\ORM\Map in /home/crm/crm/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php on line 80

**Comment by sadortun** [comment]
@Richard87 As i mentioned earlyer, i would recommend that you wait a bit to update, unless you are ready to dig deeper. If it's not too late, you can revert a backup.

Theses commands might help, look in the docs if you are not sure 

```
#!/bin/bash
php app/console --env=prod cache:clear  --no-debug
php app/console --env=prod oro:migration:load --force
php app/console --env=prod doctrine:schema:update --force
php app/console --env=prod oro:entity-extend:update-config
php app/console --env=prod oro:entity-extend:update-schema
php app/console --env=prod oro:entity-extend:cache:clear
php app/console oro:entity-config:update
php app/console cache:clear --env=prod --no-debug
php app/console --env=prod oro:platform:update  --force

**Comment by mkudelya** [comment]
@Richard87 We know about the task bundle issue and currently working on fix.
Thank you for your patience.

**Comment by Richard87** [comment]
Hi, unfortunatly I can't roll back to an earlier backup, is there a way to roll back the database changes?

Richard

**Comment by mkudelya** [comment]
@Richard87 Are you currently on 1.9.6 version? As temporary solution i suggest you copy [task bundle](https://github.com/orocrm/crm/tree/1.9/src/OroCRM/Bundle/TaskBundle) to appropriate directory if it doesn't exist and delete /app/cache/prod, /app/cache/dev directories and try again run oro crm in browser.

**Comment by Richard87** [comment]
Thank you for your help so far, I feel I have come along way...

I upgraded to master since I had a bad feeling about downgrading after migrating the database, and I came pretty far. 

First of all I copied in `OroCRMTaskBundle`

    prod ca:cl --no-debug
    PHP Fatal error:  Class 'OroCRM\Bundle\TaskBundle\OroCRMTaskBundle' not found in /home/crm/crm/app/cache/prod/bundles.php on line 102

Then, `ApiDocExtractor` was missing, so I copied that on in also

    prod ca:cl --no-debug
    PHP Fatal error:  Class 'Oro\Component\Routing\ApiDoc\ApiDocExtractor' not found in /home/crm/crm/app/cache/prod/appProdProjectContainer.php on line 18

Then `BusinessUnitListener` was copied in:

    prod ca:cl --no-debug
    PHP Fatal error:  Class 'Oro\Bundle\OrganizationBundle\Event\BusinessUnitListener' not found in /home/crm/crm/app/cache/prod/appProdProjectContainer.php on line 18

Then things went smoothly for a while ;)

Doctrine:schematic:update --force` failed`

	[Doctrine\DBAL\Exception\DriverException]
	An exception occurred while executing 'DROP INDEX IDX_C0FE4AAC6BF700BD ON orocrm_sales_opportunity':
	SQLSTATE[HY000]: General error: 1553 Cannot drop index 'IDX_C0FE4AAC6BF700BD': needed in a foreign key constrain
	t

But I deleted the index and foreign constraint manually and rerun the command, everything good :)

Until the last command, `Oro Platform Update`:

	# prod oro:platform:update  --force
	Process migrations...
	  > Oro\Bundle\EntityExtendBundle\Migration\LoadEntityConfigStateMigration
	  > Oro\Bundle\MigrationBundle\Migration\UpdateBundleVersionMigration
	  > Oro\Bundle\EntityExtendBundle\Migration\RefreshExtendCacheMigration
	  > Oro\Bundle\EntityConfigBundle\Migration\UpdateEntityConfigMigration
	  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendConfigMigration
	  > OroCRM\Bundle\ActivityContactBundle\Migration\ActivityContactMigration
	  > Oro\Bundle\ActivityListBundle\Migration\ActivityListMigration
	  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendIndicesMigration
	  > Oro\Bundle\EntityConfigBundle\Migration\WarmUpEntityConfigCacheMigration
	Loading permissions...
	  > VIEW
	  > CREATE
	  > EDIT
	  > DELETE
	  > ASSIGN
	  > SHARE
	  > CONFIGURE
	Loading workflow definitions...
	PHP Notice:  Undefined index: ref-one in /home/crm/crm/vendor/oro/platform/src/Oro/Bundle/ActionBundle/Model/AttributeGuesser.php on line 333
	PHP Notice:  Undefined index: ref-one in /home/crm/crm/vendor/oro/platform/src/Oro/Bundle/ActionBundle/Model/AttributeGuesser.php on line 334


																																																																																								   
	  [ErrorException]                                                                                                                                                                                                                                                                                                                                             
	  Catchable Fatal Error: Argument 3 passed to Oro\Bundle\ActionBundle\Model\AttributeGuesser::formatResult() must be of the type array, null given, called in /home/crm/crm/vendor/oro/platform/src/Oro/Bundle/ActionBundle/Model/AttributeGuesser.php on line 335 and defined in /home/crm/crm/vendor/oro/platform/src/Oro/Bundle/ActionBundle/Model/AttributeGuesser.php on line 252
																																																																																								   


	oro:workflow:definitions:load [--directories [DIRECTORIES]] [--workflows [WORKFLOWS]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--jms-job-id JMS-JOB-ID] [--current-user CURRENT-USER] [--current-organization CURRENT-ORGANIZATION] [--disabled-listeners DISABLED-LISTENERS] [--] <command>





	  [RuntimeException]
	  The command terminated with an exit code: 1.



	oro:platform:update [--force] [--skip-assets] [--symlink] [--force-debug] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--jms-job-id JMS-JOB-ID] [--current-user CURRENT-USER] [--current-organization CURRENT-ORGANIZATION] [--disabled-listeners DISABLED-LISTENERS] [--] <command>


I understand I'm extremely premature whith trying to fix this, so I really appreciate all the help you have already given me, I hope this can help get the proper release out faster to ;)

Richard

**Comment by artml** [comment]
@Richard87 so you've managed to fix the issue?

**Comment by Richard87** [comment]
Hi, Partially, there seems to be a bug with the workflow component (as the exception over), and I don't know what other issues might remain, but for now it seems usable and is running.
