### ISSUE TITLE
Migration Issue Upgrading From 1.8.2 to 1.9.6

### ISSUE THREAD

**Issue by archy-bold** [orocrm/platform#507]
I'm attempting to upgrade my OroCRM instance from 1.8.2 to 1.9.6. Instead of doing so with composer, I'm replacing the file structure with one of the pre-packaged bundles from the site. The database is left untouched.

I run the `app/console oro:platform:update --env=prod --force` command and it starts to migrate the database, but I get the following errors:

```
ERROR: An index with name 'att_file_orig_filename_idx' was already defined on table 'oro_attachment_file'.
```

```
[RuntimeException]                                                                               
Failed migrations: Oro\Bundle\AttachmentBundle\Migrations\Schema\v1_4\AddOriginalFilenameIndex.
```

Is there anything I can do to upgrade my instance without losing my data?

**Comment by mkudelya** [comment]
@archy-bold I have tested your case and migrations executed without any errors.
Do you have any error if you comment up function of this migration?

**Comment by archy-bold** [comment]
I tried it on another environment and it worked fine. I'm not really sure what happened in the first case.

**Comment by artml** [comment]
Okay, closing it for now then. @archy-bold feel free to reopen if you manage to reproduce the issue.
