### ISSUE TITLE
QueryDesigner "Filters" should be usable without the "Columns" definitions

### ISSUE THREAD

**Issue by sadortun** [orocrm/platform#508]
Hello Artem,

The QueryDesigner Filter is a great feature, and it would be nice to be able to use it alone without the "Column" manager.

If you are interested, we might be able to submit a PR.
Have a good day,
Samuel

**Comment by artml** [comment]
@sadortun Hi Samuel,

Thing is, we have already done it ourselves to some extent. We've added the query designer to dashboard widgets and afaik from discussions with our dev team, that required some singling out of the component.

That feature was merged only about a week ago so please check it on the latest master. I also think @zebimax and @hurricane-voronin might provide some additional info.

**Comment by sadortun** [comment]
Hi @artml and @zebimax,

Nice work ! Everything work perfectly  !
