### ISSUE TITLE
Composer semver problem

### ISSUE THREAD

**Issue by sagikazarmark** [orocrm/platform#513]
When installing ORO Platform with the following config, composer tries to install `1.10.0-beta.3` instead of `1.10.0`:

``` json
{
    "require": {
        "php": "^7.0",
        "oro/platform": "^1.10"
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}
```

May it be because composer cannot recognize `1.10.0-beta.3` as a beta release? It might be a composer issue then, but in the meantime, it might make sense to adhere composer accepted formats if this is the cause.

**Comment by artml** [comment]
@sagikazarmark thanks for pointing this out, we'll apply the fix ASAP

**Comment by mkudelya** [comment]
@sagikazarmark On friday i installed orocrm with "^1.10" and indeed it was with '1.10.0-beta.3' version, but today i tried again: cleared composer cache and run "oro/platform": "^1.10" and "oro/platform": "~1.10", both variants gave the same result, "Installing oro/platform (1.10.0)"

**Comment by sagikazarmark** [comment]
Hm, strange. Nevertheless, I just checked your earlier tags: you used to use alphaX, the latest beta versions followed beta.X. I don't know what caused this issue.

**Comment by mkudelya** [comment]
Do you still have the issue with version ?

**Comment by sagikazarmark** [comment]
Just checked: no, I don't have this issue anymore.

**Comment by artml** [comment]
Okay, closing this for now. @sagikazarmark thank you very much for the report! feel free to reopen the issue if you encounter it again.

**Comment by sergeyz** [comment]
The reason is https://github.com/orocrm/platform/blob/1.10/composer.json#L13-L16 and https://github.com/orocrm/platform/blob/1.10/composer.json#L59
Make sure your application is on `1.10` branch too https://github.com/orocrm/platform-application/blob/1.10/composer.json#L14

If repository is missing, version `1.10.0` could not be installed, so `1.10.0-beta.3` is next candidate that fit to requirements

**Comment by sbani** [comment]
What is the main purpose of `orocrm/TranslationFormBundle`? What are the differences to the original a2lix repo?

**Comment by alexandr-parkhomenko** [comment]
`orocrm/TranslationFormBundle` brings support `Symfony 2.8` to `a2lix/TranslationFormBundle@1.x`. For now is no differences between original repo and fork, because PR from this fork has already merged to original a2lix repo.

**Comment by sbani** [comment]
ah ok thanks
