### ISSUE TITLE
Translatable values in select2.js

### ISSUE THREAD

**Issue by Djamy** [orocrm/platform#515]
Hello everyone !

I think the sentences [here](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/UIBundle/Resources/public/lib/jquery/select2.js#L3086-L3091) should be translatable.

There are potentially more things to translate in this file and maybe more in others javascript files.

That's all. 

Thanks :)

**Comment by artml** [comment]
@Djamy thank you for your proposal.

**Comment by mkudelya** [comment]
@Djamy Translation has been added and will be available on the next release. Thanks!

**Comment by Djamy** [comment]
@mkudelya Great! Thank you.
