### ISSUE TITLE
Do not require PHP timezone setting on PHP 7

### ISSUE THREAD

**Issue by sagikazarmark** [orocrm/platform#518]
It is not required for PHP 7 anymore. Is it required for Oro Platform itself?

**Comment by mbessolov** [comment]
There are date_default_timezone_get calls in the code to retrieve the current timezone set on the server.
How the default timezone should be configured for PHP - via php.ini (kinda required in PHP <7, as if it is not set in php.ini there will be a warning) or somehow else (e.g. "TZ" environment variable) - it is up to the developer/web-server administrator.

**Comment by sagikazarmark** [comment]
@mbessolov In PHP 5.x the following happens:

- A warning is triggered
- Timezone value falls back to "UTC"

AFAIK in php 7.x the warning has been removed, so it should work smoothly.

So I would say having timezone configured should not be a requirement on PHP 7.x since you will receive a proper value without a warning. Oro should not require to have the INI config to be set.

**Comment by mbessolov** [comment]
It's not an OroPlatform requirement.
We use SensioDistributionBundle, which adds this requirement - https://github.com/sensiolabs/SensioDistributionBundle/blob/4.0/Resources/skeleton/app/SymfonyRequirements.php#L428

They fixed it in master already - https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Resources/skeleton/app/SymfonyRequirements.php#L428 , it just has not been released yet.

**Comment by sagikazarmark** [comment]
Ah, okay, totally missed that because I never used SymfonyRequirements. :trollface: 
Sorry for trouble then.
