### ISSUE TITLE
Optional-validation-handler.js: ignore not-visible inputs / selects when looking for not-empty fields

### ISSUE THREAD

**Issue by dgspurgin** [orocrm/platform#522]
hasNotEmptySelect & hasNotEmptyInput seem intended to check for user input in visible fields.  Can not-visible fields be ignored when doing these checks for user input?  (I have a use case where we are presetting data in country select box in order to get our region select box to behave as desired BUT this optional-validation-handler script then detects address form as not empty and then turns on asterisks.

Suggested change to:
Oro\Bundle\FormBundle\Resources\public\js\optional-validation-handler.js

```
        /**
         * @param {jQuery} group
         * @returns {boolean}
         */
        hasNotEmptyInput: function(group) {
            var elementsSelector = 'input[type!="checkbox"][type!="radio"][type!="button"][data-required]:visible,' +
                ' input[type="radio"][data-required]:checked:visible,' +
                ' input[type="checkbox"][data-required]:checked:visible';
            var checkedElements = group.find(elementsSelector);
            for (var i = 0; i < checkedElements.length; i++) {
                if (!this.isValueEmpty($(checkedElements[i]).val())) {
                    return true;
                }
            }

            return false;
        },

        /**
         * @param {jQuery} group
         * @returns {boolean}
         */
        hasNotEmptySelect: function(group) {
            var elements = group.find('select[data-required]:visible');
            for (var i = 0; i < elements.length; i++) {
                if (!this.isValueEmpty($(elements[i]).find('option:selected').val())) {
                    return true;
                }
            }

            return false;
        },

```

**Comment by ignat-s** [comment]
@dgspurgin, ignoring hidden fields will not work in all cases. For example, fields powered with "select2" has hidden field to store selected value the field is not hidden on UI of form. Will it cover your use case if it will be possible to pass a custom module to replace "oroform/js/optional-validation-handler" in the collection form of addresses? Other solution I think of is to provide a possibility to inject custom logic on the level of the field to be able to override default logic of detecting empty value.

**Comment by dgspurgin** [comment]
@ignat-s If I could override optional-validation-handler and use a custom one that would work great.  Having issues overriding (as stated in https://github.com/orocrm/platform/issues/523) because of how validate.js loads the optional validator with a relative ref.  I attempted to override validate.js as well and make it a custom piece but not working.

@AlexandrDmitriev said he had a solution?

**Comment by ignat-s** [comment]
@dandries , the problem with an override of "optional-validation-handler" was already fixed and should be available for you. But we are still working on adding a more precise way for extending this logic instead of global override of "optional-validation-handler".

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
