### ISSUE TITLE
Relative referenced dependency prevents override

### ISSUE THREAD

**Issue by dgspurgin** [orocrm/platform#523]
In your validate.js file in the Form bundle
Oro\Bundle\FormBundle\Resources\public\js\extend\validate.js

Could you refer to dependency by its handle/alias instead of relative reference.  Unable to override with this relative reference (see below):

```
define([
    'jquery',
    'underscore',
    'orotranslation/js/translator',
    'oroui/js/tools',
    **'./../optional-validation-handler',**
    'jquery.validate'
], function($, _, __, tools, validationHandler) {
```

**Comment by ignat-s** [comment]
The issue was fixed in this commit: https://github.com/orocrm/platform/commit/babbb5ceb6dc08f957b8c6f632aca6cfcb5d91b1#diff-af3b5c5a92a67974208f648cda10c5ae

@dgspurgin, the commit was ported to your version of "oro/platform" as well.
