### ISSUE TITLE
Loading workflow definititions fail when upgrading to 1.10.1

### ISSUE THREAD

**Issue by Richard87** [orocrm/platform#525]
Hi,

When running `php app/console oro:platform:update`, `Loading workflow definitions...` fails:

```
root@do-2:/home/crm/crm# php app/console oro:platform:update --env=prod --force
Process migrations...
  > Oro\Bundle\EntityExtendBundle\Migration\LoadEntityConfigStateMigration
  > Oro\Bundle\MigrationBundle\Migration\UpdateBundleVersionMigration
  > Oro\Bundle\EntityExtendBundle\Migration\RefreshExtendCacheMigration
  > Oro\Bundle\EntityConfigBundle\Migration\UpdateEntityConfigMigration
  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendConfigMigration
  > OroCRM\Bundle\ActivityContactBundle\Migration\ActivityContactMigration
  > Oro\Bundle\ActivityListBundle\Migration\ActivityListMigration
  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendIndicesMigration
  > Oro\Bundle\EntityConfigBundle\Migration\WarmUpEntityConfigCacheMigration
Loading permissions...
  > VIEW
  > CREATE
  > EDIT
  > DELETE
  > ASSIGN
  > CONFIGURE
Loading workflow definitions...
PHP Notice:  Undefined index: ref-one in /home/crm/crm/vendor/oro/platform/src/Oro/Bundle/ActionBundle/Model/AttributeGuesser.php on line 333
PHP Notice:  Undefined index: ref-one in /home/crm/crm/vendor/oro/platform/src/Oro/Bundle/ActionBundle/Model/AttributeGuesser.php on line 334
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Oro\Bundle\ActionBundle\Model\AttributeGuesser::formatResult() must be of the type array, null given, called in /home/crm/crm/vendor/oro/platform/src/Oro/Bundle/ActionBundle/Model/AttributeGuesser.php on line 334 and defined in /home/crm/crm/vendor/oro/platform/src/Oro/Bundle/ActionBundle/Model/AttributeGuesser.php:252
Stack trace:
#0 /home/crm/crm/vendor/oro/platform/src/Oro/Bundle/ActionBundle/Model/AttributeGuesser.php(334): Oro\Bundle\ActionBundle\Model\AttributeGuesser->formatResult('orocrm.sales.op...', NULL, NULL)
#1 /home/crm/crm/vendor/oro/platform/src/Oro/Bundle/ActionBundle/Model/AttributeGuesser.php(154): Oro\Bundle\ActionBundle\Model\AttributeGuesser->guessAttributeParametersScalarField(Object(Doctrine\ORM\Mapping\ClassMetadata), 'status')
#2 /home/crm/crm/vendor/oro/platform/src/Oro/Bundle/WorkflowBundle/Model/AttributeAssembler.php(106): Oro\Bundle\ActionBundle\Model\AttributeGuesser->guessAttributeParameters('OroCRM\\Bundle\\S...', 'opportunity.sta...') in /home/crm/crm/vendor/oro/platform/src/Oro/Bundle/ActionBundle/Model/AttributeGuesser.php on line 252


  [RuntimeException]
  The command terminated with an exit code: 255.


oro:platform:update [--force] [--skip-assets] [--symlink] [--force-debug] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--jms-job-id JMS-JOB-ID] [--disabled-listeners DISABLED-LISTENERS] [--] <command>
```

Any help would be greatly appreciated!

Richard

**Comment by Richard87** [comment]
Probably leftover bugs from when I failed to upgrade earlier :/ [https://github.com/orocrm/platform/issues/506](#506)

I followed the steps:

	php app/console --env=prod cache:clear  --no-debug
	php app/console --env=prod oro:migration:load --force
	php app/console --env=prod doctrine:schema:update --force
	php app/console --env=prod oro:entity-extend:update-config
	php app/console --env=prod oro:entity-extend:update-schema
	php app/console --env=prod oro:entity-extend:cache:clear
	php app/console  --env=prod oro:entity-config:update
	php app/console --env=prod cache:clear  --no-debug
	php app/console --env=prod oro:platform:update  --force

Bt failed again on the last step, when loading workflow definitions...

Since we don't use the workflow, can I disable that component somehow?

**Comment by mkudelya** [comment]
Hi @Richard87 

To disable workflow definitions you should deactivate all workflows (System -> Workflows) and comment all imports [here](https://github.com/orocrm/crm/blob/master/src/OroCRM/Bundle/SalesBundle/Resources/config/workflow.yml), [here](https://github.com/orocrm/OroCRMTaskBundle/blob/master/Resources/config/workflow.yml) and [here](https://github.com/orocrm/crm/blob/master/src/OroCRM/Bundle/MagentoBundle/Resources/config/workflow.yml).

**Comment by Richard87** [comment]
Hi @mkudelya , How can I deactivate all workflows when the system is not running?

**Comment by Richard87** [comment]
I deleted the content of `oro_workflow_definition` and it seems the foreign keys took care of deleting the correct relations? (hopefully!)

After commenting out the workflows as pointed above, I reran `oro:platform:update` and got a new error:

	root@do-2:/home/crm/crm# alias prod="php app/console --env=prod"
	root@do-2:/home/crm/crm# prod oro:platform:update  --force
	Process migrations...
	  > Oro\Bundle\EntityExtendBundle\Migration\LoadEntityConfigStateMigration
	  > Oro\Bundle\MigrationBundle\Migration\UpdateBundleVersionMigration
	  > Oro\Bundle\EntityExtendBundle\Migration\RefreshExtendCacheMigration
	  > Oro\Bundle\EntityConfigBundle\Migration\UpdateEntityConfigMigration
	  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendConfigMigration
	  > OroCRM\Bundle\ActivityContactBundle\Migration\ActivityContactMigration
	  > Oro\Bundle\ActivityListBundle\Migration\ActivityListMigration
	  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendIndicesMigration
	  > Oro\Bundle\EntityConfigBundle\Migration\WarmUpEntityConfigCacheMigration
	Loading permissions...
	  > VIEW
	  > CREATE
	  > EDIT
	  > DELETE
	  > ASSIGN
	  > CONFIGURE
	Loading workflow definitions...
	  > b2c_flow_abandoned_shopping_cart
	  > b2c_flow_order_follow_up
	[info] > process definition: "sync_email_flag_after_changed" - updated
	[info] > process definition: "schedule_integration" - updated
	[info] > process definition: "clear_user_email_origin_on_deactivation" - updated
	[info] > process definition: "clear_imap_email_folder_on_sync_enabled_change" - updated
	[info] > process definition: "analytics_channel_calculate_rfm" - updated
	[info] > process definition: "convert_mailbox_email_to_lead" - updated
	[info] > process definition: "magento_customer_creation" - updated
	[info] > process definition: "magento_customer_export" - updated
	[info] > process definition: "magento_customer_address_export" - updated
	[info] > process definition: "magento_analytics_customer_calculate" - updated
	[info] > process definition: "magento_analytics_customer_calculate_imported" - updated
	[info] > process definition: "magento_schedule_integration" - updated
	[info] > process definition: "convert_mailbox_email_to_case" - updated
	[info] Process definitions configuration updates are stored into database
	[info] >> process trigger: analytics_channel_calculate_rfm [update] - updated
	[info] >> process trigger: clear_imap_email_folder_on_sync_enabled_change [update] - updated
	[info] >> process trigger: clear_user_email_origin_on_deactivation [update] - updated
	[info] >> process trigger: magento_analytics_customer_calculate [update] - updated
	[info] >> process trigger: magento_analytics_customer_calculate_imported [create] - updated
	[info] >> process trigger: magento_customer_address_export [update] - updated
	[info] >> process trigger: magento_customer_creation [create] - updated
	[info] >> process trigger: magento_customer_export [update] - updated
	[info] >> process trigger: magento_schedule_integration [update] - updated
	[info] >> process trigger: schedule_integration [update] - updated
	[info] >> process trigger: schedule_integration [create] - updated
	[info] >> process trigger: sync_email_flag_after_changed [update] - updated
	[info] >> process triggers modifications stored in DB
	Loading "main" data fixtures ...
	  > loading Oro\Bundle\CalendarBundle\Migrations\Data\ORM\LoadAttendeeData


	  [Doctrine\Common\Persistence\Mapping\MappingException]
	  Class 'Extend\Entity\EV_Ce_Attendee_Status' does not exist


	oro:migration:data:load [--fixtures-type [FIXTURES-TYPE]] [--dry-run] [--bundles [BUNDLES]] [--exclude [EXCLUDE]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--jms-job-id JMS-JOB-ID] [--disabled-listeners DISABLED-LISTENERS] [--] <command>



	  [RuntimeException]
	  The command terminated with an exit code: 1.


	oro:platform:update [--force] [--skip-assets] [--symlink] [--force-debug] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--jms-job-id JMS-JOB-ID] [--disabled-listeners DISABLED-LISTENERS] [--] <command>

Any idea?

**Comment by mikeSimonson** [comment]
@mkudelya I also have this issue with the workflow component (running on php 5.6)

**Comment by mikeSimonson** [comment]
@mkudelya But in my case thoses steps fixed it.

```
php app/console --env=prod cache:clear  --no-debug
php app/console --env=prod oro:migration:load --force
php app/console --env=prod doctrine:schema:update --force
php app/console --env=prod oro:entity-extend:update-config
php app/console --env=prod oro:entity-extend:update-schema
php app/console --env=prod oro:entity-extend:cache:clear
php app/console  --env=prod oro:entity-config:update
php app/console --env=prod cache:clear  --no-debug
php app/console --env=prod oro:platform:update  --force
```
