### ISSUE TITLE
Google-Maps Integration - ApiKey

### ISSUE THREAD

**Issue by mathielen** [orocrm/platform#526]
Google Maps needs an ApiKey now: http://stackoverflow.com/a/37991723

Please make the apiKey property in https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/AddressBundle/Resources/public/js/mapservice/googlemaps.js configurable.

Thanks

**Comment by artml** [comment]
hi @mathielen 

thanks for heads up, we'll add this to our release scope

**Comment by sadortun** [comment]
Related to https://github.com/orocrm/platform/issues/381
