### ISSUE TITLE
Email template edit throws exception 1.10.4

### ISSUE THREAD

**Issue by LRotherfield** [orocrm/platform#535]
When trying to edit an email template in version 1.10.4 an exception is thrown because a new `EmailTemplateTransformer` is instantiated without any arguments but it requires a `SanitizeHTMLTransformer` object in it's constructor:

1. https://github.com/orocrm/platform/blob/1.10.4/src/Oro/Bundle/EmailBundle/Form/Type/EmailTemplateRichTextType.php#L19
2. https://github.com/orocrm/platform/blob/1.10.4/src/Oro/Bundle/EmailBundle/Form/DataTransformer/EmailTemplateTransformer.php#L21

I can see that this is fixed in master as the deprecated sanitize option is removed.  Are you planning to release a patch for this in 1.10.x?

**Comment by mkudelya** [comment]
Hi @LRotherfield 

Thank you for your report! Fix will be as soon as possible.

**Comment by LRotherfield** [comment]
It looks like this ticket is actually a duplicate of https://github.com/orocrm/platform/issues/532 and https://github.com/orocrm/crm/issues/218, sorry about that

**Comment by LRotherfield** [comment]
Thanks for the fix, all seems to be working in [1.10.5](https://github.com/orocrm/platform/tree/1.10.5)

**Comment by mkudelya** [comment]
@LRotherfield 

Thanks you too!
