### ISSUE TITLE
Email password is encrypted and base64 encoded but the database column doesn't have enough space

### ISSUE THREAD

**Issue by aabbbaa** [orocrm/platform#540]
Before an email password is saved, it's encrypted with AES-256-CBC and then base64 encoded. The resulting string doesn't fit in the corresponding database column because the column's length is 100 characters but the value can be longer than that. 

MySQL silently truncates the value. This in turn makes the IMAP sync feature to not function as it's unable to decrypt the password.

``` sql
CREATE TABLE oro_email_origin (
  ...
  imap_password varchar(100) DEFAULT NULL,
  ...
);
```

**Comment by rgrebenchuk** [comment]
@aabbbaa Thank you for reporting issue. We will fixe it in nearest release
