### ISSUE TITLE
Can we cache the EntityMaskBuilder instances

### ISSUE THREAD

**Issue by LRotherfield** [orocrm/platform#546]
I have been profiling one of our apps with xhprof and noticed that the following method is called many times and is quite expensive:
[Oro\Bundle\SecurityBundle\Acl\Extension\EntityMaskBuilder::preparePermissions](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/SecurityBundle/Acl/Extension/EntityMaskBuilder.php#L63)
I profiled the application on the page (full page refresh) `/email/emailtemplate/update/2` which is editing the email template (core functionality) `calendar_invitation_accepted` and below are my results:
![screen shot 2016-10-10 at 16 17 47](https://cloud.githubusercontent.com/assets/186184/19249779/2eebec5e-8f05-11e6-8976-bae68b622622.png)

Based on this and several other profiles on multiple custom and core routes I had a look at caching the EntityMaskBuilder instances and wondered if you could have a quick look and see if you think the following gist is valid.  As far as I can tell, only the property `mask` is actually updated so if the builder is cloned and reset I think there should be no issues:
https://gist.github.com/LRotherfield/9cfbefec1c1f64d78276812c80549945

Using this seems to benefit a lot but it may be that I am missing something and this kind of caching is not valid.  Here is my profiling post caching gist above:
![screen shot 2016-10-10 at 16 25 37](https://cloud.githubusercontent.com/assets/186184/19250132/c944e534-8f06-11e6-8b18-b99a33a527ea.png)

**Comment by LRotherfield** [comment]
I guess the other alternative would be to cache the map by extracting the methods `preparePermissions` and `prepareLevels` into a separate singleton service and injecting that into the `EntityMaskBuilder` instances?

**Comment by DimaSoroka** [comment]
@LRotherfield , team is going to work on the fix for this issue in the next few weeks, thanks for submitting it and all the details!

**Comment by LRotherfield** [comment]
Looks like this is fixed: https://github.com/orocrm/platform/blob/2.0/src/Oro/Bundle/SecurityBundle/Acl/Extension/EntityAclExtension.php#L195
https://github.com/orocrm/platform/blob/2.0/src/Oro/Bundle/SecurityBundle/Acl/Extension/EntityAclExtension.php#L655

Thanks for your hard work guys
