### ISSUE TITLE
select2-autocomplete-view.js attempting array push on undefined variable

### ISSUE THREAD

**Issue by dgspurgin** [orocrm/platform#549]
The following line can return undefined instead of an array:
https://github.com/orocrm/platform/blob/1.9/src/Oro/Bundle/FormBundle/Resources/public/js/app/views/select2-autocomplete-view.js#L11

Push on this line then fails:
https://github.com/orocrm/platform/blob/1.9/src/Oro/Bundle/FormBundle/Resources/public/js/app/views/select2-autocomplete-view.js#L13

Possible fix:
                var selectedData = [];
                if ($(this.$el).data() && $(this.$el).data().selectedData) {
                    selectedData = $(this.$el).data().selectedData;
                }

**Comment by Grygir** [comment]
Hello, @dgspurgin 

I see that this issue is already fixed in master and platform 1.10. But still can be reproduced in platform 1.9. I will apply the fix in to older version.

Thank you for report.

**Comment by dgspurgin** [comment]
Thank-you @Grygir ;P

**Comment by dgspurgin** [comment]
@Ignat fix will also need to be applied to AE forks too, right?

**Comment by ignat-s** [comment]
@dgspurgin, yes it will be ported later today.
