### ISSUE TITLE
Can't install platform

### ISSUE THREAD

**Issue by benyang2015** [orocrm/platform#552]
composer install error:out of memory size.
php.ini memory_limit:2048M

**Comment by mkudelya** [comment]
Hi @benyang2015 
Unfortunately the composer consumes a lot of memory, so the only way - to increase memory_limit.

**Comment by alex-barylski** [comment]
I have the PHP memory_limit set to explicit 10GB and -1 and I am still getting this error???

I have confirmed the correct php.ini is being loaded - but even tried installing from CLI:

`php -d memory_limit=-1 C:\ProgramData\ComposerSetup\bin\composer.phar install --prefer-dist --no-dev
`
`php -d memory_limit=5G C:\ProgramData\ComposerSetup\bin\composer.phar install --prefer-dist --no-dev`


```
composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Out of memory (allocated 1573650432) (tried to allocate 134217728 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220

Fatal error: Out of memory (allocated 1573650432) (tried to allocate 134217728 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220
```

Then

```
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 8388608 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/RuleSet.php on line 73

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 8388608 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/RuleSet.php on line 73

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
```

Any ideas? I am running Windows 10 with php.exe

I managed to get this to work running virtualbox/vagrant VM with only 512MB so I am not sure if its something with PHP and windows or WTF...

ANyway any input or alternatives greatly appreciated.

**Comment by sadortun** [comment]
Hi @alex-barylski  Had the same issue on windows. Ensure you have a  x64 php and apache installed, otherwise you wont be able to make it ! 

FYI, installing php7 will also solve the issue !

**Comment by alex-barylski** [comment]
@sadortun thanks for quick reply :)

I am probably running the x86 PHP version...darn it....I will try the 64NTS version. As for Apache - I definitely will not that installed...why would that be a requirement for composer?

**Comment by sadortun** [comment]
Well, 

1. The first issue https://github.com/composer/composer/issues/1898 is a composer issue, 
2. On top of that oro have a large dependency tree
3. PHP 5 x86 on windows doesnt seems like it can alocate more than **1.5GGb of RAM**. (http://stackoverflow.com/questions/639540/how-much-memory-can-a-32-bit-process-access-on-a-64-bit-operating-system   **minus** Apache RAM, **minus** PHP RAM

My tests using Apache x64 and PHP 5x  x64 did not end well,  but PHP7 works like a charm, there is also an easy **2X** 🎆    performance gain, and a **5X-10X** 🎆😀   "performance" gain when using XDebug !

**Comment by alex-barylski** [comment]
Running 64 didn't seem to make a difference...upgraded to php7 and it seems to be installing...

**Comment by sadortun** [comment]
@mkudelya  @artml 

Seems like a repeatable issue, maybe a note should be added in the docs to mentioned that PHP5 on windows doesnt work anymore. I saw this problem occuring for the first time a few months ago.

**Comment by sadortun** [comment]
FYI @alex-barylski  you are not the only one ! https://travis-ci.org/orocrm/crm/jobs/168959882#L171

**Comment by sergeyz** [comment]
We are going to refactor version constraints to x.x.* and that will decrease memory usage a little bit. Another way to decrease memory usage is to remove unstable deps (knp menu upgrade from 2.x-alpha to 2.x.stable)

**Comment by ste93cry** [comment]
As far as I understand the problem is that the `composer.json` of the platform does not specify any constraint for the Symfony version and this lead to a massive usage of RAM to compute the final constraints to be used for install. At least, this is what I noticed on my Windows machine with PHP 5.6 32bit

**Comment by sergeyz** [comment]
We accept symfony 2.8.* https://github.com/orocrm/platform/blob/master/composer.json#L25

**Comment by ste93cry** [comment]
Yes, you're right, I confused the `composer.json` of the platform with the one of the application (not the CRM, the standalone application). Anyway, for that case having the symfony constraint on the file solved my problem
