### ISSUE TITLE
Using oro_entity_changeset in a transition form

### ISSUE THREAD

**Issue by adamlundrigan** [orocrm/platform#556]
In my case ([some details on which are found here](https://www.orocrm.com/forums/topic/workflow-transition-form-with-custom-page-template)) I have a transition form which uses a datagrid and `oro_entity_changeset` to record some selections related to the transition and apply them as part of the actual transition.  

This all works very well, except in one case: failed transition form validation. In that case I run up against a bug in `ChangeEditableCellListener`: it's init method it captures a reference to the DOM element of the hidden form element it's bound to:

```
        initialize: function(options) {
            if (!_.has(options, 'selector')) {
                throw new Error('Parameter selector is not specified');
            }
            this.$selector = $(options.selector);
```

https://github.com/orocrm/platform/blob/40d95cbf7dadc6549a02da6eafd0ae1b64af7217/src/Oro/Bundle/DataGridBundle/Resources/public/js/datagrid/listener/change-editable-cell-listener.js#L28

This works fine as long as the form DOM doesn't change.  However, when a transition form is submitted and fails validation an entirely new form DOM is returned by the XHR and it's substituted into the page in place of the old form.  

Since `ChangeEditableCellListener` holds a direct DOM reference to the form element, changes made to the datagrid selections don't propagate into the transition form on subsequent attempts.

The simplest fix is to to update `ChangeEditableCellListener` to not hold a reference and instead query the DOM using the selector each time it needs to grab the hidden field:

``` diff
diff --git a/src/Oro/Bundle/DataGridBundle/Resources/public/js/datagrid/listener/change-editable-cell-listener.js b/src/Oro/Bundle/DataGridBundle/Resources/public/js/datagrid/listener/change-editable-cell-listener.js
index fa95204..bc98696 100644
--- a/src/Oro/Bundle/DataGridBundle/Resources/public/js/datagrid/listener/change-editable-cell-listener.js
+++ b/src/Oro/Bundle/DataGridBundle/Resources/public/js/datagrid/listener/change-editable-cell-listener.js
@@ -15,7 +15,7 @@ define([
      */
     ChangeEditableCellListener = AbstractGridChangeListener.extend({

-        /** @param {Object} */
+        /** @param string */
         $selector: null,

         /**
@@ -25,9 +25,9 @@ define([
             if (!_.has(options, 'selector')) {
                 throw new Error('Parameter selector is not specified');
             }
-            this.$selector = $(options.selector);
+            this.$selector = options.selector;

-            if (!this.$selector.length) {
+            if (!$(this.$selector).length) {
                 throw new Error('DOM element for selector not found');
             }

@@ -100,7 +100,7 @@ define([
          * @inheritDoc
          */
         _synchronizeState: function() {
-            this.$selector.val(JSON.stringify(this.get('changeset')));
+            $(this.$selector).val(JSON.stringify(this.get('changeset')));
         },

         /**
@@ -122,8 +122,9 @@ define([
          */
         _restoreState: function() {
             var changeset = {};
-            if (this.$selector.length) {
-                changeset = this._toObject(this.$selector.val());
+            var selector = $(this.$selector);
+            if (selector.length) {
+                changeset = this._toObject(selector.val());
                 this.set('changeset', changeset);
             }
             if (!_.isEmpty(changeset)) {
```

I can prepare a PR for this if it's an acceptable solution.

**Comment by artml** [comment]
@adamlundrigan yes, a PR will be most welcomed. Thank you!
