### ISSUE TITLE
Language update cause the language to be desactivated

### ISSUE THREAD

**Issue by sadortun** [orocrm/platform#560]
Hello Artem,

When a language update is done, the language  is disabled after the update.

1) 
![image](https://cloud.githubusercontent.com/assets/794449/19878631/b522a462-9fc1-11e6-9538-a611f9879553.png)

![image](https://cloud.githubusercontent.com/assets/794449/19878634/bd770b58-9fc1-11e6-948e-d68038516084.png)

2)  When the language update is completed, the UI display it was updated correctly.
![image](https://cloud.githubusercontent.com/assets/794449/19878649/dc0becaa-9fc1-11e6-8213-8ae3db7fa295.png)

3) But when refreshing the page,  the language is not avalaible, We need to re-select English, to be able to activate the language
![image](https://cloud.githubusercontent.com/assets/794449/19878667/13d55766-9fc2-11e6-92e8-4cb64a7080fd.png)

4) After the language is activated, it need to be re-selected manually.
![image](https://cloud.githubusercontent.com/assets/794449/19878686/4360bdb8-9fc2-11e6-995e-c39ada8e8991.png)

Thanks,
Samuel

**Comment by mbessolov** [comment]
It seems like an inconvenience that can be worked around by a user.
In 2.0 the language management UI is decoupled from System Configuration so there should be no problems like this one anymore.

**Comment by sadortun** [comment]
Ok, thanks.
