### ISSUE TITLE
When going to localapp.dev/app.php/installer Exception thrown. 

### ISSUE THREAD

**Issue by duffner** [orocrm/platform#561]
Steps to reproduce.  

Installation is followed by the following URL: https://github.com/orocrm/platform-application

System Environment,  Vagrant, Ubuntu, PHP7.0 or PHP5.6, MySQL 5.6 

1.) ```git clone https://github.com/orocrm/platform-application.git```
2.) ```composer global require "fxp/composer-asset-plugin:~1.2"``` Missing in Install instructions
3.) run ```composer install```
4.)  Go to localapp.dev/app.php/installer or CLI  ```php app/console oro:install --env prod```

After meeting all prerequistes - Click "Next"  and exception is thrown. 

```
( ! ) Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: There is no extension able to load the configuration for "monolog" (in /var/www/magehawk_oro/platform-application/app/config/config_prod.yml). Looked for namespace "monolog", found none in /var/www/magehawk_oro/platform-application/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php on line 399
( ! ) Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: There is no extension able to load the configuration for "monolog" (in /var/www/magehawk_oro/platform-application/app/config/config_prod.yml). Looked for namespace "monolog", found none in /var/www/magehawk_oro/platform-application/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php on line 399
Call Stack
#	Time	Memory	Function	Location
1	0.0000	368424	{main}( )	.../app.php:0
2	0.0004	652312	Symfony\Component\HttpKernel\Kernel->handle( )	.../app.php:22
3	0.0004	652312	Oro\Bundle\DistributionBundle\OroKernel->boot( )	.../bootstrap.php.cache:2534
4	0.0005	660184	Symfony\Component\HttpKernel\Kernel->boot( )	.../OroKernel.php:250
5	0.0006	662384	Oro\Bundle\DistributionBundle\OroKernel->initializeContainer( )	.../bootstrap.php.cache:2503
6	0.0007	664168	Symfony\Component\HttpKernel\Kernel->initializeContainer( )	.../OroKernel.php:288
7	0.0007	664880	Symfony\Component\HttpKernel\Kernel->buildContainer( )	.../bootstrap.php.cache:2724
8	0.0022	914616	AppKernel->registerContainerConfiguration( )	.../bootstrap.php.cache:2772
9	0.0022	914712	Symfony\Component\Config\Loader\DelegatingLoader->load( )	.../AppKernel.php:32
10	0.0022	914712	Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load( )	.../DelegatingLoader.php:45
11	0.0022	914712	Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadFile( )	.../YamlFileLoader.php:44
12	0.0031	925544	Symfony\Component\DependencyInjection\Loader\YamlFileLoader->validate( )	.../YamlFileLoader.php:369
```

**Comment by mkudelya** [comment]
Hi @duffner 

Did you use master branch during install ?

**Comment by duffner** [comment]
@mkudelya,  I used the master branch during the installation.     

Note: I did have success yesterday when I ran the CLI install differently from your instructions, however never could get the Web Install tool to work correctly.    My success in the CLI install was by running ```php app/console oro:install``` instead of ```php app/console oro:install --env prod```  as your instructions state. I'm not sure what the difference is there as I haven't looked yet.

**Comment by mkudelya** [comment]
Hi @duffner 

I suggest you use the latest stable release instead master. Please look at [1.10.8](https://github.com/orocrm/platform-application/tree/1.10.8) version, drop&create database, delete cache (app/cache/prod, app/cache/dev) and install application.

**Comment by duffner** [comment]
@mkudelya, moving forward what's the best way to know what the current latest stable release is?

**Comment by mkudelya** [comment]
The best way is:

- Go to [repository](https://github.com/orocrm/platform-application)
- Click on "Branch: master" button
- Find, latest at the moment branch 1.10 (previous was 1.9)
- Checkout it, "git checkout 1.10"

By the way comment about 'composer global required' [appeared](https://github.com/orocrm/platform-application)

**Comment by artml** [comment]
all questions appear to be answered so I'm closing this
