### ISSUE TITLE
BusinessUnit doesn't work 

### ISSUE THREAD

**Issue by thinh2010** [orocrm/platform#563]
Hi, I am using the dev-master of oro platform. I found an error when I tried to create a new user, I cannot pick the business unit. Could you please check

**Comment by artml** [comment]
Hi,

Do you have business units created?

**Comment by thinh2010** [comment]
I have Main business unit default. And I think the bug related to auto complete search. Event if I re-index the Business Unit Entity, it still cannot search in auto complete form field

**Comment by thinh2010** [comment]
Okie, I just run this command 
app/console oro:message-queue:consume -vvv --env=prod
and it solved my problem.
