### ISSUE TITLE
Error when sending email from system mailbox

### ISSUE THREAD

**Issue by stepansib** [orocrm/platform#571]
Good day.
I'm on OroPlatform 1.10.9.
I have 2 system mailboxes - Gmail and MSExchange, for example
When i try to compose and send email (through Exchange system mailbox) - the following error appears:

> Catchable Fatal Error: Argument 1 passed to Oro\Bundle\EmailBundle\Entity\EmailUser::addFolder() must be an instance of Oro\Bundle\EmailBundle\Entity\EmailFolder, boolean given, called in /domains/crm.nicholsons.gb.com/___oro/vendor/oro/platform/src/Oro/Bundle/EmailBundle/Mailer/Processor.php on line 474 and defined in /domains/crm.nicholsons.gb.com/___oro/vendor/oro/platform/src/Oro/Bundle/EmailBundle/Entity/EmailUser.php on line 180

But the email was sent.
When i compose and send email from Gmail system mailbox - everything is ok.
Both mailboxes fully set up to work with SMTP and IMAP.

Do you know - what is this and how to get rid of this error?

Update: i've found the way to reproduce this error and how to avoid it, please see my comment below

**Comment by stepansib** [comment]
I found a hackish solution.
To avoid this error - we need to add system mailbox email addresses to any user's email addresses.
Please fix the code. As i understand - system mailbox should not depends on users settings and email addresses

**Comment by mkudelya** [comment]
Hi @stepansib 

We will try to reproduce the issue.
Thank you

**Comment by artml** [comment]
@stepansib please check the latest master, we've merged the fix

**Comment by stepansib** [comment]
Thank you, will check in next couple days
