### ISSUE TITLE
DataGrid in popup: doesn't work manage filters dropdown and assigned dropdown

### ISSUE THREAD

**Issue by vodvud** [orocrm/platform#572]
For example in page http://demo.orocrm.com/desktop/account/update/42
Go to section "Contacts" and push the button ["Add"](http://storage4.static.itmages.com/i/16/1123/h_1479879264_8327998_4dff8db423.jpeg)
After opened popup, you can try to changing/scrolling ["Manage filters" dropdown](http://storage2.static.itmages.com/i/16/1123/h_1479887912_6863053_4c255ad94d.jpeg) or try to changing ["Assigned" dropdown](http://storage5.static.itmages.com/i/16/1123/h_1479879735_1763944_e270d27658.jpeg). 
**It isn't works.**

But, if I manually change `display: none;` to `display: block;` for dropdown, it is works.
http://storage6.static.itmages.com/i/16/1123/h_1479880517_4775840_a309ac79c6.jpeg

**Comment by mkudelya** [comment]
Hi Yaroslav

This is known issue, fix will be available in the next release.
Thank you

**Comment by artml** [comment]
@vodvud the fix is in the master. Thanks for reporting!

**Comment by vodvud** [comment]
Thank you.
