### ISSUE TITLE
Extract the ChainProcessor component from the platform

### ISSUE THREAD

**Issue by ste93cry** [orocrm/platform#577]
As talked with @DimaSoroka on Slack, I propose to extract the `ChainProcessor` component from the whole platform to its standalone repository. I quickly checked the code and to me it seems that it doesn't use any feature of other bundles/components, so it should be ready to work alone. I would like to use it in my project, so it would be cool if you agree on my proposal to do it as soon as possible.

**Comment by artml** [comment]
Can't promise the ASAP execution, so marking this as open for contribution for the time being.

**Comment by ste93cry** [comment]
Maybe I'm missing something, but as I said the component seems ready to be extracted. The only thing you have to do is to split the repository from the main one into its own one and change the `composer.json` of the platform to refer to it.

**Comment by artml** [comment]
@ste93cry yes, but atm we are fully busy with the release preparation. We'll get back to this after 2.0, in January or later.

**Comment by ste93cry** [comment]
The component has been split up, or at least there is its repository now. The only thing missing is that it's not published on Packagist yet. Could you do it?

**Comment by sergeyz** [comment]
@ste93cry done, https://packagist.org/packages/oro/chain-processor

**Comment by ste93cry** [comment]
Nice, the only missing thing would be to tag a release as stable

**Comment by sergeyz** [comment]
I think we should test it on Travis first

**Comment by sergeyz** [comment]
Yep, but that will not guarantee it works separately. Especially in case with dependencies on other platform bundles that are not standalone

**Comment by ste93cry** [comment]
The chain processor has no dependencies on other platform bundles/components, at least by looking at the `composer.json`. If you give a look at the repositories of the Symfony components, they are not tested by Travis (there is no `.travis.yml` file)

**Comment by mkudelya** [comment]
Can i close this issue?

**Comment by ste93cry** [comment]
As said below, tests are missing, but if you want to close anyway this issue feel free to do it

**Comment by mkudelya** [comment]
Thanks!

**Comment by ste93cry** [comment]
Any news on this? I know it's a pretty old issue, but the standalone repository is not even in sync anymore with this one and there could be people (like me) that relies on the component itself in projects not using the Oro Platform

**Comment by sergeyz** [comment]
Hi, @ste93cry, it was working for a while but was disabled during one of our CI migrations, sorry. I've restored that build. Will keep an eye on it, feel free to ping me if something wrong with splits
