### ISSUE TITLE
CRITICAL: Contact has no field or association named ac_contact_count

### ISSUE THREAD

**Issue by Avtonom** [orocrm/platform#582]
After add contact items.
Go to url "/contact"

>  request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("[Semantical Error] line 0, col 743 near 'ac_contact_count': Error: Class OroCRM\Bundle\ContactBundle\Entity\Contact has no field or association named ac_contact_count") in "/vendor/oro/platform/src/Oro/Bundle/UIBundle/Resources/views/actions/index.html.twig" at line 44." at /vendor/twig/twig/lib/Twig/Template.php line 182 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Semantical Error] line 0, col 743 near 'ac_contact_count': Error: Class OroCRM\\Bundle\\ContactBundle\\Entity\\Contact has no field or association named ac_contact_count\") in \"/vendor/oro/platform/src/Oro/Bundle/UIBundle/Resources/views/
> actions/index.html.twig\" at line 44. at /home/panel/public_html/vendor/twig/twig/lib/Twig/Template.php:182, Doctrine\\ORM\\Query
> \\QueryException(code: 0): [Semantical Error] line 0, col 743 near 'ac_contact_count': Error: Class OroCRM\\Bundle\\ContactBundle\\Entity\\Contact has no field or association named ac_contact_count at /vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT c.id, c.firstName, c.lastName, c.createdAt
> , c.updatedAt, c.fax, c.skype, c.twitter, c.facebook, c.googlePlus, c.linkedIn, c.birthday, c.gender, picture.originalFilename as pictureFilename, contactSource.name as source, email.email, email.id as emailId, phone.phone, phone.id as phoneId, CONCAT(CASE WHEN address.regionText IS NOT NULL THEN address.regionText ELSE region.name END, '') as regionLabel, country.name as countryName,
>  address.postalCode as addressPostalCode, address.city as addressCity, address.street as addressStreet, CONCAT_WS(' ', o.firstName, o.lastName) as ownerName, CONCAT_WS(' ', assignedTo.firstName, assignedTo.lastName) as assignedName, CONCAT_WS(' ', reportsTo.firstName, reportsTo.lastName) as reportsName, c.ac_contact_count as timesContacted, c.ac_contact_count_in as timesContactedIn, c
> .ac_contact_count_out as timesContactedOut, c.ac_last_contact_date as lastContactedDate, c.ac_last_contact_date_in as lastContactedDateIn, c.ac_last_contact_date_out as lastContactedDateOut, DATE_DIFF(CURRENT_DATE(), c.ac_last_contact_date) as daysSinceLastContact FROM OroCRM\\Bundle\\ContactBundle\\Entity\\Contact c LEFT JOIN c.addresses address WITH address.primary = true LEFT JOIN c.emails email WITH email.primary = true LEFT JOIN c.phones phone WITH phone.primary = true LEFT JOIN c.source contactSource LEFT JOIN address.country country LEFT JOIN address.region region LEFT JOIN c.owner o LEFT JOIN c.assignedTo assignedTo LEFT JOIN c.r
> eportsTo reportsTo LEFT JOIN c.picture picture ORDER BY c.lastName ASC, c.firstName ASC at /vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []

**Comment by mkudelya** [comment]
Hi @Avtonom

I have some questions. Which version of orocrm are you using ? Is it brand new install or you ever run platform update ? Try to delete your /app/cache/[dev and prod] directories and reload your contact page. After that app/cache/[env_directory]/oro_entities/Extend/Entity/EX_OroCRMContactBundle_Contact.php should contains ac_contact_count property.

**Comment by Avtonom** [comment]
@mkudelya 
this new install. I installed yesterday. version 1.10

After delete your /app/cache/[dev and prod]
Log:
`ERROR: A plural alias for "OroCRM\Bundle\CaseBundle\Entity\CasePriority" entity not found. {"exception":"[object] (Oro\\Bundle\\EntityBundle\\Exception\\EntityAliasNotFoundException(code: 0): A plural alias for \"OroCRM\\Bundle\\CaseBundle\\Entity\\CasePriority\" entity not found. at /vendor/oro/platform/src/Oro/Bundle/EntityBundle/ORM/EntityAliasResolver.php:97)"} `

In console:
$php app/console cache:clear --env=prod

` The target-entity OroEntityProxy\OroEmailBundle\EmailAddressProxy cannot be found in 'Oro\Bundle\EmailBundle\Entity\EmailRecipient#emailAddress'`

**Comment by mkudelya** [comment]
Try to reinstall your application, probably you had some errors during installation. Before that make sure that cache directories are empty and you have clean database.

**Comment by Avtonom** [comment]
That helped. Initially, when the database installation script had to miss due to timeout
