### ISSUE TITLE
IMAP sync failed due to deadlock

### ISSUE THREAD

**Issue by alsma** [orocrm/platform#583]
Hi!

We have CRM instance v1.10.1 and sometimes users complaining about long delay in email appearence. I'm investigating this and found in logs that from time to time following error happens(see error message in the end).
Probably this could lead to such delays, because according to [this](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/EmailBundle/Sync/AbstractEmailSynchronizer.php#L463) comment, sync for failed origins will be postponed for 30 mins.

Also what I noticed is that there is no DB locks neither [here](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/EmailBundle/Sync/AbstractEmailSynchronizer.php#L467) no [there](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/EmailBundle/Sync/AbstractEmailSynchronizer.php#L391), so I suspect this could cause race conditions between concurent jobs, and in that case few jobs could syncronize the same origin... Probably "Double-checked locking" could be useful there.

```
The synchronization failed. Error: An exception occurred while executing 'UPDATE orocrm_contact SET ac_contact_count = ?, ac_contact_count_in = ?, ac_contact_count_out = ?, updatedAt = ?, updated_by_user_id = ? WHERE id = ?' with params [3690, 1887, 1803, "2016-12-06 12:44:50", null, 1822]:

SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
The synchronization failed. Error: An exception occurred while executing 'UPDATE orocrm_contact SET ac_contact_count = ?, ac_contact_count_in = ?, ac_contact_count_out = ?, updatedAt = ?, updated_by_user_id = ? WHERE id = ?' with params [3690, 1887, 1803, "2016-12-06 12:44:50", null, 1822]:

SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
```

Another  error I'm facing is the next one (49 times during today). IMAP is hosted on "gmail for business"
```
PHP Warning:  fwrite(): SSL operation failed with code 1. OpenSSL Error messages:
error:140D00CF:SSL routines:SSL_write:protocol is shutdown in /PATH/vendor/zendframework/zend-mail/src/Protocol/Imap.php on line 336
PHP Fatal error:  Uncaught exception 'Oro\Bundle\ImapBundle\Exception\SocketTimeoutException' with message 'cannot read - connection closed?' in /PATH/vendor/oro/platform/src/Oro/Bundle/ImapBundle/Mail/Protocol/Imap.php:116
Stack trace:
#0 /PATH/vendor/zendframework/zend-mail/src/Protocol/Imap.php(149): Oro\Bundle\ImapBundle\Mail\Protocol\Imap->_nextLine()
#1 /PATH/vendor/zendframework/zend-mail/src/Protocol/Imap.php(265): Zend\Mail\Protocol\Imap->_nextTaggedLine(NULL)
#2 /PATH/vendor/zendframework/zend-mail/src/Protocol/Imap.php(288): Zend\Mail\Protocol\Imap->readLine(NULL, 'TAG156', true)
#3 /PATH/vendor/zendframework/zend-mail/src/Protocol/Imap.php(353): Zend\Mail\Protocol\Imap->readResponse('TAG156', true)
#4 /PATH/vendor/zendframework/zend-mail/src/Protocol/Imap.php(423): Zend\Mail\Protocol\Imap->requestAndResponse('LOGOUT', Array, true)
#5 /PATH/vendor/oro/platform/src/Oro/Bundle/ImapBundle/Mail/Protocol/Imap.php on line 116
```

**Comment by mkudelya** [comment]
Hi @alsma 

As i understood the main problem to reduce time waiting next retry. In this case you can for example override findOriginToSync function with new value of $timeShift. I have created bug according to this issue.

**Comment by artml** [comment]
@alsma have you tried the 2.0 version with RabbitMQ? Perhaps it might have fixed the problem with interlocking jobs just by removing the root cause.

**Comment by mkudelya** [comment]
Hi @alsma 

Since version 1.10.1, we have fixed many issues related to working with emails. If you haven't updated to version 2.0 yet, you could try switching to the latest 1.10 tag and check the errors again.

Also, could you please let me know:

- what version of mysql and php you use,
- how many email origins you have,
- whether you sync emails via `app/console oro:cron` command and how often this command runs,
- whether you noticed if multiple 'oro: cron: imap-sync' jobs were running

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.

**Comment by sreekuttan-m-achari** [comment]
we were able to solve the imap read lock issue by introducing a file based locking  method in the email processing for dimantedesk ticketing application.. which is using the same libraries for its purposes.. 

This will help while the cronjobs try to start a new email process while the existing one is still running. 

Hope it helps .. :-) 

` protected function execute(InputInterface $input, OutputInterface $output) {

		//$flagFile = 'cronFlg.flg';

		$flagFile = dirname(__FILE__).'/cronFlg.flg';

		$output->writeln("Flag-File: ".$flagFile." :  ".date("Y-m-d h:i:sa"));

		if (!file_exists($flagFile)) {
			if (file_put_contents($flagFile, "COMPLETED")) {
				$output->writeln("Flag-File Created : ".date("Y-m-d h:i:sa"));
			} else {
				$output->writeln("Error! Unable to create Flag-File Please check folder/file permissions: ".date("Y-m-d h:i:sa"));
			}
		} else {

			$flg = file_get_contents($flagFile);

			if ($flg == 'COMPLETED') {
				file_put_contents($flagFile, "START");

				$output->writeln("Start General Email Processing : ".date("Y-m-d h:i:sa"));
				$this->getContainer()->get('diamante.email_processing.service')->process();
				$output->writeln("General Email Processing Done : ".date("Y-m-d h:i:sa"));

				file_put_contents($flagFile, "COMPLETED");
			} else {
				$output->writeln("Processing Emails... : ".date("Y-m-d h:i:sa"));
			}
		}

	} `
