### ISSUE TITLE
Email folder "non selectable" causes removing of all emails from the folder

### ISSUE THREAD

**Issue by alsma** [orocrm/platform#590]
Hi.

Today I've received complains from a few our users that they don't see all their emails in CRM.
I've checked DB and did not find any records with their user ids in `oro_email`, `oro_email_user`. 
After investigation I've found jobs that contains following output 10 time in a row
```
Found "***@gmail.com (imap.gmail.com)" email origin. Id: 3.
Get folders enabled for sync...
Got 6 folder(s).
The folder "Customer" cannot be selected and was skipped.
The folder "INBOX" cannot be selected and was skipped.
The folder "[Gmail]/Bin" cannot be selected and was skipped.
The folder "[Gmail]/Important" cannot be selected and was skipped.
The folder "[Gmail]/Sent Mail" cannot be selected and was skipped.
The folder "[Gmail]/Starred" cannot be selected and was skipped.
```

And error output contains 

```
PHP Notice:  iconv(): Wrong charset, conversion from `UTF-8' to `UTF7-IMAP//IGNORE' is not allowed in /var/www/vendor/symfony/polyfill-mbstring/Mbstring.php on line 113
PHP Notice:  Uninitialized string offset: 0 in /var/www/vendor/zendframework/zend-mail/src/Protocol/Imap.php on line 186
PHP Notice:  Uninitialized string offset: 0 in /var/www/vendor/zendframework/zend-mail/src/Protocol/Imap.php on line 191
PHP Notice:  Uninitialized string offset: 0 in /var/www/vendor/zendframework/zend-mail/src/Protocol/Imap.php on line 198
```

After that I enabled sync for that folders again and it started to sync well.
So I have following questions:
1) Have you any idea why this could happened ? 
2) Is it desired behavior to remove all emails from folders that were disabled due to technical issues ?

**Comment by mkudelya** [comment]
Hi @alsma 

Try to install mbstring php extension. Hope it helps.

**Comment by alsma** [comment]
WHAT!? 👎

**Comment by alsma** [comment]
Hi @mkudelya 

From my POV the main issue is that emails were removed, not the error output itself.

**Comment by mkudelya** [comment]
Hi @alsma 

As i understood you have following STR:

- User has emails
- Sometimes errors has occurred
- When folder can't sync a few times it becomes unchecked.
- When folder is unchecked, sync script removing emails in this folder.

I saw similar issue, therefore i ask you about mbstring. Can you tell me, is it installed or not?

**Comment by mkudelya** [comment]
I’m closing this issue as we have not received feedback from you. Feel free open it if you have any question.
