### ISSUE TITLE
workflow steps and transition buttons are not translated in the UI

### ISSUE THREAD

**Issue by markusrothenbacher** [orocrm/platform#591]
The twigs are simply missing trans statements

Step Translation is missong here:
vendor/oro/platform/src/Oro/Bundle/WorkflowBundle/Resources/views/Widget/widget/steps.html.twig: line 5-6

Buttons I guess here:
vendor/oro/platform/src/Oro/Bundle/WorkflowBundle/Resources/views/macros.html.twig: line 50, 59, maybe line 110,114 also

**Comment by mkudelya** [comment]
Hi @markusrothenbacher 

Thank you! Improvement has been created.

**Comment by mbessolov** [comment]
@markusrothenbacher Ability to translate workflow names, step names, transition names and transition warning messages is introduced for ver. 2.0.
It cannot be introduced into previous releases in a backwards compatible manner. Just making use of the translator in the templates you mentioned (as well as in other places) results in other side effects.
