### ISSUE TITLE
Roadmap second version

### ISSUE THREAD

**Issue by tadcka** [orocrm/platform#592]
When planned release second version?

**Comment by sadortun** [comment]
` Due by December 31, 2016`

https://github.com/orocrm/platform/milestone/2

**Comment by tadcka** [comment]
Cool :)

**Comment by artml** [comment]
@tadcka by the end of the year, unless major problems will happen. We hope they won't :)

**Comment by sadortun** [comment]
@artml I think 2016 have been long enough as it is :) let's hope there is no more major problems :)  thanks!
