### ISSUE TITLE
add relation between ORO entity and a mapped super class child

### ISSUE THREAD

**Issue by JacerOmri** [orocrm/platform#595]
Hello,

I was trying to add a many to one relationship between Business Unit entity and My own entity (Provider). That catch here is that Provider extends a single table mapped super class called Contactable.

The code I wrote in a migration class is the following:
```
$this->extendExtension->addManyToOneRelation(
            $schema,
            'oro_business_unit',
            'related_provider',
            'contactable',
            'name',
            ['extend' => ['owner' => ExtendScope::OWNER_CUSTOM]]
```

But obviously, as i have to specify a table name and not an entity name, I have no way to specify `target_entity` here (i tried adding it to the options array after `extend`).

The issue here is that I have no controle over the entity targeted here. Is there a way to do this?

Thank you.

**Comment by mkudelya** [comment]
Hi @JacerOmri 

I don't really understand, why do not you just put on fourth parameter table name of your child entity with annotations like this?

/**
 ** @ORM\Entity
 ** @ORM\Table(name="child_table_name")
 ** @Config()
 */

**Comment by mkudelya** [comment]
Can you give me, please, some code of your entities, for better understanding ?

**Comment by mkudelya** [comment]
I’m closing this issue as we have not received feedback from you. Feel free open it if you have any question.
