### ISSUE TITLE
Magento Integration - newline characters in blank Customer fields

### ISSUE THREAD

**Issue by MikeOtown** [orocrm/platform#606]
In Oro\Bundle\IntegrationBundle\Provider\SoapClient->__doRequest(), the call to oroCustomerList with PHP's SoapClient is returning "\n" newline sequences inside blank fields.  See below for a sample response... (newlines show as a space here, but in phpStorm they show as \n)

`<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:Magento">
<SOAP-ENV:Body>
<ns1:oroCustomerListResponseParam>
<result>
<complexObjectArray>
<customer_id>2546</customer_id>
<created_at>2017-01-04 16:53:31</created_at>
<updated_at>2017-01-09 15:22:51</updated_at>
<increment_id>
</increment_id>
<store_id>0</store_id>
<website_id>1</website_id>
<created_in>Admin</created_in>
<email>xxx</email>
<firstname>Michael</firstname>
<middlename>
</middlename>
<lastname>Wasson</lastname>
<group_id>1</group_id>
<prefix>
</prefix>
<suffix>
</suffix>
<dob>2012-09-02 00:00:00</dob>
<taxvat>
</taxvat>
<confirmation>false</confirmation>
<password_hash>xxx</password_hash>
<gender>
</gender>
<addresses/>
</complexObjectArray>
</result>
</ns1:oroCustomerListResponseParam>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

SoapUI tool doesn't return these newlines.

The newline causes an issue later when the code attempts to parse Date fields (like BirthDate).

There is already the line:
`// Remove all non printable characters except whitespace characters
$response = preg_replace('/[^[:print:][:space:]]/u', '', $response);`

after the call, but that doesn't remove newline characters.  Is it possible to add the removing of newlines?

**Comment by mkudelya** [comment]
Hi @MikeOtown 

I have tried sync magento on orocrm 1.10.12, magento 1.9.2.4, oro bridge 1.2.8, php 5.6.29 and i retrieved the following response without empty fields:

`
<ns1:oroCustomerListResponse>
<result SOAP-ENC:arrayType="ns1:oroCustomerEntity[2]" xsi:type="ns1:oroCustomerEntityArray">...
<item xsi:type="ns1:oroCustomerEntity">
<customer_id xsi:type="xsd:int">152</customer_id>
<created_at xsi:type="xsd:string">2017-01-10 15:30:34</created_at>
<updated_at xsi:type="xsd:string">2017-01-10 15:30:34</updated_at>
<store_id xsi:type="xsd:int">0</store_id>
<website_id xsi:type="xsd:int">0</website_id>
<created_in xsi:type="xsd:string">Admin</created_in>
<email xsi:type="xsd:string">test@gmail.com</email>
<firstname xsi:type="xsd:string">test</firstname>
<lastname xsi:type="xsd:string">test</lastname>
<group_id xsi:type="xsd:int">1</group_id>
<dob xsi:type="xsd:string">2016-04-05 00:00:00</dob>
<password_hash xsi:type="xsd:string">4686e74c8572a86a81fe1cefab521e35:wdph38RyCb1cBxcSmnyeROSY9wnHIGJR</password_hash>
<addresses SOAP-ENC:arrayType="ns1:customerAddressEntityItem[0]" xsi:type="ns1:customerAddressEntityArray"/>
</item>
</result>
</ns1:oroCustomerListResponse>`

I'm using integration sync command

`oro:cron:integration:sync -vvv --integration-id=[number]`

Please tell me which version of magento, bridge, php are you using ?

This function don't remove new lines

`preg_replace('/[^[:print:][:space:]]/u', '', $response);`

but this simple function yes:

`str_replace("\n", '', $string);`

**Comment by MikeOtown** [comment]
Hi - I'm running on Windows, not sure if that matters.  See also:

[http://stackoverflow.com/questions/41571219/newline-carriage-return-returned-in-blank-fields](url)

You don't have any blank fields - what if you delete that Customer's Date of Birth so that is blank?

OroCRM Enterprise v1.12, Magento CE v1.9.3.1, Oro Bridge (latest - not sure how to tell version number), php 5.6.24

oro:magento:initial:sync --integration-id=1 --skip-dictionary -vvv

**Comment by mkudelya** [comment]
> You don't have any blank fields - what if you delete that Customer's Date of Birth so that is blank?

If i don't enter customer's birth, <dob> tag won't be appear in xml

**Comment by mkudelya** [comment]
Are you using 
http://yourserver.com/api/soap?wsdl
or 
http://yourserver.com/api/v2_soap?wsdl
?

**Comment by MikeOtown** [comment]
/index.php/api/v2_soap/?wsdl=1

For some reason, our Blank fields are appearing in the XML returned from oroCustomerList.

For example:

<increment_id></increment_id>
<prefix></prefix>
<suffix></suffix>
<taxvat></taxvat>
<gender></gender>
<addresses/>

**Comment by mkudelya** [comment]
Are you using brand new magento installation ? (without any customization) If no, will you have similar problems with new magento ?

**Comment by MikeOtown** [comment]
This problem has fixed itself somehow.
