### ISSUE TITLE
'anon.' user cause exception in event listener

### ISSUE THREAD

**Issue by sadortun** [orocrm/platform#624]
Hi, when  the securityToken contain an annonymous user, and a persist is done, the following exception is thrown:
>>>
Fatal error: Uncaught Error: Call to a member function getOwner() on string in /var/www/orocrm/vendor/oro/platform/src/Oro/Bundle/OrganizationBundle/EventListener/RecordOwnerDataListener.php:114 Stack trace: #0 
>>>

I am not sure what is the extent of usage of this method, but here is a suggestion: 

https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/OrganizationBundle/EventListener/RecordOwnerDataListener.php#L114
```php
// original code
// $user may === 'annon.'
            $owner = null;
            if ($user instanceof User) {
                $owner = $user;
            } elseif ($user->getOwner() instanceof User) {
                $owner = $user->getOwner();
            }
```
```php
// suggested update 
            if ($user instanceof User) {
                $owner = $user;
            } elseif (is_object($user) && method_exists($user, 'getOwner') && $user->getOwner() instanceof User) {
                $owner = $user->getOwner();
            }
```

**Comment by mkudelya** [comment]
Hi @sadortun 

How i can reproduce the issue ?

**Comment by sadortun** [comment]
This should the trick 

```
// user = anonymous
 $c = new Contact ();
$em->persost ($c);
$em->flush ();
```

**Comment by mkudelya** [comment]
Hi

I have tried to emulate anonymous user by setting this code to [login](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/UserBundle/Controller/SecurityController.php#L19) action, but got:

```
Class '' does not exist
in vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php at line 96
```

    $em = $this->getDoctrine()->getManager();
    $c = new Contact();
    $em->persist($c);
    $em->flush();

Can you please provide more detail STR ?

**Comment by mkudelya** [comment]
Also i would like to know, which use-case are you using when you want to create Contact inside anonymous user ? (if not difficult)

**Comment by sadortun** [comment]
We had this issue when manipulating entities from a Command.

**Comment by mkudelya** [comment]
I put this code into [oro:cron:imap-sync](https://github.com/orocrm/platform/blob/1.10/src/Oro/Bundle/ImapBundle/Command/Cron/EmailSyncCommand.php#L114) command and it has produced an empty contact record.

    $em = $this->getContainer()->get('doctrine')->getManager();
    $c = new Contact();
    $em->persist($c);
    $em->flush();
    exit;

<img width="822" alt="screen shot 2017-03-09 at 16 28 37" src="https://cloud.githubusercontent.com/assets/3332593/23754434/a08bd468-04e5-11e7-86f2-d1d907cd700a.png">

Could you please tell me which version of OroCRM you use ?

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
