### ISSUE TITLE
Syntax error in EmailBundle/Validator/Constraints/MailboxOrigin.php

### ISSUE THREAD

**Issue by ianfp** [orocrm/platform#625]
I just upgraded from 1.10.3 to 1.10.13 and now I'm getting this error:

> Parse error: syntax error, unexpected '.', expecting ',' or ';' in /home/ianfp/projects/orocrm/vendor/oro/platform/src/Oro/Bundle/EmailBundle/Validator/Constraints/MailboxOrigin.php on line 11

The problem is that an expression (rather than a constant) is used to initialize the `$message` property; using an expression is not supported until PHP 5.6, but I'm still on 5.5, as is the oro platform `composer.json`.

**Comment by mkudelya** [comment]
Hi

This bug will be fixed in the next 1.10 release.
Thank you!
