### ISSUE TITLE
Misconfigured conditions: "True" (oro_action.expression.true) and "False" (oro_action.expression.false)

### ISSUE THREAD

**Issue by cawolf** [orocrm/platform#631]
Hey, 

we are currently upgrading to 1.10 and our smoke test found some misconfigurations in the `Oro/Bundle/ActionBundle/Resources/config/conditions.yml`:

    oro_action.expression.true:
        class: Oro\Component\ConfigExpression\Condition\True
        tags:
            - { name: oro_action.condition, alias: "true" }

    oro_action.expression.false:
        class: Oro\Component\ConfigExpression\Condition\False
        tags:
            - { name: oro_action.condition, alias: "false" }

Both classes are non-existent, they were renamed to `TrueCondition` and `FalseCondition`.

We are now overwriting the definitions, but it would be great if you could fix this issue in an upcoming release. Thanks in advance,

best regards,
Christian

**Comment by mkudelya** [comment]
Hi @cawolf 

The issue will be fixed in the next 1.10 release. 2.0 version doesn't contain this misconfigurations.
Thank you!
