### ISSUE TITLE
Orphaned definition of "oro_calendar.exception.form.type" in Oro/Bundle/CalendarBundle

### ISSUE THREAD

**Issue by cawolf** [orocrm/platform#633]
Hey,

we are currently upgrading to 1.10 and our smoke test found a misconfiguration in the `Oro/Bundle/CalendarBundle/Resources/config/form.yml`:

    oro_calendar.exception.form.type.class:                        Oro\Bundle\CalendarBundle\Form\Type\ExceptionFormType

    # [...]

    oro_calendar.exception.form.type:
        class: '%oro_calendar.exception.form.type.class%'
        tags:
            - { name: form.type, alias: oro_calendar_event_exception }

The class `Oro\Bundle\CalendarBundle\Form\Type\ExceptionFormType` was obviously removed, but this definition still refers to it. It would be great if you could fix this issue in an upcoming release. Thanks in advance,

best regards,
Christian

**Comment by mkudelya** [comment]
Hi @cawolf 

This service will be removed in the next 1.10 release. I'm closing this issue.
Thank you!
