### ISSUE TITLE
unable to install oro-platform

### ISSUE THREAD

**Issue by videni** [orocrm/platform#639]
app/console oro:install --env=dev

```
Loading workflow definitions...

  [Oro\Component\Action\Exception\AssemblerException]
  Option "type" is required

[RuntimeException]
  The command '/usr/local/Cellar/php70/7.0.14_7/bin/php' 'app/console' 'oro:workflow:definiti
  ons:load' '--no-debug' terminated with an exit code: 1.
```

**Comment by mkudelya** [comment]
Hi @videni

Thank you for your comment! 
Here is an [issue](https://github.com/orocommerce/orocommerce/issues/21) similar to yours. 
I am closing your issue for now but feel free to reopen it if you have any more questions.
