### ISSUE TITLE
Creating new campaign start/end date input value error

### ISSUE THREAD

**Issue by gabrieldosanjosbr** [orocrm/platform#644]
I installed OroCRM on Ubuntu but when creating new campaign, after selecting the start/end date in calendar the input tells that these values are wrong (e.g. 14 14 feb 14 2017).
Also it doesn't show input time to pick :/
Thx!!

**Comment by mkudelya** [comment]
Hi @gabrieldosanjosbr 

I have tested your use case but I found no issues with start/end fields. (I am using versions 1.10.16 and 2.0.1) Could you please show me a screenshot? Also i want to know which version of OroCRM do you use ? At the moment start/end fields carry more informative function, but we have plans to improve their.

**Comment by gabrieldosanjosbr** [comment]
Idk the error but i tested again on amazon ec2 and its working :S
