### ISSUE TITLE
How to remove custom relation with core bundle

### ISSUE THREAD

**Issue by ajeetvarma** [orocrm/platform#648]
I have mapped a custom entity Asset with Oro's Contact entity by migration -

      `$this->extendExtension->addManyToManyRelation(
            $schema,
            'hotelivate_asset',
            'contacts', 
            'orocrm_contact',
            ['first_name'], 
            ['first_name'], 
            ['first_name'], 
            ['extend' => ['owner' => ExtendScope::OWNER_CUSTOM]]
        );
        $this->extendExtension->addManyToManyInverseRelation(
            $schema,
            'hotelivate_asset',
            'contacts',
            'orocrm_contact',
            'assets',
            ['name'], 
            ['description'], 
            ['name'], 
            ['extend' => ['owner' => ExtendScope::OWNER_CUSTOM]]
        );`

Now i want to remove previous mapping and reverse this many to many association relation . just like this .
    
       `$this->extendExtension->addManyToManyRelation(
            $schema,
            'orocrm_contact', 
            'assets', 
            'hotelivate_asset',
            ['name'],
            ['description'], 
            ['name'], 
            ['extend' => ['owner' => ExtendScope::OWNER_CUSTOM]]
        );
        $this->extendExtension->addManyToManyInverseRelation(
            $schema,
            'orocrm_contact', 
            'assets',
            'hotelivate_asset',
            'contacts',
            ['first_name'], 
            ['first_name'], 
            ['first_name'], 
            ['extend' => ['owner' => ExtendScope::OWNER_CUSTOM]]
        );`

When i tried a extra migration load after the last script then i found error

> Property "contacts" in "MyFolder\Bundle\AssetBundle\Entity\Asset" was a  
  lready declared, but it must be declared only once

I do't know how to remove this error. Even i remove cache and delete join table created from first script but same error is come .
Please help me to solve this error .

Thanks in Advance ..

**Comment by mkudelya** [comment]
Hi @ajeetvarma 

At the moment there is no way to add the same column names. I suggest that you either rename them or use [a similar guide](https://www.orocrm.com/forums/topic/drop-one-to-many-relation-attachementextentsion#post-32768) to remove relation fields and clear config.

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
