### ISSUE TITLE
Import from CLI always run in validation mode

### ISSUE THREAD

**Issue by scapital** [orocrm/platform#650]
["hasOption" will search](https://github.com/orocrm/platform/blob/2.0/src/Oro/Bundle/ImportExportBundle/Command/ImportCommand.php#L66) option in InputDefinition, so, it is always exist and import_validation will run always instead of import

**Comment by mkudelya** [comment]
Hi @scapital 

Thanks for pointing that out! This issue has been fixed in the latest master. Please, feel free to reopen it if you have any questions.
