### ISSUE TITLE
Wrong argument list during call OroBundleImportExportBundleHandlerCliImportHandler::handleImport

### ISSUE THREAD

**Issue by scapital** [orocrm/platform#651]
["handleImport"](https://github.com/orocrm/platform/blob/2.0/src/Oro/Bundle/ImportExportBundle/Async/Import/CliImportMessageProcessor.php#L90-L96) takes 3 arguments and 3-st argument should be "array", so, I always get this error in log
An error occurred while running command "'oro:message-queue:consume'". Type error: Argument 3 passed to OroBundleImportExportBundleHandlerCliImportHandler_000000003fe018b600000000439b0f042acfbf534e0272cedb4b58f52ecb1216::handleImport() must be of the type array, null given, called in vendor/oro/platform/src/Oro/Bundle/ImportExportBundle/Async/Import/CliImportMessageProcessor.php on line 95 {"exit_code":0,"arguments":
{"command":"oro:message-queue:consume"}

**Comment by mkudelya** [comment]
Hi @scapital 

I saw that import processor has been refactored on the master branch. These changes should be available in the public repo soon. Please, feel free to reopen it if you have any questions.
