### ISSUE TITLE
Wrong summary message in import from CLI

### ISSUE THREAD

**Issue by scapital** [orocrm/platform#652]
[$result['counts'] and $result['errors']](https://github.com/orocrm/platform/blob/2.0/src/Oro/Bundle/ImportExportBundle/Async/Import/CliImportMessageProcessor.php#L98-L105) it is arrays, so, $summary always is FALSE instead of message

**Comment by mkudelya** [comment]
Hi @scapital 

This code has also been refactored.
Thank you!
