### ISSUE TITLE
[API Bundle] - using Form type, registered as a service for create and update actions

### ISSUE THREAD

**Issue by mechpave** [orocrm/platform#654]
Hello,
ORO JSON API documentation states that in `api.yml` configuration it is possible to use a form type for create and update actions.
It works fine if I provide FQCN for the form type, but i would like to use a form type registered as a service, because the form type depends on some other services.

**Comment by vsoroka** [comment]
Hello @mechpave ,

To use form type as a service you need to register it. There are several ways to do this:

- tag your form type service by the tag `oro.api.form.type` 
- `app/config/config.yml` of your application
- `Resources/config/oro/app.yml` of your bundle

For details please see [Forms Configuration in ApiBundle](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/ApiBundle/Resources/doc/forms.md).

**Comment by mechpave** [comment]
@vsoroka, thanks for your answer, I managed to get it working.
But it only started to work when I set the alias of the form to FQCN and also used FQCN in api.yml.
Documentation, on the other hand, uses service id in its example, which can be misleading.
Maybe documentation should be updated?

**Comment by mechpave** [comment]
Hey, I have one more question, but I think ORO Forums would be a better place for such discussions, so I am going to close this issue for now.
Here is a link to my question in the forums: https://www.orocrm.com/?post_type=topic&p=32930
