### ISSUE TITLE
Workflow 'force_autostart' in docs

### ISSUE THREAD

**Issue by sadortun** [orocrm/platform#659]
Hi Oro Team,

There is a few mentions of `force_autostart` in the docs, but it seems that this attribute no longer exists ....

  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Can't parse workflow configuration from workflows.yml. Unrecognized option "force_autostart" under "workflows.my_flow"

Should it be removed from the docs ?

Have a good day,
Samuel

**Comment by mbessolov** [comment]
It should work.
https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/WorkflowBundle/EventListener/WorkflowItemListener.php#L174

Examples:
- https://github.com/orocommerce/orocommerce/blob/master/src/Oro/Bundle/RFPBundle/Resources/config/oro/workflows/b2b_rfq_backoffice_default.yml#L13
- https://github.com/orocommerce/orocommerce/blob/master/src/Oro/Bundle/RFPBundle/Resources/config/oro/workflows/b2b_rfq_frontoffice_default.yml#L12

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
