### ISSUE TITLE
Error during install with empty DB

### ISSUE THREAD

**Issue by scapital** [orocrm/platform#661]
When I try install with empty DB, I always get this error:
There is no column with name 'status_id' on table 'orocrm_sales_opportunity'.

If run command again, error does not occur.

**Comment by mkudelya** [comment]
Hi @scapital 

It is a known bug. Thank you for reporting it.

**Comment by oacevedo** [comment]
the same here

**Comment by mbessolov** [comment]
Fixed in 2.2
4325369e31a2c4f7de5fb5edc7a3fd3f8aad0221
