### ISSUE TITLE
dependency problems when install  platform-application

### ISSUE THREAD

**Issue by videni** [orocrm/platform#669]
composer install --prefer-dist --no-dev -vvv --profile

```
[216.9MB/1812.40s] Downloading https://api.github.com/repos/fat/bean/contents/bower.json?ref=master
[216.8MB/1813.91s] Downloading https://api.github.com/repos/fat/bean/tags?per_page=100


  [Composer\Repository\InvalidRepositoryException]
  No valid bower.json was found in any branch or tag of https://github.com/fat/bean.git, could not
   load a package from it.
```

I am using fxp/composer-asset-plugin  v1.3.0

**Comment by tbondois** [comment]
Hello,

I think I already had this issue.

composer self-update
composer global require fxp/composer-asset-plugin:1.2.2
composer install --prefer-dist  --no-dev

(or without  --no-dev if it still don't works)

**Comment by videni** [comment]
@tbondois, 
using  fxp/composer-asset-plugin 1.2.2  will complain the error below with or without `--no-dev`, 
```
[UnexpectedValueException]
  Could not parse version constraint >=~2: Invalid version string "~2"
```

**Comment by sergeyz** [comment]
@videni @tbondois use
`composer global require fxp/composer-asset-plugin` to get latest stable 1.3 release

**Comment by videni** [comment]
@sergeyz  the latest fxp/composer-asset-plugin is the reason that leads to the issue,

**Comment by tbondois** [comment]
@sergeyz You still have the error : 

  No valid bower.json was found in any branch or tag of https://github.com/fat/bean.git, could not
   load a package from it.

@sergeyz yes i had this error at one point, :
    Could not parse version constraint >=~2: Invalid version string "~2"

Which mysteriously dissapeared after a composer self-update. But now I know where is was coming from, thanks. I was not understanding where it came from because I had not string ">=~2" in my /vendor/

Using "global require" sucks for that...

**Comment by videni** [comment]
@tbondis, yep, any way to solve this problem?

**Comment by tbondois** [comment]
fat/bean is also in my `
vendorbowerassets\bean
web\bundles\bowerassets\bean
`
(i think it's a standard dependance of oroplatfrom), i also don't have a bower.json in that directory, but i don't have problem with. 

And i don't know enough bower to help your debugging with, sorry.

Maybe your can 
- Check if fxp/composer-asset-plugin is correctly linked in the global config linked with your "composer command.
- make another composer self-update
- not use --profile option

And given you have this problem when installing that library and not Oro itself, maybe you should open a  [Fat/bean](https://github.com/fat/bean/issues) or [fxpio](https://github.com/fxpio/composer-asset-plugin/issues) issue ? After reading their README and existing issues of course.

**Comment by mkudelya** [comment]
Hi @videni 

I am using fxp/composer-asset-plugin version 1.3.1, composer version 1.3.2 and I have no problems with `composer install --prefer-dist --no-dev -vvv --profile`. Please tell me, which version of oro are you using ?

**Comment by videni** [comment]
@mkudelya , thank you very much, Because I am evaluating OroPlatform for our new project,  I am always using the code from master branch, now I updated to the latest, it works now,  I think it is  fixed by the latest code  somehow.
