### ISSUE TITLE
Bug: 2.1  EntityExtend Select field override  entity field in datagrid

### ISSUE THREAD

**Issue by sadortun** [orocrm/platform#676]
Hi Oro Team,
/cc @vetal-e 

The JOIN clause of a  select field no longer have an alias in 2.1. This create an issue when you display a Extend field in a datagrid that contain  the `name` propriety.

**This affect all 2.1 installations  Account, and Lead datagrids that have Extend select fields.**

### How to reproduced on demo.orocrm.com : 
1. Create a lead with some values
2.  In Entity Management -> Lead -> Create field
3. Create a "Select" field  "mySelectField"
4.  Add two values  "AAAA" and "BBBB"
5. Save and update schema
6. Edit the lead created in step # 1 and set the 'select' field value to BBBB

**After step # 1**  The lead name is displayed correctly
![image](https://cloud.githubusercontent.com/assets/794449/24843873/c5427738-1d74-11e7-9fd9-b766886c922f.png)

**After Step 5** The sales-lead-grid datagrid looks like this. The lead name is gone.
![image](https://cloud.githubusercontent.com/assets/794449/24843867/b9084fc4-1d74-11e7-8aea-b89984e5351c.png)

**After step 6** The sales-lead-grid now display the `mySelectField.name` value in the `Lead::name` column
![image](https://cloud.githubusercontent.com/assets/794449/24843924/17b3c882-1d75-11e7-8b63-1fe44ed4b40f.png)

## Additional info

In https://github.com/orocrm/platform/blob/b355cc95ecc29dea457d5a81b59cebcdda051ff8/src/Oro/Bundle/DataGridBundle/Datasource/Orm/OrmDatasource.php#L97

```php
$query->_dql ===
"SELECT l.id, l.name, ............. ,  auto_rel_3.name, 
....................
FROM Oro\Bundle\SalesBundle\Entity\Lead l LEFT JOIN l.emails email WITH email.primary = true 
.................
LEFT JOIN l.myselectfield auto_rel_3 
............
ORDER BY l.createdAt DESC
";
```

**Comment by sadortun** [comment]
This seems to fix the issue. Use at your on risk ! 
https://github.com/sadortun/platform/commit/c2197057b2279388e029009e12949e9fe9f49dfd

**Comment by manowark** [comment]
Hi, @sadortun.

Thank you for reporting this issue. We will fix it in short time.

**Comment by sadortun** [comment]
Hi @manowark 
> We will fix it in short time.
Are you  waiting for `open for contribution` or  it is `scheduled for implementation`  ?

**Comment by manowark** [comment]
@sadortun, this task still in our backlog and we will fix it as soon as we can. Thank you!

**Comment by sadortun** [comment]
https://github.com/orocrm/platform/issues/676#issuecomment-311901230
> Fixes for related issues already in master. Can I close that PR
