### ISSUE TITLE
2.1 Behat testing produces Fatal error: Class 'Oro\Bundle\TestFrameworkBundle\Behat\Element\Transformers\PageSuffixTransformerInterface' not found 

### ISSUE THREAD

**Issue by dimonixx** [orocrm/platform#680]
The class in the file Oro/Bundle/TestFrameworkBundle/Behat/Element/Transformers/PageSuffixTransformer.php
has `PageSuffixTransformerInterface` name but should actually be `PageSuffixTransformer`.

**Comment by mkudelya** [comment]
Hi @dimonixx 

Thank you for pointing out the issue! The fix will be available in the next release.

**Comment by mkudelya** [comment]
The fix is already in the master branch. I'm closing this issue.
