### ISSUE TITLE
The documentation wrongly says that the WSEE header lifetime is 300 seconds, but really it is 3600 seconds

### ISSUE THREAD

**Issue by dmitry-fedyuk** [orocrm/platform#709]
https://github.com/orocrm/documentation/blob/temp2.0/cookbook/how_to_use_wsse_authentication.rst#header-and-nonce-lifetime
https://github.com/orocrm/platform/blob/2.2.0/src/Oro/Bundle/ApiBundle/Resources/config/oro/app.yml#L21-L22

**Comment by NiMias** [comment]
Hi, @dmitry-fedyuk !

The mistake just was corrected on orocrm.com site (https://www.orocrm.com/documentation/current/cookbook/how-to-use-wsse-authentication) and shortly this change will appear in documentation repository https://github.com/orocrm/documentation/blob/master/cookbook/how_to_use_wsse_authentication.rst (accordingly to our document publishing flow).

Thank you very much for your contribution!
