### ISSUE TITLE
[Composer\Repository\InvalidRepositoryException]                                                                                       No valid bower.json was found in any branch or tag of https://github.com/jquery/jquery-dist.git, could not load a package from it.

### ISSUE THREAD

**Issue by CodeingMonkey** [orocrm/platform#716]
composer  install or composer update occurs the problem。
Installation environment：lnmp
Installation process：
1：curl -sS https://getcomposer.org/installer | php
2：php composer.phar global require "fxp/composer-asset-plugin:^1.2.0"
3：php composer.phar create-project yiisoft/yii2-app-basic basic 2.0.12
When the third step is performed，occur the exception
![image](https://user-images.githubusercontent.com/20737017/27468581-257b42e6-581d-11e7-9872-eb4e519bc5a1.png)

**Comment by CodeingMonkey** [comment]
My solution
vi  composer.json
update  config
![image](https://user-images.githubusercontent.com/20737017/27470967-abc5f688-5828-11e7-90c3-ff8d372a9d1b.png)
github.com:
Authorization code

**Comment by mbessolov** [comment]
@CodeingMonkey is it related to OroPlatform? From what I see you are installing Yii2 application.
