### ISSUE TITLE
please merge simplified Chinese into Crowdin, so I can contribute. 

### ISSUE THREAD

**Issue by videni** [orocrm/platform#719]
I'd like to help Chinese translation in Crowdin, I found someone has done lots of work in [this repo](https://github.com/TonyGao/OroPlatformTranslation)  , I contact its author , he will not contribute it using Crowdin, please merge that repo,  so I can continue.

**Comment by mbessolov** [comment]
@videni We do not merge/keep translation in the repository. You should upload the translation files to OroPlatform project on CrowdIn - https://crowdin.com/project/oro-platform/

**Comment by videni** [comment]
@mbessolov, What I am saying is that someone in oro group should upload that translation to crowdin first, so it can save me some time.

**Comment by mbessolov** [comment]
@videni any person (who joined the project on CrowdIn as translator) can upload translation files:

![upload-crowdin-translation-suggestions](https://user-images.githubusercontent.com/2725121/27536115-65dc0748-5a76-11e7-8f1b-dd9cf90fb816.png)

And there is a number of free Symfony YAML to XLIFF converters available on the web.

Thank you for your interest to the project and contributing to its translation to Chinese.

**Comment by miguelrincon** [comment]
@videni In the end, did you upload those files in the crowdin platform? I tested but I cannot see some of the translations uploaded to crowdin.

@mbessolov I am very interested in looking into this and contributing, but at the moment I am concerned that quite a few Chinese translations are not yet approved (some are about 1 year old).

Are you interested in having my team in China contributing as proofreader? I have sent a message via crowdin as well.

**Comment by mbessolov** [comment]
@miguelrincon Yes, sure, I'll check the CrowdIn inbox.
