### ISSUE TITLE
Address Collection : When Country Is Changed the Sates Don't get re-populated. 

### ISSUE THREAD

**Issue by sachingk** [orocrm/platform#723]
I see there  is a bug when using address collection.  When the country is changed , the states have to re populate. However this is not happening. 

I see this bug in ORO Commerce in the Admin Customer Management Screen - Both in Add Address via popup & Edit customer screen. 

I guess this  bug is because is AddressCollectionTypeSubscriber missing from the Github Source code. But Documentation say I have to add that as a Event Listener to the form

**Comment by aivus** [comment]
Hi, @sachingk.

Thank you for your request.
Which version of platform/orocommerce are you using?
Could you explain your issue or write steps to reproduce?

I just tested on latest master and `State` field is changed after changing `Country` field.

**Comment by aivus** [comment]
Discussion moved to https://github.com/orocommerce/orocommerce/issues/42
