### ISSUE TITLE
Date filters in data grids

### ISSUE THREAD

**Issue by andesk** [orocrm/platform#89]
Hi there,

it seems that the datepickers for datagrid filters of type "date" have an issue right now leading to page reload with empty hashtag (so manily redirects to dashboard) when clicking on a date.

Did assetic:dump and assets:install before. Oro platform version is 1.1.0, but as I did not see any mentions of that in issues/changelog/etc I think this might still be valid in 1.2.0.

Browsers:
- Firefox, only for "lower than" and "more than", javascript error:  "TypeError: e.datepicker._curInst is null" in oro.min.js:357
- Chrome, occurs on any sub filter type, javascript error: "Uncaught TypeError: Cannot read property 'input' of null" in oro.min.js:357

Any further information needed?

**Comment by iklymenko** [comment]
Please check 1.4.4 or latest stable release. Should be fixed there.
